package es.redsara.misim.misim_bus_webapp;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2016-04-26T10:40:54.595+02:00
 * Generated source version: 2.6.3
 * 
 */
@SuppressWarnings("restriction")
@WebServiceClient(name = "OperacionMensajesService", 
                  wsdlLocation = "./wsdl/OperacionesMensajes.wsdl",
                  targetNamespace = "http://misim.redsara.es/misim-bus-webapp/") 
public class OperacionMensajesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://misim.redsara.es/misim-bus-webapp/", "OperacionMensajesService");
    public final static QName OperacionMensajesServicePort = new QName("http://misim.redsara.es/misim-bus-webapp/", "OperacionMensajesServicePort");
    static {
        URL url = OperacionMensajesService.class.getResource("./wsdl/OperacionesMensajes.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(OperacionMensajesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "./wsdl/OperacionesMensajes.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public OperacionMensajesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperacionMensajesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperacionMensajesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public OperacionMensajesService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public OperacionMensajesService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public OperacionMensajesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns OperacionMensajesServicePortType
     */
    @WebEndpoint(name = "OperacionMensajesServicePort")
    public OperacionMensajesServicePortType getOperacionMensajesServicePort() {
        return super.getPort(OperacionMensajesServicePort, OperacionMensajesServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OperacionMensajesServicePortType
     */
    @WebEndpoint(name = "OperacionMensajesServicePort")
    public OperacionMensajesServicePortType getOperacionMensajesServicePort(WebServiceFeature... features) {
        return super.getPort(OperacionMensajesServicePort, OperacionMensajesServicePortType.class, features);
    }

}
