package es.redsara.misim.misim_bus_webapp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * 2016-04-26T10:40:54.581+02:00
 * Generated source version: 2.6.3
 * 
 */
@SuppressWarnings("restriction")
@WebService(targetNamespace = "http://misim.redsara.es/misim-bus-webapp/", name = "OperacionMensajesServicePortType")
@XmlSeeAlso({es.redsara.misim.misim_bus_webapp.peticionOperacion.ObjectFactory.class, es.redsara.misim.misim_bus_webapp.respuestaOperacion.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OperacionMensajesServicePortType {

	 @WebResult(name = "Respuesta", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/respuesta", partName = "respuesta")
    @WebMethod(action = "anularMensaje")
    public es.redsara.misim.misim_bus_webapp.respuestaOperacion.RespuestaOperacion anularMensaje(
        @WebParam(partName = "peticion", name = "PeticionMensaje", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/peticion")
        es.redsara.misim.misim_bus_webapp.peticionOperacion.PeticionMensaje peticion
    );

    @WebResult(name = "Respuesta", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/respuesta", partName = "respuesta")
    @WebMethod(action = "reenviarMensaje")
    public es.redsara.misim.misim_bus_webapp.respuestaOperacion.RespuestaOperacion reenviarMensaje(
        @WebParam(partName = "peticionReenviar", name = "PeticionMensaje", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/peticion")
        es.redsara.misim.misim_bus_webapp.peticionOperacion.PeticionMensaje peticionReenviar
    );

    @WebResult(name = "Respuesta", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/respuesta", partName = "respuesta")
    @WebMethod(action = "anularLote")
    public es.redsara.misim.misim_bus_webapp.respuestaOperacion.RespuestaOperacion anularLote(
        @WebParam(partName = "peticion", name = "PeticionLote", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/peticion")
        es.redsara.misim.misim_bus_webapp.peticionOperacion.PeticionLote peticion
    );
	    
    @WebResult(name = "Respuesta", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/respuesta", partName = "respuesta")
    @WebMethod(action = "reenviarLote")
    public es.redsara.misim.misim_bus_webapp.respuestaOperacion.RespuestaOperacion reenviarLote(
        @WebParam(partName = "peticionReenviar", name = "PeticionLote", targetNamespace = "http://misim.redsara.es/misim-bus-webapp/peticion")
        es.redsara.misim.misim_bus_webapp.peticionOperacion.PeticionLote peticionReenviar
    );
}
