package es.mpr.plataformamensajeria.ws.envionotificacionespush;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://envionotificacionpush.ws.plataformamensajeria.minhap.es/", name = "IEnvioNotificacionPushService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IEnvioNotificacionPushService {

    @WebResult(name = "envioNotificacionPushResponse", targetNamespace = "http://envionotificacionpush.ws.plataformamensajeria.minhap.es/", partName = "parameters")
    @WebMethod
    public EnvioNotificacionPushResponse envioNotificacionPush(
        @WebParam(partName = "parameters", name = "envioNotificacionPushRequest", targetNamespace = "http://envionotificacionpush.ws.plataformamensajeria.minhap.es/")
        EnvioNotificacionPushRequest parameters
    );
}
