
package es.mpr.plataformamensajeria.ws.envionotificacionespush;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.3
 * Generated source version: 2.6.3
 * 
 */
 
public class IEnvioNotificacionPushService_EnvioNotificacionPushImplPort_Server{

    protected IEnvioNotificacionPushService_EnvioNotificacionPushImplPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IEnvioNotificacionPushServiceImpl();
        String address = "http://des-sim.redsara.es/PlataformaMensajeriaWS/EnvioNotificacionPush";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IEnvioNotificacionPushService_EnvioNotificacionPushImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
