package es.minhap.plataformamensajeria.iop.services.usuariosplataformas;

import es.minhap.plataformamensajeria.iop.beans.UsuariosXMLBean;

/**
 * This class was generated by Apache CXF 2.6.3
 * Generated source version: 2.6.3
 * 
 */

public interface IRegistroUsuarioPushService {

	public RegistroUsuarioPushResponse registroUsuario(String nombreUsuario, String servicioId, String usuario, String password,
			String plataformaId, String tokenUsuario, String dispositivoId, String tokenSession,
			String uidDispositivo);
	
	public RegistroUsuarioPushResponse registroUsuario(UsuariosXMLBean usuariosXML);
	
	public boolean eliminarUsuario(String tokem);

	
    
}
