package es.map.xml_schemas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2016-02-12T12:15:51.876+01:00
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "MICCAsincrono", 
                  wsdlLocation = "file:/C:/workspace_MISIM/maven.1453279207193/misim-bus/misim-bus-core/src/main/resources/wsdl/peticion-asincrona.wsdl",
                  targetNamespace = "http://www.map.es/xml-schemas") 
public class MICCAsincrono_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.map.es/xml-schemas", "MICCAsincrono");
    public final static QName MICCAsincrono = new QName("http://www.map.es/xml-schemas", "MICCAsincrono");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace_MISIM/maven.1453279207193/misim-bus/misim-bus-core/src/main/resources/wsdl/peticion-asincrona.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MICCAsincrono_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace_MISIM/maven.1453279207193/misim-bus/misim-bus-core/src/main/resources/wsdl/peticion-asincrona.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MICCAsincrono_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MICCAsincrono_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MICCAsincrono_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MICCAsincrono_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MICCAsincrono_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MICCAsincrono_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MICCAsincrono
     */
    @WebEndpoint(name = "MICCAsincrono")
    public MICCAsincrono getMICCAsincrono() {
        return super.getPort(MICCAsincrono, MICCAsincrono.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MICCAsincrono
     */
    @WebEndpoint(name = "MICCAsincrono")
    public MICCAsincrono getMICCAsincrono(WebServiceFeature... features) {
        return super.getPort(MICCAsincrono, MICCAsincrono.class, features);
    }

}
