package es.mpr.plataformamensajeria.ws.recepcion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://recepcion.ws.plataformamensajeria.minhap.es/", name = "IRecepcionMensajesService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IRecepcionMensajesService {

    @WebResult(name = "recibirSMSResponse", targetNamespace = "http://recepcion.ws.plataformamensajeria.minhap.es/", partName = "parameters")
    @WebMethod
    public RecibirSMSResponse recibirSMS(
        @WebParam(partName = "parameters", name = "recibirSMSRequest", targetNamespace = "http://recepcion.ws.plataformamensajeria.minhap.es/")
        RecibirSMSRequest parameters
    );
}
