<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema"  
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:impl="http://misim.redsara.es/misim-bus-webapp/"  
	xmlns:ns1="http://misim.redsara.es/misim-bus-webapp/peticion" 
	xmlns:ns2="http://misim.redsara.es/misim-bus-webapp/respuesta"
	targetNamespace="http://misim.redsara.es/misim-bus-webapp/">
	<wsdl:types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.map.es/xml-schemas">
			<import namespace="http://misim.redsara.es/misim-bus-webapp/peticion" schemaLocation="peticion.xsd"/>
			<import namespace="http://misim.redsara.es/misim-bus-webapp/respuesta" schemaLocation="respuesta.xsd"/>
		</schema>
	</wsdl:types>
	<wsdl:message name="enviar001Peticion">
		<wsdl:part name="peticion" element="ns1:Peticion"/>
	</wsdl:message>
	<wsdl:message name="enviar001Respuesta">
		<wsdl:part name="respuesta" element="ns2:Respuesta"/>
	</wsdl:message>
	<wsdl:portType name="Envio001ServiceWSBindingPortType">
		<wsdl:operation name="enviar001">
			<wsdl:input name="Peticion" message="impl:enviar001Peticion"/>
			<wsdl:output name="Respuesta" message="impl:enviar001Respuesta"/>
		</wsdl:operation>
		
	</wsdl:portType>
	<wsdl:binding name="Envio001ServiceBinding" type="impl:Envio001ServiceWSBindingPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="enviar001">
			<soap:operation soapAction="enviar001" style="document"/>
			<wsdl:input>
				<soap:body parts="peticion" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="respuesta" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="Envio001Service">
		<wsdl:port name="Envio001ServicePort" binding="impl:Envio001ServiceBinding">
<!-- 			<soap:address location="http://des-misim.redsara.es:8081/misim-bus-webapp/EnvioMensajesService"/> -->
			<soap:address location="/misim-bus-webapp/Envio001Service"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
