drop table FWK_AUDIT cascade constraints;

CREATE TABLE FWK_AUDIT
(
  IP_USUARIO         VARCHAR2(15 BYTE),
  OPERACION          VARCHAR2(150 BYTE),
  USUARIO            VARCHAR2(150 BYTE),
  DATOS_ENTRADA      CLOB,
  DATOS_REPUESTA     CLOB,
  RESULTADO          VARCHAR2(150 BYTE),
  FECHA              DATE,
  ID                 NUMBER(5),
  T_PROCESADO        NUMBER,
  CONSTRAINT FWK_AUDIT_PK PRIMARY KEY (ID)
);


DROP SEQUENCE FWK_AUDIT_SEQ;

CREATE SEQUENCE FWK_AUDIT_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
