
CREATE TABLE FWK_GROUP
(
  IDGROUP           NUMBER,
  NAME         VARCHAR2(255 BYTE),
  DESCRIPTION  VARCHAR2(255 BYTE)
);


CREATE TABLE FWK_USUARIO
(
  IDUSUARIO                NUMBER(5)            NOT NULL,
  USERNAME                 VARCHAR2(50 BYTE),
  DESCRIPCION              VARCHAR2(250 BYTE),
  APELLIDOS                VARCHAR2(250 BYTE),
  NOMBRE                   VARCHAR2(250 BYTE),
  PASSWORD                 VARCHAR2(250 BYTE),
  TELEFONO              VARCHAR2(250 BYTE),
  EMAIL                 VARCHAR2(250 BYTE),
  organismo		NUMBER(5),
  unidadOrganizacional  NUMBER(5),
  nif			VARCHAR2(50 BYTE),
  cif			VARCHAR2(50 BYTE),
  email2		VARCHAR2(250 BYTE),
  telefono2		VARCHAR2(250 BYTE),
  movil			VARCHAR2(250 BYTE),
  direccion		VARCHAR2(250 BYTE),
  numero		VARCHAR2(250 BYTE),
  piso			VARCHAR2(250 BYTE),
  puerta		VARCHAR2(250 BYTE),
  escalera		VARCHAR2(250 BYTE),
  ciudad		VARCHAR2(250 BYTE),
  provincia		VARCHAR2(250 BYTE),
  pais		VARCHAR2(250 BYTE),
  codigoPostal		VARCHAR2(250 BYTE),
  Pregunta		VARCHAR2(250 BYTE),
  Respuesta		VARCHAR2(250 BYTE),
  mailNoticias		VARCHAR2(250 BYTE),
  mailNovedades		VARCHAR2(250 BYTE),
  mailContenidos		VARCHAR2(250 BYTE),
  mailServicios		VARCHAR2(250 BYTE),
  mailCampanias		VARCHAR2(250 BYTE),
  fax		VARCHAR2(250 BYTE),
  puntosContacto		VARCHAR2(250 BYTE),
  despacho		VARCHAR2(250 BYTE)
);


CREATE TABLE FWK_USERGROUPS
(
  IDUSUARIO   NUMBER,
  IDGROUP  NUMBER
);


ALTER TABLE FWK_GROUP ADD (
  PRIMARY KEY
 (IDGROUP));


ALTER TABLE FWK_USUARIO ADD (
  PRIMARY KEY
 (IDUSUARIO));
                   

alter table FWK_USERGROUPS add constraint FKuserGroupsToUsers foreign key (IDUSUARIO) references FWK_USUARIO(IDUSUARIO);

alter table FWK_USERGROUPS add constraint FKuserGroupsToGroups foreign key (IDGROUP) references FWK_GROUP(IDGROUP);


DROP SEQUENCE FWK_USUARIO_SEQ;

CREATE SEQUENCE FWK_USUARIO_SEQ
  START WITH 2
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


DROP SEQUENCE FWK_GROUP_SEQ;

CREATE SEQUENCE FWK_GROUP_SEQ
  START WITH 2
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


ALTER TABLE FWK_USUARIO ADD UNIQUE (USERNAME);

ALTER TABLE FWK_GROUP ADD UNIQUE (NAME);

INSERT INTO FWK_USUARIO ( IDUSUARIO, USERNAME, DESCRIPCION, APELLIDOS, NOMBRE, PASSWORD, TELEFONO,
EMAIL, ORGANISMO, UNIDADORGANIZACIONAL, NIF, CIF, EMAIL2, TELEFONO2, MOVIL, DIRECCION, NUMERO, PISO,
PUERTA, ESCALERA, CIUDAD, PROVINCIA, PAIS, CODIGOPOSTAL, PREGUNTA, RESPUESTA, MAILNOTICIAS,
MAILNOVEDADES, MAILCONTENIDOS, MAILSERVICIOS, MAILCAMPANIAS, FAX, PUNTOSCONTACTO,
DESPACHO ) VALUES ( 
1, 'admin, NULL, NULL, NULL, '{SHA}0DPiKuNIrrVmD8IUCuw1hQxNqZc=', NULL
, NULL, NULL, 123, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 

COMMIT;

INSERT INTO FWK_GROUP ( IDGROUP, NAME, DESCRIPTION ) VALUES ( 
1, 'ADMINFWK', 'ADMINFWK'); 
COMMIT;



INSERT INTO FWK_USERGROUPS ( IDUSUARIO, IDGROUP ) VALUES ( 
1, 1); 
COMMIT;
