package es.minhap.misim.bus.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 09-sep-2015 11:41:17 by Hibernate Tools 3.4.0.CR1


/**
 * Comunicacion generated by hbm2java
 */
@Entity
@Table(name = "COMUNICACION")
public class Comunicacion implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Long idComunicacion;
	private String nombre;

	public Comunicacion() {
	}

	@Id
	@Column(name = "ID_COMUNICACION", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getIdComunicacion() {
		return this.idComunicacion;
	}

	public void setIdComunicacion(Long idComunicacion) {
		this.idComunicacion = idComunicacion;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
