package es.minhap.misim.bus.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

// Generated 09-sep-2015 11:41:17 by Hibernate Tools 3.4.0.CR1


/**
 * Aplicacion generated by hbm2java
 */
@Entity
@Table(name = "ERRORES")
public class Errores implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Long idError;
	private String nombre;
	private Boolean estado;
	private Date fechaActualizacion;

	public Errores() {
	}

	@Id
	@Column(name = "ID_ERROR", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getIdError() {
		return idError;
	}

	public void setIdError(Long idError) {
		this.idError = idError;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ESTADO", length = 1)
	public Boolean getEstado() {
		return estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "FECHA_ACTUALIZACION", length = 7)
	public Date getFechaActualizacion() {
		return fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
