package es.minhap.misim.bus.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 09-sep-2015 11:41:17 by Hibernate Tools 3.4.0.CR1


/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "ESTADO")
public class Estado implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Long idEstado;
	private String nombre;

	public Estado() {
	}

	@Id
	@Column(name = "ID_ESTADO", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Long idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
