package es.minhap.misim.bus.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// Generated 09-sep-2015 11:41:17 by Hibernate Tools 3.4.0.CR1


/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "PROVEEDOR")
public class Proveedor implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Long idProveedor;
	private Endpoint endpoint;
	private Producto producto;
	private Transformacion transformacion;
	private String nombre;
	private String usuario;
	private String password;
	private String company;
	private String type;
	private String certificado;
	private String certificadoPass;
	private String firma;
	private String tipoFirma;
	private String cifrado;
	private String nodoCifrado;
	private String esquemaCifrado;

	public Proveedor() {
	}

	@Id
	@Column(name = "ID_PROVEEDOR", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Long idProveedor) {
		this.idProveedor = idProveedor;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_ENDPOINT", nullable = false)
	public Endpoint getEndpoint() {
		return this.endpoint;
	}

	public void setEndpoint(Endpoint endpoint) {
		this.endpoint = endpoint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_TRANSFORMACION")
	public Transformacion getTransformacion() {
		return this.transformacion;
	}

	public void setTransformacion(Transformacion transformacion) {
		this.transformacion = transformacion;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "USUARIO", length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "PASSWORD", length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "COMPANY", length = 40)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}
	
	@Column(name = "CERTIFICADO", length = 100)
	public String getCertificado() {
		return this.certificado;
	}

	public void setCertificado(String certificado) {
		this.certificado = certificado;
	}
	
	@Column(name = "CERTIFICADO_PASS", length = 40)
	public String getCertificadoPass() {
		return this.certificadoPass;
	}

	public void setCertificadoPass(String certificadoPass) {
		this.certificadoPass = certificadoPass;
	}
	
	@Column(name = "FIRMA", length = 1)
	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}
	
	@Column(name = "TIPO_FIRMA", length = 40)
	public String getTipoFirma() {
		return this.tipoFirma;
	}

	public void setTipoFirma(String tipoFirma) {
		this.tipoFirma = tipoFirma;
	}

	@Column(name = "CIFRADO", length = 1)
	public String getCifrado() {
		return this.cifrado;
	}

	public void setCifrado(String cifrado) {
		this.cifrado = cifrado;
	}
	
	@Column(name = "NODO_CIFRADO", length = 100)
	public String getNodoCifrado() {
		return this.nodoCifrado;
	}

	public void setNodoCifrado(String nodoCifrado) {
		this.nodoCifrado = nodoCifrado;
	}
	
	@Column(name = "ESQUEMA_CIFRADO", length = 100)
	public String getEsquemaCifrado() {
		return this.esquemaCifrado;
	}

	public void setEsquemaCifrado(String esquemaCifrado) {
		this.esquemaCifrado = esquemaCifrado;
	}

	@Column(name = "TYPE", length = 40)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
