package es.map.xml_schemas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2016-02-12T12:15:51.363+01:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://www.map.es/xml-schemas", name = "MICCSincrono")
@XmlSeeAlso({es.redsara.intermediacion.scsp.esquemas.v3.peticion.ObjectFactory.class, es.redsara.intermediacion.scsp.esquemas.datosespecificos.ObjectFactory.class, es.redsara.intermediacion.scsp.esquemas.v3.respuesta.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MICCSincrono {

    @WebResult(name = "Respuesta", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/V3/respuesta", partName = "respuesta")
    @WebMethod(action = "peticionSincrona")
    public es.redsara.intermediacion.scsp.esquemas.v3.respuesta.Respuesta peticionSincrona(
        @WebParam(partName = "peticion", name = "Peticion", targetNamespace = "http://intermediacion.redsara.es/scsp/esquemas/V3/peticion")
        es.redsara.intermediacion.scsp.esquemas.v3.peticion.Peticion peticion
    );
}
