package es.minhap.misim.bus.model;

// Generated 09-sep-2015 11:41:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Endpoint generated by hbm2java
 */
@Entity
@Table(name = "ENDPOINT")
public class Endpoint implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Long idEndpoint;
	private Comunicacion comunicacion;
	private String nombre;
	private String urlEndpoint;
	private String serviceName;
	private String portName;
	private String targetName;
	private String operation;
	private Long timeout;
	private Date fechaCreacion;
	private Date fechaActualizacion;

	public Endpoint() {
	}

	@Id
	@Column(name = "ID_ENDPOINT", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getIdEndpoint() {
		return this.idEndpoint;
	}

	public void setIdEndpoint(Long idEndpoint) {
		this.idEndpoint = idEndpoint;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COMUNICACION", nullable = false)
	public Comunicacion getComunicacion() {
		return this.comunicacion;
	}

	public void setComunicacion(Comunicacion comunicacion) {
		this.comunicacion = comunicacion;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "URL_ENDPOINT", nullable = false, length = 255)
	public String getUrlEndpoint() {
		return this.urlEndpoint;
	}

	public void setUrlEndpoint(String urlEndpoint) {
		this.urlEndpoint = urlEndpoint;
	}

	@Column(name = "SERVICE_NAME", length = 100)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "PORT_NAME",length = 100)
	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	@Column(name = "TARGET_NAME", length = 255)
	public String getTargetName() {
		return this.targetName;
	}

	public void setTargetName(String targetName) {
		this.targetName = targetName;
	}

	@Column(name = "OPERATION", length = 100)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "TIMEOUT", precision = 22, scale = 0)
	public Long getTimeout() {
		return this.timeout;
	}

	public void setTimeout(Long timeout) {
		this.timeout = timeout;
	}

	@Column(name = "FECHA_CREACION", nullable = false, length = 7)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "FECHA_ACTUALIZACION", nullable = false, length = 7)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

}
