package es.minhap.misim.bus.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

// Generated 09-sep-2015 11:41:17 by Hibernate Tools 3.4.0.CR1


/**
 * Peticion generated by hbm2java
 */
@Entity
@Table(name = "PETICION")
public class Peticion implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private Long idPeticion;
	private Proveedor proveedor;
	private Estado estado;
	private Aplicacion aplicacion;
	private Producto producto;
	private Long idMensaje;
	private String mensajePeticion;
	private String mensajeRespuesta;

	public Peticion() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO, generator="generator")
	@SequenceGenerator(name="generator",sequenceName="SEQ_PETICION")
	@Column(name = "ID_PETICION", unique = true, nullable = false, precision = 20, scale = 0)
	public Long getIdPeticion() {
		return this.idPeticion;
	}

	public void setIdPeticion(Long idPeticion) {
		this.idPeticion = idPeticion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROVEEDOR", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ESTADO", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_APLICACION", nullable = false)
	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PRODUCTO", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "ID_MENSAJE", precision = 20, scale = 0)
	public Long getIdMensaje() {
		return this.idMensaje;
	}

	public void setIdMensaje(Long idMensaje) {
		this.idMensaje = idMensaje;
	}

	@Column(name = "MENSAJE_PETICION", nullable = false)
	public String getMensajePeticion() {
		return this.mensajePeticion;
	}

	public void setMensajePeticion(String mensajePeticion) {
		this.mensajePeticion = mensajePeticion;
	}

	@Column(name = "MENSAJE_RESPUESTA")
	public String getMensajeRespuesta() {
		return this.mensajeRespuesta;
	}

	public void setMensajeRespuesta(String mensajeRespuesta) {
		this.mensajeRespuesta = mensajeRespuesta;
	}

}
