package es.mpr.plataformamensajeria.ws.usuariosplataformas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://registrousuario.ws.plataformamensajeria.minhap.es/", name = "IRegistroUsuarioService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IRegistroUsuarioService {

    @WebResult(name = "registroUsuarioResponse", targetNamespace = "http://registrousuario.ws.plataformamensajeria.minhap.es/", partName = "parameters")
    @WebMethod
    public RegistroUsuarioResponse registroUsuario(
        @WebParam(partName = "parameters", name = "registroUsuarioRequest", targetNamespace = "http://registrousuario.ws.plataformamensajeria.minhap.es/")
        RegistroUsuarioRequest parameters
    );
}
