package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TblAplicaciones generated by hbm2java
 */
@Entity
@Table(name = "TBL_APLICACIONES")
public class TblAplicaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5913863977101061496L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="APLICACIONID_SEC")
    @SequenceGenerator(name="APLICACIONID_SEC", sequenceName="APLICACIONID_SEC", allocationSize=1)
	@Column(name = "APLICACIONID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "NOMBRE", length = 100)
	private String nombre;

	@Column(name = "DESCRIPCION", length = 500)
	private String descripcion;

	@Column(name = "ACTIVO")
	private Boolean activo;

	@Column(name = "FECHACREACION", length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", length = 100)
	private String creadopor;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadopor;

	@Column(name = "USUARIO", length = 50)
	private String usuario;

	@Column(name = "PASSWORD", length = 50)
	private String password;

	@Column(name = "ELIMINADO", length = 1)
	private String eliminado;

	@Column(name = "RESP_FUNCIONAL_NOMBRE", length = 100)
	private String respFuncionalNombre;

	@Column(name = "RESP_FUNCIONAL_EMAIL", length = 100)
	private String respFuncionalEmail;

	@Column(name = "RESP_TECNICO_NOMBRE", length = 100)
	private String respTecnicoNombre;

	@Column(name = "RESP_TECNICO_EMAIL", length = 100)
	private String respTecnicoEmail;

	public TblAplicaciones() {
	}

	/**
	 * @return the aplicacionid
	 */
	public Long getAplicacionid() {
		return aplicacionid;
	}

	/**
	 * @param aplicacionid
	 *            the aplicacionid to set
	 */
	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre
	 *            the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion
	 *            the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor
	 *            the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	/**
	 * @return the fechamodificacion
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * @param fechamodificacion
	 *            the fechamodificacion to set
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * @return the modificadopor
	 */
	public String getModificadopor() {
		return modificadopor;
	}

	/**
	 * @param modificadopor
	 *            the modificadopor to set
	 */
	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	/**
	 * @return the usuario
	 */
	public String getUsuario() {
		return usuario;
	}

	/**
	 * @param usuario
	 *            the usuario to set
	 */
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the eliminado
	 */
	public String getEliminado() {
		return eliminado;
	}

	/**
	 * @param eliminado
	 *            the eliminado to set
	 */
	public void setEliminado(String eliminado) {
		this.eliminado = eliminado;
	}

	/**
	 * @return the respFuncionalNombre
	 */
	public String getRespFuncionalNombre() {
		return respFuncionalNombre;
	}

	/**
	 * @param respFuncionalNombre
	 *            the respFuncionalNombre to set
	 */
	public void setRespFuncionalNombre(String respFuncionalNombre) {
		this.respFuncionalNombre = respFuncionalNombre;
	}

	/**
	 * @return the respFuncionalEmail
	 */
	public String getRespFuncionalEmail() {
		return respFuncionalEmail;
	}

	/**
	 * @param respFuncionalEmail
	 *            the respFuncionalEmail to set
	 */
	public void setRespFuncionalEmail(String respFuncionalEmail) {
		this.respFuncionalEmail = respFuncionalEmail;
	}

	/**
	 * @return the respTecnicoNombre
	 */
	public String getRespTecnicoNombre() {
		return respTecnicoNombre;
	}

	/**
	 * @param respTecnicoNombre
	 *            the respTecnicoNombre to set
	 */
	public void setRespTecnicoNombre(String respTecnicoNombre) {
		this.respTecnicoNombre = respTecnicoNombre;
	}

	/**
	 * @return the respTecnicoEmail
	 */
	public String getRespTecnicoEmail() {
		return respTecnicoEmail;
	}

	/**
	 * @param respTecnicoEmail
	 *            the respTecnicoEmail to set
	 */
	public void setRespTecnicoEmail(String respTecnicoEmail) {
		this.respTecnicoEmail = respTecnicoEmail;
	}

	/**
	 * @return the activo
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * @param activo
	 *            the activo to set
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

}
