package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblAyuda generated by hbm2java
 */
@Entity
@Table(name = "TBL_AYUDA")
public class TblAyuda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8445094541420820361L;
	@Id
	@Column(name = "AYUDAID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long ayudaid;

	@Column(name = "TEXTOAYUDA", length = 2000)
	private String textoayuda;

	@Column(name = "FECHACREACION", length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", length = 100)
	private String creadopor;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadopor;

	public TblAyuda() {
	}

	/**
	 * @return the ayudaid
	 */
	public Long getAyudaid() {
		return ayudaid;
	}

	/**
	 * @param ayudaid
	 *            the ayudaid to set
	 */
	public void setAyudaid(Long ayudaid) {
		this.ayudaid = ayudaid;
	}

	/**
	 * @return the textoayuda
	 */
	public String getTextoayuda() {
		return textoayuda;
	}

	/**
	 * @param textoayuda
	 *            the textoayuda to set
	 */
	public void setTextoayuda(String textoayuda) {
		this.textoayuda = textoayuda;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor
	 *            the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	/**
	 * @return the fechamodificacion
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * @param fechamodificacion
	 *            the fechamodificacion to set
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * @return the modificadopor
	 */
	public String getModificadopor() {
		return modificadopor;
	}

	/**
	 * @param modificadopor
	 *            the modificadopor to set
	 */
	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	
}
