package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblConfigId generated by hbm2java
 */
@Embeddable
public class TblConfigId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4222149720798151194L;
	@Column(name = "MAIL_LISENER_STATUS", length = 120)
	private String mailLisenerStatus;

	@Column(name = "START_LISTENER_ON_DB_START_UP", length = 3)
	private String startListenerOnDbStartUp;

	@Column(name = "LISTENER_RUN_MODE", length = 60)
	private String listenerRunMode;

	public TblConfigId() {
	}

	/**
	 * @return the mailLisenerStatus
	 */
	public String getMailLisenerStatus() {
		return mailLisenerStatus;
	}

	/**
	 * @param mailLisenerStatus
	 *            the mailLisenerStatus to set
	 */
	public void setMailLisenerStatus(String mailLisenerStatus) {
		this.mailLisenerStatus = mailLisenerStatus;
	}

	/**
	 * @return the startListenerOnDbStartUp
	 */
	public String getStartListenerOnDbStartUp() {
		return startListenerOnDbStartUp;
	}

	/**
	 * @param startListenerOnDbStartUp
	 *            the startListenerOnDbStartUp to set
	 */
	public void setStartListenerOnDbStartUp(String startListenerOnDbStartUp) {
		this.startListenerOnDbStartUp = startListenerOnDbStartUp;
	}

	/**
	 * @return the listenerRunMode
	 */
	public String getListenerRunMode() {
		return listenerRunMode;
	}

	/**
	 * @param listenerRunMode
	 *            the listenerRunMode to set
	 */
	public void setListenerRunMode(String listenerRunMode) {
		this.listenerRunMode = listenerRunMode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblConfigId))
			return false;
		TblConfigId castOther = (TblConfigId) other;

		return ((this.getMailLisenerStatus() == castOther
				.getMailLisenerStatus()) || (this.getMailLisenerStatus() != null
				&& castOther.getMailLisenerStatus() != null && this
				.getMailLisenerStatus()
				.equals(castOther.getMailLisenerStatus())))
				&& ((this.getStartListenerOnDbStartUp() == castOther
						.getStartListenerOnDbStartUp()) || (this
						.getStartListenerOnDbStartUp() != null
						&& castOther.getStartListenerOnDbStartUp() != null && this
						.getStartListenerOnDbStartUp().equals(
								castOther.getStartListenerOnDbStartUp())))
				&& ((this.getListenerRunMode() == castOther
						.getListenerRunMode()) || (this.getListenerRunMode() != null
						&& castOther.getListenerRunMode() != null && this
						.getListenerRunMode().equals(
								castOther.getListenerRunMode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMailLisenerStatus() == null ? 0 : this
						.getMailLisenerStatus().hashCode());
		result = 37
				* result
				+ (getStartListenerOnDbStartUp() == null ? 0 : this
						.getStartListenerOnDbStartUp().hashCode());
		result = 37
				* result
				+ (getListenerRunMode() == null ? 0 : this.getListenerRunMode()
						.hashCode());
		return result;
	}

}
