package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TblConfig generated by hbm2java
 */
@Entity
@Table(name = "TBL_CONFIG")
public class TblConfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7680669129032760184L;
	private TblConfigId id;

	public TblConfig() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mailLisenerStatus", column = @Column(name = "MAIL_LISENER_STATUS", length = 120)),
			@AttributeOverride(name = "startListenerOnDbStartUp", column = @Column(name = "START_LISTENER_ON_DB_START_UP", length = 3)),
			@AttributeOverride(name = "listenerRunMode", column = @Column(name = "LISTENER_RUN_MODE", length = 60)) })
	public TblConfigId getId() {
		return this.id;
	}

	public void setId(TblConfigId id) {
		this.id = id;
	}

}
