package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TblGestionEnvios generated by hbm2java
 */
@Entity
@Table(name = "TBL_GESTIONENVIOS")
public class TblGestionEnvios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5739935519375696942L;

	@Id
	@Column(name = "MENSAJEID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long mensajeid;

	@Column(name = "APLICACION", length = 100)
	private String aplicacion;

	@Column(name = "CANAL", length = 100)
	private String canal;

	@Column(name = "SERVICIO", length = 100)
	private String servicio;

	@Column(name = "ESTADO", length = 50)
	private String estado;

	@Column(name = "DESTINATARIO", length = 4000)
	private String destinatario;

	@Column(name = "APLICACIONID", precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "CANALID", precision = 22, scale = 0)
	private Long canalid;

	@Column(name = "LOTEENVIOID", precision = 22, scale = 0)
	private Long loteenvioid;

	@Column(name = "NOMBRE", length = 100)
	private String nombre;

	@Column(name = "ULTIMOENVIO", length = 7)
	private Date ultimoenvio;

	@Column(name = "ESTADOID", precision = 22, scale = 0)
	private Long estadoid;

	@Column(name = "SERVIDORID", precision = 22, scale = 0)
	private Long servidorid;

	@Column(name = "CODIGOEXTERNO", length = 100)
	private String codigoexterno;

	@Column(name = "ANIO", precision = 4, scale = 0)
	private Integer anio;

	@Column(name = "MES", precision = 2, scale = 0)
	private Integer mes;

	@Column(name = "DOCUSUARIO", length = 20)
	private String docusuario;

	@Column(name = "CODSIA", length = 20)
	private String codsia;

	@Column(name = "CODORGANISMO", length = 20)
	private String codorganismo;

	@Column(name = "CODORGANISMOPAGADOR", length = 20)
	private String codorganismopagador;

	@Column(name = "NOMBREUSUARIO", length = 50)
	private String nombreusuario;

	@Column(name = "ICONO", length = 100)
	private String icono;

	@Column(name = "SONIDO", length = 100)
	private String sonido;

	@Column(name = "ESTADOLOTE", length = 50)
	private String estadolote;

	@Transient
	private Integer numTotal;
	
	public TblGestionEnvios() {
	}

	/**
	 * @return the mensajeid
	 */
	public Long getMensajeid() {
		return mensajeid;
	}

	/**
	 * @param mensajeid
	 *            the mensajeid to set
	 */
	public void setMensajeid(Long mensajeid) {
		this.mensajeid = mensajeid;
	}

	/**
	 * @return the aplicacion
	 */
	public String getAplicacion() {
		return aplicacion;
	}

	/**
	 * @param aplicacion
	 *            the aplicacion to set
	 */
	public void setAplicacion(String aplicacion) {
		this.aplicacion = aplicacion;
	}

	/**
	 * @return the canal
	 */
	public String getCanal() {
		return canal;
	}

	/**
	 * @param canal
	 *            the canal to set
	 */
	public void setCanal(String canal) {
		this.canal = canal;
	}

	/**
	 * @return the servicio
	 */
	public String getServicio() {
		return servicio;
	}

	/**
	 * @param servicio
	 *            the servicio to set
	 */
	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	/**
	 * @return the estado
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * @param estado
	 *            the estado to set
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * @return the destinatario
	 */
	public String getDestinatario() {
		return destinatario;
	}

	/**
	 * @param destinatario
	 *            the destinatario to set
	 */
	public void setDestinatario(String destinatario) {
		this.destinatario = destinatario;
	}

	/**
	 * @return the aplicacionid
	 */
	public Long getAplicacionid() {
		return aplicacionid;
	}

	/**
	 * @param aplicacionid
	 *            the aplicacionid to set
	 */
	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the canalid
	 */
	public Long getCanalid() {
		return canalid;
	}

	/**
	 * @param canalid
	 *            the canalid to set
	 */
	public void setCanalid(Long canalid) {
		this.canalid = canalid;
	}

	/**
	 * @return the loteenvioid
	 */
	public Long getLoteenvioid() {
		return loteenvioid;
	}

	/**
	 * @param loteenvioid
	 *            the loteenvioid to set
	 */
	public void setLoteenvioid(Long loteenvioid) {
		this.loteenvioid = loteenvioid;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre
	 *            the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the ultimoenvio
	 */
	public Date getUltimoenvio() {
		return ultimoenvio;
	}

	/**
	 * @param ultimoenvio
	 *            the ultimoenvio to set
	 */
	public void setUltimoenvio(Date ultimoenvio) {
		this.ultimoenvio = ultimoenvio;
	}

	/**
	 * @return the estadoid
	 */
	public Long getEstadoid() {
		return estadoid;
	}

	/**
	 * @param estadoid
	 *            the estadoid to set
	 */
	public void setEstadoid(Long estadoid) {
		this.estadoid = estadoid;
	}

	/**
	 * @return the servidorid
	 */
	public Long getServidorid() {
		return servidorid;
	}

	/**
	 * @param servidorid
	 *            the servidorid to set
	 */
	public void setServidorid(Long servidorid) {
		this.servidorid = servidorid;
	}

	/**
	 * @return the codigoexterno
	 */
	public String getCodigoexterno() {
		return codigoexterno;
	}

	/**
	 * @param codigoexterno
	 *            the codigoexterno to set
	 */
	public void setCodigoexterno(String codigoexterno) {
		this.codigoexterno = codigoexterno;
	}

	/**
	 * @return the docusuario
	 */
	public String getDocusuario() {
		return docusuario;
	}

	/**
	 * @param docusuario
	 *            the docusuario to set
	 */
	public void setDocusuario(String docusuario) {
		this.docusuario = docusuario;
	}

	/**
	 * @return the codsia
	 */
	public String getCodsia() {
		return codsia;
	}

	/**
	 * @param codsia
	 *            the codsia to set
	 */
	public void setCodsia(String codsia) {
		this.codsia = codsia;
	}

	/**
	 * @return the codorganismo
	 */
	public String getCodorganismo() {
		return codorganismo;
	}

	/**
	 * @param codorganismo
	 *            the codorganismo to set
	 */
	public void setCodorganismo(String codorganismo) {
		this.codorganismo = codorganismo;
	}

	/**
	 * @return the codorganismopagador
	 */
	public String getCodorganismopagador() {
		return codorganismopagador;
	}

	/**
	 * @param codorganismopagador
	 *            the codorganismopagador to set
	 */
	public void setCodorganismopagador(String codorganismopagador) {
		this.codorganismopagador = codorganismopagador;
	}

	/**
	 * @return the nombreusuario
	 */
	public String getNombreusuario() {
		return nombreusuario;
	}

	/**
	 * @param nombreusuario
	 *            the nombreusuario to set
	 */
	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	/**
	 * @return the icono
	 */
	public String getIcono() {
		return icono;
	}

	/**
	 * @param icono
	 *            the icono to set
	 */
	public void setIcono(String icono) {
		this.icono = icono;
	}

	/**
	 * @return the sonido
	 */
	public String getSonido() {
		return sonido;
	}

	/**
	 * @param sonido
	 *            the sonido to set
	 */
	public void setSonido(String sonido) {
		this.sonido = sonido;
	}

	/**
	 * @return the estadolote
	 */
	public String getEstadolote() {
		return estadolote;
	}

	/**
	 * @param estadolote
	 *            the estadolote to set
	 */
	public void setEstadolote(String estadolote) {
		this.estadolote = estadolote;
	}

	/**
	 * @return the anio
	 */
	public Integer getAnio() {
		return anio;
	}

	/**
	 * @param anio
	 *            the anio to set
	 */
	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	/**
	 * @return the mes
	 */
	public Integer getMes() {
		return mes;
	}

	/**
	 * @param mes
	 *            the mes to set
	 */
	public void setMes(Integer mes) {
		this.mes = mes;
	}

	/**
	 * @return the numTotal
	 */
	public Integer getNumTotal() {
		return numTotal;
	}

	/**
	 * @param numTotal the numTotal to set
	 */
	public void setNumTotal(Integer numTotal) {
		this.numTotal = numTotal;
	}

}
