package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblJobs generated by hbm2java
 */
@Entity
@Table(name = "TBL_JOBS")
public class TblJobs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5068724163521679291L;

	@Id
	@Column(name = "JOBID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long jobid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLANIFICACIONID")
	private TblPlanificaciones tblPlanificaciones;

	@Column(name = "FECHA", nullable = false, length = 7)
	private Date fecha;

	@Column(name = "PARAMETROS", length = 200)
	private String parametros;

	@Column(name = "SALIDA", length = 100)
	private String salida;

	public TblJobs() {
	}

	/**
	 * @return the jobid
	 */
	public Long getJobid() {
		return jobid;
	}

	/**
	 * @param jobid
	 *            the jobid to set
	 */
	public void setJobid(Long jobid) {
		this.jobid = jobid;
	}

	/**
	 * @return the tblPlanificaciones
	 */
	public TblPlanificaciones getTblPlanificaciones() {
		return tblPlanificaciones;
	}

	/**
	 * @param tblPlanificaciones
	 *            the tblPlanificaciones to set
	 */
	public void setTblPlanificaciones(TblPlanificaciones tblPlanificaciones) {
		this.tblPlanificaciones = tblPlanificaciones;
	}

	/**
	 * @return the fecha
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * @param fecha
	 *            the fecha to set
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * @return the parametros
	 */
	public String getParametros() {
		return parametros;
	}

	/**
	 * @param parametros
	 *            the parametros to set
	 */
	public void setParametros(String parametros) {
		this.parametros = parametros;
	}

	/**
	 * @return the salida
	 */
	public String getSalida() {
		return salida;
	}

	/**
	 * @param salida
	 *            the salida to set
	 */
	public void setSalida(String salida) {
		this.salida = salida;
	}

}
