package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblLog generated by hbm2java
 */
@Entity
@Table(name = "TBL_LOG")
public class TblLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5245253794202172151L;

	@Id
	@Column(name = "LOGID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long logid;

	@Column(name = "SOURCENAME", nullable = false, length = 100)
	private String sourcename;

	@Column(name = "SOURCEID", precision = 22, scale = 0)
	private Long sourceid;

	@Column(name = "LOGACCION", precision = 22, scale = 0)
	private Long logaccion;

	@Column(name = "LOGDESCRIPCION", length = 1000)
	private String logdescripcion;

	@Column(name = "ADTUSUARIO", length = 100)
	private String adtusuario;

	@Column(name = "ADTFECHA", length = 7)
	private Date adtfecha;

	@Column(name = "SOURCEDESCRIPTION", length = 100)
	private String sourcedescription;

	public TblLog() {
	}

	/**
	 * @return the logid
	 */
	public Long getLogid() {
		return logid;
	}

	/**
	 * @param logid
	 *            the logid to set
	 */
	public void setLogid(Long logid) {
		this.logid = logid;
	}

	/**
	 * @return the sourcename
	 */
	public String getSourcename() {
		return sourcename;
	}

	/**
	 * @param sourcename
	 *            the sourcename to set
	 */
	public void setSourcename(String sourcename) {
		this.sourcename = sourcename;
	}

	/**
	 * @return the sourceid
	 */
	public Long getSourceid() {
		return sourceid;
	}

	/**
	 * @param sourceid
	 *            the sourceid to set
	 */
	public void setSourceid(Long sourceid) {
		this.sourceid = sourceid;
	}

	/**
	 * @return the logaccion
	 */
	public Long getLogaccion() {
		return logaccion;
	}

	/**
	 * @param logaccion
	 *            the logaccion to set
	 */
	public void setLogaccion(Long logaccion) {
		this.logaccion = logaccion;
	}

	/**
	 * @return the logdescripcion
	 */
	public String getLogdescripcion() {
		return logdescripcion;
	}

	/**
	 * @param logdescripcion
	 *            the logdescripcion to set
	 */
	public void setLogdescripcion(String logdescripcion) {
		this.logdescripcion = logdescripcion;
	}

	/**
	 * @return the adtusuario
	 */
	public String getAdtusuario() {
		return adtusuario;
	}

	/**
	 * @param adtusuario
	 *            the adtusuario to set
	 */
	public void setAdtusuario(String adtusuario) {
		this.adtusuario = adtusuario;
	}

	/**
	 * @return the adtfecha
	 */
	public Date getAdtfecha() {
		return adtfecha;
	}

	/**
	 * @param adtfecha
	 *            the adtfecha to set
	 */
	public void setAdtfecha(Date adtfecha) {
		this.adtfecha = adtfecha;
	}

	/**
	 * @return the sourcedescription
	 */
	public String getSourcedescription() {
		return sourcedescription;
	}

	/**
	 * @param sourcedescription
	 *            the sourcedescription to set
	 */
	public void setSourcedescription(String sourcedescription) {
		this.sourcedescription = sourcedescription;
	}

}
