package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblLotesEnviosHist generated by hbm2java
 */
@Entity
@Table(name = "TBL_LOTESENVIOS_HIST")
public class TblLotesEnviosHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3585887715944975918L;

	@Id
	@Column(name = "LOTEENVIOID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long loteenvioid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVICIOID")
	private TblServicios tblServicios;

	@Column(name = "NOMBRE", length = 100)
	private String nombre;

	@Column(name = "DESCRIPCION", length = 500)
	private String descripcion;

	@Column(name = "ESTADOENVIOID", precision = 22, scale = 0)
	private Long estadoenvioid;

	@Column(name = "FECHACREACION", length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", length = 100)
	private String creadopor;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadopor;

	@Column(name = "FECHAHISTORIFICACION", length = 7)
	private Date fechahistorificacion;

	@Column(name = "MULTIDESTINATARIO", precision = 1, scale = 0)
	private Boolean multidestinatario;

	public TblLotesEnviosHist() {
	}

	/**
	 * @return the loteenvioid
	 */
	public Long getLoteenvioid() {
		return loteenvioid;
	}

	/**
	 * @param loteenvioid
	 *            the loteenvioid to set
	 */
	public void setLoteenvioid(Long loteenvioid) {
		this.loteenvioid = loteenvioid;
	}

	/**
	 * @return the tblServicios
	 */
	public TblServicios getTblServicios() {
		return tblServicios;
	}

	/**
	 * @param tblServicios
	 *            the tblServicios to set
	 */
	public void setTblServicios(TblServicios tblServicios) {
		this.tblServicios = tblServicios;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre
	 *            the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion
	 *            the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the estadoenvioid
	 */
	public Long getEstadoenvioid() {
		return estadoenvioid;
	}

	/**
	 * @param estadoenvioid
	 *            the estadoenvioid to set
	 */
	public void setEstadoenvioid(Long estadoenvioid) {
		this.estadoenvioid = estadoenvioid;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor
	 *            the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	/**
	 * @return the fechamodificacion
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * @param fechamodificacion
	 *            the fechamodificacion to set
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * @return the modificadopor
	 */
	public String getModificadopor() {
		return modificadopor;
	}

	/**
	 * @param modificadopor
	 *            the modificadopor to set
	 */
	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	/**
	 * @return the fechahistorificacion
	 */
	public Date getFechahistorificacion() {
		return fechahistorificacion;
	}

	/**
	 * @param fechahistorificacion
	 *            the fechahistorificacion to set
	 */
	public void setFechahistorificacion(Date fechahistorificacion) {
		this.fechahistorificacion = fechahistorificacion;
	}

	/**
	 * @return the multidestinatario
	 */
	public Boolean getMultidestinatario() {
		return multidestinatario;
	}

	/**
	 * @param multidestinatario
	 *            the multidestinatario to set
	 */
	public void setMultidestinatario(Boolean multidestinatario) {
		this.multidestinatario = multidestinatario;
	}

}
