package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TblMensajesAdjuntos generated by hbm2java
 */
@Entity
@Table(name = "TBL_MENSAJESADJUNTOS")
public class TblMensajesAdjuntos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5171137625340585200L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="MENSAJEADJUNTOID_SEC")
    @SequenceGenerator(name="MENSAJEADJUNTOID_SEC", sequenceName="MENSAJEADJUNTOID_SEC", allocationSize=1)
	@Column(name = "MENSAJEADJUNTOID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long mensajeadjuntoid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENSAJEID")
	private TblMensajes tblMensajes;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADJUNTOID", nullable = false)
	private TblAdjuntos tblAdjuntos;

	public TblMensajesAdjuntos() {
	}

	/**
	 * @return the mensajeadjuntoid
	 */
	public Long getMensajeadjuntoid() {
		return mensajeadjuntoid;
	}

	/**
	 * @param mensajeadjuntoid
	 *            the mensajeadjuntoid to set
	 */
	public void setMensajeadjuntoid(Long mensajeadjuntoid) {
		this.mensajeadjuntoid = mensajeadjuntoid;
	}

	/**
	 * @return the tblMensajes
	 */
	public TblMensajes getTblMensajes() {
		return tblMensajes;
	}

	/**
	 * @param tblMensajes
	 *            the tblMensajes to set
	 */
	public void setTblMensajes(TblMensajes tblMensajes) {
		this.tblMensajes = tblMensajes;
	}

	/**
	 * @return the tblAdjuntos
	 */
	public TblAdjuntos getTblAdjuntos() {
		return tblAdjuntos;
	}

	/**
	 * @param tblAdjuntos
	 *            the tblAdjuntos to set
	 */
	public void setTblAdjuntos(TblAdjuntos tblAdjuntos) {
		this.tblAdjuntos = tblAdjuntos;
	}

}
