package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblMensajesAdjuntosHist generated by hbm2java
 */
@Entity
@Table(name = "TBL_MENSAJESADJUNTOS_HIST")
public class TblMensajesAdjuntosHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8877153226241976270L;

	@Id
	@Column(name = "MENSAJEADJUNTOID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long mensajeadjuntoid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MENSAJEID")
	private TblMensajesHist tblMensajesHist;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADJUNTOID", nullable = false)
	private TblAdjuntosHist tblAdjuntosHist;

	@Column(name = "FECHAHISTORIFICACION", length = 7)
	private Date fechahistorificacion;

	public TblMensajesAdjuntosHist() {
	}

	/**
	 * @return the mensajeadjuntoid
	 */
	public Long getMensajeadjuntoid() {
		return mensajeadjuntoid;
	}

	/**
	 * @param mensajeadjuntoid
	 *            the mensajeadjuntoid to set
	 */
	public void setMensajeadjuntoid(Long mensajeadjuntoid) {
		this.mensajeadjuntoid = mensajeadjuntoid;
	}

	/**
	 * @return the tblMensajesHist
	 */
	public TblMensajesHist getTblMensajesHist() {
		return tblMensajesHist;
	}

	/**
	 * @param tblMensajesHist
	 *            the tblMensajesHist to set
	 */
	public void setTblMensajesHist(TblMensajesHist tblMensajesHist) {
		this.tblMensajesHist = tblMensajesHist;
	}

	/**
	 * @return the tblAdjuntosHist
	 */
	public TblAdjuntosHist getTblAdjuntosHist() {
		return tblAdjuntosHist;
	}

	/**
	 * @param tblAdjuntosHist
	 *            the tblAdjuntosHist to set
	 */
	public void setTblAdjuntosHist(TblAdjuntosHist tblAdjuntosHist) {
		this.tblAdjuntosHist = tblAdjuntosHist;
	}

	/**
	 * @return the fechahistorificacion
	 */
	public Date getFechahistorificacion() {
		return fechahistorificacion;
	}

	/**
	 * @param fechahistorificacion
	 *            the fechahistorificacion to set
	 */
	public void setFechahistorificacion(Date fechahistorificacion) {
		this.fechahistorificacion = fechahistorificacion;
	}

}
