package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblParametrosServidor generated by hbm2java
 */
@Entity
@Table(name = "TBL_PARAMETROSSERVIDOR")
public class TblParametrosServidor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3981758442574656440L;

	@Id
	@Column(name = "PARAMETROSERVIDORID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long parametroservidorid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVIDORID", nullable = false)
	private TblServidores tblServidores;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TIPOPARAMETROID", nullable = false)
	private TblTiposParametros tblTiposParametros;

	@Column(name = "VALOR", nullable = false, length = 200)
	private String valor;

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	private Boolean activo;

	@Column(name = "FECHACREACION", nullable = false, length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", nullable = false, length = 100)
	private String creadopor;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadopor;

	@Column(name = "EXTERNALID", precision = 22, scale = 0)
	private Long externalid;

	public TblParametrosServidor() {
	}

	/**
	 * @return the parametroservidorid
	 */
	public Long getParametroservidorid() {
		return parametroservidorid;
	}

	/**
	 * @param parametroservidorid
	 *            the parametroservidorid to set
	 */
	public void setParametroservidorid(Long parametroservidorid) {
		this.parametroservidorid = parametroservidorid;
	}

	/**
	 * @return the tblServidores
	 */
	public TblServidores getTblServidores() {
		return tblServidores;
	}

	/**
	 * @param tblServidores
	 *            the tblServidores to set
	 */
	public void setTblServidores(TblServidores tblServidores) {
		this.tblServidores = tblServidores;
	}

	/**
	 * @return the tblTiposParametros
	 */
	public TblTiposParametros getTblTiposParametros() {
		return tblTiposParametros;
	}

	/**
	 * @param tblTiposParametros
	 *            the tblTiposParametros to set
	 */
	public void setTblTiposParametros(TblTiposParametros tblTiposParametros) {
		this.tblTiposParametros = tblTiposParametros;
	}

	/**
	 * @return the valor
	 */
	public String getValor() {
		return valor;
	}

	/**
	 * @param valor
	 *            the valor to set
	 */
	public void setValor(String valor) {
		this.valor = valor;
	}

	/**
	 * @return the activo
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * @param activo
	 *            the activo to set
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor
	 *            the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	/**
	 * @return the fechamodificacion
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * @param fechamodificacion
	 *            the fechamodificacion to set
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * @return the modificadopor
	 */
	public String getModificadopor() {
		return modificadopor;
	}

	/**
	 * @param modificadopor
	 *            the modificadopor to set
	 */
	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	/**
	 * @return the externalid
	 */
	public Long getExternalid() {
		return externalid;
	}

	/**
	 * @param externalid
	 *            the externalid to set
	 */
	public void setExternalid(Long externalid) {
		this.externalid = externalid;
	}

}
