package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TblProcesoHist generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROCESO_HIST")
public class TblProcesoHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2872854191045809231L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PROCESOHISTID_SEC")
    @SequenceGenerator(name="PROCESOHISTID_SEC", sequenceName="PROCESOHISTID_SEC", allocationSize=1)
	@Column(name = "PROCESOHISTID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long procesohistid;

	@Column(name = "CODIGOESTADO", length = 5)
	private String codigoestado;

	@Column(name = "DESCRIPCIONESTADO", length = 4000)
	private String descripcionestado;

	@Column(name = "FECHACREACION", length = 7)
	private Date fechacreacion;

	@Column(name = "FECHAINICIO", length = 7)
	private Date fechainicio;

	@Column(name = "FECHAFIN", length = 7)
	private Date fechafin;

	public TblProcesoHist() {
	}

	/**
	 * @return the procesohistid
	 */
	public Long getProcesohistid() {
		return procesohistid;
	}

	/**
	 * @param procesohistid
	 *            the procesohistid to set
	 */
	public void setProcesohistid(Long procesohistid) {
		this.procesohistid = procesohistid;
	}

	/**
	 * @return the codigoestado
	 */
	public String getCodigoestado() {
		return codigoestado;
	}

	/**
	 * @param codigoestado
	 *            the codigoestado to set
	 */
	public void setCodigoestado(String codigoestado) {
		this.codigoestado = codigoestado;
	}

	/**
	 * @return the descripcionestado
	 */
	public String getDescripcionestado() {
		return descripcionestado;
	}

	/**
	 * @param descripcionestado
	 *            the descripcionestado to set
	 */
	public void setDescripcionestado(String descripcionestado) {
		this.descripcionestado = descripcionestado;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the fechainicio
	 */
	public Date getFechainicio() {
		return fechainicio;
	}

	/**
	 * @param fechainicio
	 *            the fechainicio to set
	 */
	public void setFechainicio(Date fechainicio) {
		this.fechainicio = fechainicio;
	}

	/**
	 * @return the fechafin
	 */
	public Date getFechafin() {
		return fechafin;
	}

	/**
	 * @param fechafin
	 *            the fechafin to set
	 */
	public void setFechafin(Date fechafin) {
		this.fechafin = fechafin;
	}

}
