package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TblCanales generated by hbm2java
 */
@Entity
@Table(name = "TBL_PROCESOS")
public class TblProcesos implements java.io.Serializable {

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3769793847325107514L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="PROCESOSID_SEC")
    @SequenceGenerator(name="PROCESOSID_SEC", sequenceName="PROCESOSID_SEC", allocationSize=1)
	@Column(name = "PROCESOSID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long procesosid;
	
	@Column(name = "NOMBRE", length = 100)
	private String nombre;
	
	@Column(name = "NOMBRECLASE", length = 100)
	private String nombreClase;
		
	@Column(name = "INICIOULTIMAEJECUCION", length = 7)
	private Date inicioUltimaEjecucion;
	
	@Column(name = "FINULTIMAEJECUCION", length = 7)
	private Date finUltimaEjecucion;
		
	@Column(name = "ESTADO", length = 100)
	private String estado;
	
	@Column(name = "HORAINICIO", length = 100)
	private String horaInicio;
	
	@Column(name = "PROXIMAEJECUCION", length = 100)
	private String proximaEjecucion;
	
	@Column(name = "TIPO", length = 100)
	private String tipo;
	
	@Column(name = "PARAMETRO1", length = 300)
	private String parametro1;

	@Column(name = "PARAMETRO2", length = 300)
	private String parametro2;
	
	@Column(name = "ACTIVO")
	private Boolean activo;
	
	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechaModificacion;
	
	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadoPor;
	
	@Column(name = "LUNES")
	private Boolean lunes;
	
	@Column(name = "MARTES")
	private Boolean martes;
	
	@Column(name = "MIERCOLES")
	private Boolean miercoles;
	
	@Column(name = "JUEVES")
	private Boolean jueves;
	
	@Column(name = "VIERNES")
	private Boolean viernes;
	
	@Column(name = "SABADO")
	private Boolean sabado;
	
	@Column(name = "DOMINGO")
	private Boolean domingo;

	

	public TblProcesos() {
	}

	public Long getProcesosid() {
		return procesosid;
	}

	public void setProcesosid(Long procesosid) {
		this.procesosid = procesosid;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getInicioUltimaEjecucion() {
		return inicioUltimaEjecucion;
	}

	public void setInicioUltimaEjecucion(Date inicioUltimaEjecucion) {
		this.inicioUltimaEjecucion = inicioUltimaEjecucion;
	}

	public Date getFinUltimaEjecucion() {
		return finUltimaEjecucion;
	}

	public void setFinUltimaEjecucion(Date finUltimaEjecucion) {
		this.finUltimaEjecucion = finUltimaEjecucion;
	}

	public String getEstado() {
		return estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getProximaEjecucion() {
		return proximaEjecucion;
	}

	public void setProximaEjecucion(String proximaEjecucion) {
		this.proximaEjecucion = proximaEjecucion;
	}

	public String getParametro1() {
		return parametro1;
	}

	public void setParametro1(String parametro1) {
		this.parametro1 = parametro1;
	}
	
	
	public String getParametro2() {
		return parametro2;
	}

	public void setParametro2(String parametro2) {
		this.parametro2 = parametro2;
	}

	public Boolean getActivo() {
		return activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	public String getNombreClase() {
		return nombreClase;
	}

	public void setNombreClase(String nombreClase) {
		this.nombreClase = nombreClase;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getModificadoPor() {
		return modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}
	
	public String getTipo() {
		return tipo;
	}

	public String getHoraInicio() {
		return horaInicio;
	}

	public void setHoraInicio(String horaInicio) {
		this.horaInicio = horaInicio;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Boolean getLunes() {
		return lunes;
	}

	public void setLunes(Boolean lunes) {
		this.lunes = lunes;
	}

	public Boolean getMartes() {
		return martes;
	}

	public void setMartes(Boolean martes) {
		this.martes = martes;
	}

	public Boolean getMiercoles() {
		return miercoles;
	}

	public void setMiercoles(Boolean miercoles) {
		this.miercoles = miercoles;
	}

	public Boolean getJueves() {
		return jueves;
	}

	public void setJueves(Boolean jueves) {
		this.jueves = jueves;
	}

	public Boolean getViernes() {
		return viernes;
	}

	public void setViernes(Boolean viernes) {
		this.viernes = viernes;
	}

	public Boolean getSabado() {
		return sabado;
	}

	public void setSabado(Boolean sabado) {
		this.sabado = sabado;
	}

	public Boolean getDomingo() {
		return domingo;
	}

	public void setDomingo(Boolean domingo) {
		this.domingo = domingo;
	}

}
