package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblSubestados generated by hbm2java
 */
@Entity
@Table(name = "TBL_SUBESTADOS")
public class TblSubestados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8171533541559710208L;

	@Id
	@Column(name = "SUBESTADOID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long subestadoid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESTADOID", nullable = false)
	private TblEstados tblEstados;

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	private String descripcion;

	public TblSubestados() {
	}

	/**
	 * @return the subestadoid
	 */
	public Long getSubestadoid() {
		return subestadoid;
	}

	/**
	 * @param subestadoid
	 *            the subestadoid to set
	 */
	public void setSubestadoid(Long subestadoid) {
		this.subestadoid = subestadoid;
	}

	/**
	 * @return the tblEstados
	 */
	public TblEstados getTblEstados() {
		return tblEstados;
	}

	/**
	 * @param tblEstados
	 *            the tblEstados to set
	 */
	public void setTblEstados(TblEstados tblEstados) {
		this.tblEstados = tblEstados;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion
	 *            the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
