package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblSubestadoMensaje generated by hbm2java
 */
@Entity
@Table(name = "TBL_SUBESTADO_MENSAJE")
public class TblSubestadoMensaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1177833493956097488L;

	@Id
	@Column(name = "SUBESTADOMENSAJEID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long subestadomensajeid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBESTADOID", nullable = false)
	private TblSubestados tblSubestados;

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	private String descripcion;

	@Column(name = "CODIGO", length = 100)
	private String codigo;

	public TblSubestadoMensaje() {
	}

	/**
	 * @return the subestadomensajeid
	 */
	public Long getSubestadomensajeid() {
		return subestadomensajeid;
	}

	/**
	 * @param subestadomensajeid
	 *            the subestadomensajeid to set
	 */
	public void setSubestadomensajeid(Long subestadomensajeid) {
		this.subestadomensajeid = subestadomensajeid;
	}

	/**
	 * @return the tblSubestados
	 */
	public TblSubestados getTblSubestados() {
		return tblSubestados;
	}

	/**
	 * @param tblSubestados
	 *            the tblSubestados to set
	 */
	public void setTblSubestados(TblSubestados tblSubestados) {
		this.tblSubestados = tblSubestados;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion
	 *            the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the codigo
	 */
	public String getCodigo() {
		return codigo;
	}

	/**
	 * @param codigo
	 *            the codigo to set
	 */
	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
