package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblServidoresOrganismos generated by hbm2java
 */
@Entity
@Table(name = "TBL_SERVIDORES_ORGANISMOS")
public class TblServidoresOrganismos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -176536502820441192L;

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servidororganismoid", column = @Column(name = "SERVIDORORGANISMOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "organismoid", column = @Column(name = "ORGANISMOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "numintentos", column = @Column(name = "NUMINTENTOS", precision = 22, scale = 0)),
			@AttributeOverride(name = "headersms", column = @Column(name = "HEADERSMS", length = 50)),
			@AttributeOverride(name = "proveedorusuariosms", column = @Column(name = "PROVEEDORUSUARIOSMS", length = 20)),
			@AttributeOverride(name = "proveedorpasswordsms", column = @Column(name = "PROVEEDORPASSWORDSMS", length = 20)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)) })
	private TblServidoresOrganismosId id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SERVIDORID", nullable = false, insertable = false, updatable = false)
	private TblServidores tblServidores;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORGANISMOID", nullable = false, insertable = false, updatable = false)
	private TblOrganismos tblOrganismos;

	public TblServidoresOrganismos() {
	}

	/**
	 * @return the id
	 */
	public TblServidoresOrganismosId getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(TblServidoresOrganismosId id) {
		this.id = id;
	}

	/**
	 * @return the tblServidores
	 */
	public TblServidores getTblServidores() {
		return tblServidores;
	}

	/**
	 * @param tblServidores
	 *            the tblServidores to set
	 */
	public void setTblServidores(TblServidores tblServidores) {
		this.tblServidores = tblServidores;
	}

	/**
	 * @return the tblOrganismos
	 */
	public TblOrganismos getTblOrganismos() {
		return tblOrganismos;
	}

	/**
	 * @param tblOrganismos
	 *            the tblOrganismos to set
	 */
	public void setTblOrganismos(TblOrganismos tblOrganismos) {
		this.tblOrganismos = tblOrganismos;
	}

}
