package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TblUsuariosAplicaciones generated by hbm2java
 */
@Entity
@Table(name = "TBL_USUARIOS_APLICACIONES")
public class TblUsuariosAplicaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2860879849462327826L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="USUARIOAPLICACIONID_SEC")
    @SequenceGenerator(name="USUARIOAPLICACIONID_SEC", sequenceName="USUARIOAPLICACIONID_SEC", allocationSize=1)
	@Column(name = "USUARIOAPLICACIONID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long usuarioaplicacionid;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIOID")
	private TblUsuarios tblUsuarios;

	@Column(name = "APLICACIONID", precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "MODO", precision = 1, scale = 0)
	private Integer modo;

	@Column(name = "FECHACREACION", length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", length = 100)
	private String creadopor;

	public TblUsuariosAplicaciones() {
	}

	/**
	 * @return the usuarioaplicacionid
	 */
	public Long getUsuarioaplicacionid() {
		return usuarioaplicacionid;
	}

	/**
	 * @param usuarioaplicacionid
	 *            the usuarioaplicacionid to set
	 */
	public void setUsuarioaplicacionid(Long usuarioaplicacionid) {
		this.usuarioaplicacionid = usuarioaplicacionid;
	}

	/**
	 * @return the tblUsuarios
	 */
	public TblUsuarios getTblUsuarios() {
		return tblUsuarios;
	}

	/**
	 * @param tblUsuarios
	 *            the tblUsuarios to set
	 */
	public void setTblUsuarios(TblUsuarios tblUsuarios) {
		this.tblUsuarios = tblUsuarios;
	}

	/**
	 * @return the aplicacionid
	 */
	public Long getAplicacionid() {
		return aplicacionid;
	}

	/**
	 * @param aplicacionid
	 *            the aplicacionid to set
	 */
	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	/**
	 * @return the modo
	 */
	public Integer getModo() {
		return modo;
	}

	/**
	 * @param modo
	 *            the modo to set
	 */
	public void setModo(Integer modo) {
		this.modo = modo;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor
	 *            the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

}
