package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewGestionEnviosDestHist generated by hbm2java
 */
@Entity
@Table(name = "VIEW_GESTIONENVIOS_DEST_HIST")
public class ViewGestionEnviosDestHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3417373248622533697L;
	private ViewGestionEnviosDestHistId id;

	public ViewGestionEnviosDestHist() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "aplicacion", column = @Column(name = "APLICACION", length = 100)),
			@AttributeOverride(name = "canal", column = @Column(name = "CANAL", length = 100)),
			@AttributeOverride(name = "servicio", column = @Column(name = "SERVICIO", length = 100)),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO", length = 100)),
			@AttributeOverride(name = "destinatario", column = @Column(name = "DESTINATARIO", length = 200)),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)),
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "loteenvio", column = @Column(name = "LOTEENVIO", length = 100)),
			@AttributeOverride(name = "mensajeid", column = @Column(name = "MENSAJEID", precision = 22, scale = 0)),
			@AttributeOverride(name = "ultimoenvio", column = @Column(name = "ULTIMOENVIO", length = 7)),
			@AttributeOverride(name = "estadoid", column = @Column(name = "ESTADOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "codigoexterno", column = @Column(name = "CODIGOEXTERNO", length = 100)),
			@AttributeOverride(name = "envioid", column = @Column(name = "ENVIOID", length = 42)),
			@AttributeOverride(name = "uim", column = @Column(name = "UIM", length = 50)),
			@AttributeOverride(name = "docusuario", column = @Column(name = "DOCUSUARIO", length = 20)),
			@AttributeOverride(name = "codsia", column = @Column(name = "CODSIA", length = 20)),
			@AttributeOverride(name = "codorganismo", column = @Column(name = "CODORGANISMO", length = 20)),
			@AttributeOverride(name = "codorganismopagador", column = @Column(name = "CODORGANISMOPAGADOR", length = 20)),
			@AttributeOverride(name = "icono", column = @Column(name = "ICONO", length = 100)),
			@AttributeOverride(name = "sonido", column = @Column(name = "SONIDO", length = 100)),
			@AttributeOverride(name = "destinatariosmensajes", column = @Column(name = "DESTINATARIOSMENSAJES", precision = 22, scale = 0)) })
	public ViewGestionEnviosDestHistId getId() {
		return this.id;
	}

	public void setId(ViewGestionEnviosDestHistId id) {
		this.id = id;
	}

}
