package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewMensajesAdjuntos generated by hbm2java
 */
@Entity
@Table(name = "VIEW_MENSAJESADJUNTOS")
public class ViewMensajesAdjuntos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6743551094711786433L;
	private ViewMensajesAdjuntosId id;

	public ViewMensajesAdjuntos() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mensajeadjuntoid", column = @Column(name = "MENSAJEADJUNTOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "mensajeid", column = @Column(name = "MENSAJEID", precision = 22, scale = 0)),
			@AttributeOverride(name = "adjuntoid", column = @Column(name = "ADJUNTOID", nullable = false, precision = 22, scale = 0)) })
	public ViewMensajesAdjuntosId getId() {
		return this.id;
	}

	public void setId(ViewMensajesAdjuntosId id) {
		this.id = id;
	}

}
