package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewDestinatarios generated by hbm2java
 */
@Entity
@Table(name = "VIEW_DESTINATARIOS")
public class ViewDestinatarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4672218737390637863L;
	private ViewDestinatariosId id;

	public ViewDestinatarios() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "destinatarioid", column = @Column(name = "DESTINATARIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 150)),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", nullable = false, length = 150)),
			@AttributeOverride(name = "emailid", column = @Column(name = "EMAILID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", nullable = false, length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", nullable = false, length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "tipodestinatario", column = @Column(name = "TIPODESTINATARIO", nullable = false, length = 3)) })
	public ViewDestinatariosId getId() {
		return this.id;
	}

	public void setId(ViewDestinatariosId id) {
		this.id = id;
	}

}
