package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewGestionEnviosDestId generated by hbm2java
 */
@Embeddable
public class ViewGestionEnviosDestId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3983944593051854853L;

	@Column(name = "APLICACION", length = 100)
	private String aplicacion;

	@Column(name = "CANAL", length = 100)
	private String canal;

	@Column(name = "SERVICIO", length = 100)
	private String servicio;

	@Column(name = "ESTADO", length = 100)
	private String estado;

	@Column(name = "DESTINATARIO", length = 200)
	private String destinatario;

	@Column(name = "APLICACIONID", precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "CANALID", precision = 22, scale = 0)
	private Long canalid;

	@Column(name = "LOTEENVIOID", precision = 22, scale = 0)
	private Long loteenvioid;

	@Column(name = "LOTEENVIO", length = 100)
	private String loteenvio;

	@Column(name = "MENSAJEID", precision = 22, scale = 0)
	private Long mensajeid;

	@Column(name = "ULTIMOENVIO", length = 7)
	private Date ultimoenvio;

	@Column(name = "ESTADOID", precision = 22, scale = 0)
	private Long estadoid;

	@Column(name = "SERVIDORID", precision = 22, scale = 0)
	private Long servidorid;

	@Column(name = "CODIGOEXTERNO", length = 100)
	private String codigoexterno;

	@Column(name = "ENVIOID", length = 42)
	private String envioid;

	@Column(name = "UIM", length = 50)
	private String uim;

	@Column(name = "DOCUSUARIO", length = 20)
	private String docusuario;

	@Column(name = "CODSIA", length = 20)
	private String codsia;

	@Column(name = "CODORGANISMO", length = 20)
	private String codorganismo;

	@Column(name = "CODORGANISMOPAGADOR", length = 20)
	private String codorganismopagador;

	@Column(name = "ICONO", length = 100)
	private String icono;

	@Column(name = "SONIDO", length = 100)
	private String sonido;

	@Column(name = "DESTINATARIOSMENSAJES", precision = 22, scale = 0)
	private Long destinatariosmensajes;

	public ViewGestionEnviosDestId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewGestionEnviosDestId))
			return false;
		ViewGestionEnviosDestId castOther = (ViewGestionEnviosDestId) other;

		return ((this.getAplicacion() == castOther.getAplicacion()) || (this
				.getAplicacion() != null && castOther.getAplicacion() != null && this
				.getAplicacion().equals(castOther.getAplicacion())))
				&& ((this.getCanal() == castOther.getCanal()) || (this
						.getCanal() != null && castOther.getCanal() != null && this
						.getCanal().equals(castOther.getCanal())))
				&& ((this.getServicio() == castOther.getServicio()) || (this
						.getServicio() != null
						&& castOther.getServicio() != null && this
						.getServicio().equals(castOther.getServicio())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getDestinatario() == castOther.getDestinatario()) || (this
						.getDestinatario() != null
						&& castOther.getDestinatario() != null && this
						.getDestinatario().equals(castOther.getDestinatario())))
				&& ((this.getAplicacionid() == castOther.getAplicacionid()) || (this
						.getAplicacionid() != null
						&& castOther.getAplicacionid() != null && this
						.getAplicacionid().equals(castOther.getAplicacionid())))
				&& ((this.getServicioid() == castOther.getServicioid()) || (this
						.getServicioid() != null
						&& castOther.getServicioid() != null && this
						.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getCanalid() == castOther.getCanalid()) || (this
						.getCanalid() != null && castOther.getCanalid() != null && this
						.getCanalid().equals(castOther.getCanalid())))
				&& ((this.getLoteenvioid() == castOther.getLoteenvioid()) || (this
						.getLoteenvioid() != null
						&& castOther.getLoteenvioid() != null && this
						.getLoteenvioid().equals(castOther.getLoteenvioid())))
				&& ((this.getLoteenvio() == castOther.getLoteenvio()) || (this
						.getLoteenvio() != null
						&& castOther.getLoteenvio() != null && this
						.getLoteenvio().equals(castOther.getLoteenvio())))
				&& ((this.getMensajeid() == castOther.getMensajeid()) || (this
						.getMensajeid() != null
						&& castOther.getMensajeid() != null && this
						.getMensajeid().equals(castOther.getMensajeid())))
				&& ((this.getUltimoenvio() == castOther.getUltimoenvio()) || (this
						.getUltimoenvio() != null
						&& castOther.getUltimoenvio() != null && this
						.getUltimoenvio().equals(castOther.getUltimoenvio())))
				&& ((this.getEstadoid() == castOther.getEstadoid()) || (this
						.getEstadoid() != null
						&& castOther.getEstadoid() != null && this
						.getEstadoid().equals(castOther.getEstadoid())))
				&& ((this.getServidorid() == castOther.getServidorid()) || (this
						.getServidorid() != null
						&& castOther.getServidorid() != null && this
						.getServidorid().equals(castOther.getServidorid())))
				&& ((this.getCodigoexterno() == castOther.getCodigoexterno()) || (this
						.getCodigoexterno() != null
						&& castOther.getCodigoexterno() != null && this
						.getCodigoexterno()
						.equals(castOther.getCodigoexterno())))
				&& ((this.getEnvioid() == castOther.getEnvioid()) || (this
						.getEnvioid() != null && castOther.getEnvioid() != null && this
						.getEnvioid().equals(castOther.getEnvioid())))
				&& ((this.getUim() == castOther.getUim()) || (this.getUim() != null
						&& castOther.getUim() != null && this.getUim().equals(
						castOther.getUim())))
				&& ((this.getDocusuario() == castOther.getDocusuario()) || (this
						.getDocusuario() != null
						&& castOther.getDocusuario() != null && this
						.getDocusuario().equals(castOther.getDocusuario())))
				&& ((this.getCodsia() == castOther.getCodsia()) || (this
						.getCodsia() != null && castOther.getCodsia() != null && this
						.getCodsia().equals(castOther.getCodsia())))
				&& ((this.getCodorganismo() == castOther.getCodorganismo()) || (this
						.getCodorganismo() != null
						&& castOther.getCodorganismo() != null && this
						.getCodorganismo().equals(castOther.getCodorganismo())))
				&& ((this.getCodorganismopagador() == castOther
						.getCodorganismopagador()) || (this
						.getCodorganismopagador() != null
						&& castOther.getCodorganismopagador() != null && this
						.getCodorganismopagador().equals(
								castOther.getCodorganismopagador())))
				&& ((this.getIcono() == castOther.getIcono()) || (this
						.getIcono() != null && castOther.getIcono() != null && this
						.getIcono().equals(castOther.getIcono())))
				&& ((this.getSonido() == castOther.getSonido()) || (this
						.getSonido() != null && castOther.getSonido() != null && this
						.getSonido().equals(castOther.getSonido())))
				&& ((this.getDestinatariosmensajes() == castOther
						.getDestinatariosmensajes()) || (this
						.getDestinatariosmensajes() != null
						&& castOther.getDestinatariosmensajes() != null && this
						.getDestinatariosmensajes().equals(
								castOther.getDestinatariosmensajes())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAplicacion() == null ? 0 : this.getAplicacion()
						.hashCode());
		result = 37 * result
				+ (getCanal() == null ? 0 : this.getCanal().hashCode());
		result = 37 * result
				+ (getServicio() == null ? 0 : this.getServicio().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37
				* result
				+ (getDestinatario() == null ? 0 : this.getDestinatario()
						.hashCode());
		result = 37
				* result
				+ (getAplicacionid() == null ? 0 : this.getAplicacionid()
						.hashCode());
		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37 * result
				+ (getCanalid() == null ? 0 : this.getCanalid().hashCode());
		result = 37
				* result
				+ (getLoteenvioid() == null ? 0 : this.getLoteenvioid()
						.hashCode());
		result = 37 * result
				+ (getLoteenvio() == null ? 0 : this.getLoteenvio().hashCode());
		result = 37 * result
				+ (getMensajeid() == null ? 0 : this.getMensajeid().hashCode());
		result = 37
				* result
				+ (getUltimoenvio() == null ? 0 : this.getUltimoenvio()
						.hashCode());
		result = 37 * result
				+ (getEstadoid() == null ? 0 : this.getEstadoid().hashCode());
		result = 37
				* result
				+ (getServidorid() == null ? 0 : this.getServidorid()
						.hashCode());
		result = 37
				* result
				+ (getCodigoexterno() == null ? 0 : this.getCodigoexterno()
						.hashCode());
		result = 37 * result
				+ (getEnvioid() == null ? 0 : this.getEnvioid().hashCode());
		result = 37 * result
				+ (getUim() == null ? 0 : this.getUim().hashCode());
		result = 37
				* result
				+ (getDocusuario() == null ? 0 : this.getDocusuario()
						.hashCode());
		result = 37 * result
				+ (getCodsia() == null ? 0 : this.getCodsia().hashCode());
		result = 37
				* result
				+ (getCodorganismo() == null ? 0 : this.getCodorganismo()
						.hashCode());
		result = 37
				* result
				+ (getCodorganismopagador() == null ? 0 : this
						.getCodorganismopagador().hashCode());
		result = 37 * result
				+ (getIcono() == null ? 0 : this.getIcono().hashCode());
		result = 37 * result
				+ (getSonido() == null ? 0 : this.getSonido().hashCode());
		result = 37
				* result
				+ (getDestinatariosmensajes() == null ? 0 : this
						.getDestinatariosmensajes().hashCode());
		return result;
	}

	/**
	 * @return the aplicacion
	 */
	public String getAplicacion() {
		return aplicacion;
	}

	/**
	 * @param aplicacion
	 *            the aplicacion to set
	 */
	public void setAplicacion(String aplicacion) {
		this.aplicacion = aplicacion;
	}

	/**
	 * @return the canal
	 */
	public String getCanal() {
		return canal;
	}

	/**
	 * @param canal
	 *            the canal to set
	 */
	public void setCanal(String canal) {
		this.canal = canal;
	}

	/**
	 * @return the servicio
	 */
	public String getServicio() {
		return servicio;
	}

	/**
	 * @param servicio
	 *            the servicio to set
	 */
	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	/**
	 * @return the estado
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * @param estado
	 *            the estado to set
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * @return the destinatario
	 */
	public String getDestinatario() {
		return destinatario;
	}

	/**
	 * @param destinatario
	 *            the destinatario to set
	 */
	public void setDestinatario(String destinatario) {
		this.destinatario = destinatario;
	}

	/**
	 * @return the aplicacionid
	 */
	public Long getAplicacionid() {
		return aplicacionid;
	}

	/**
	 * @param aplicacionid
	 *            the aplicacionid to set
	 */
	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the canalid
	 */
	public Long getCanalid() {
		return canalid;
	}

	/**
	 * @param canalid
	 *            the canalid to set
	 */
	public void setCanalid(Long canalid) {
		this.canalid = canalid;
	}

	/**
	 * @return the loteenvioid
	 */
	public Long getLoteenvioid() {
		return loteenvioid;
	}

	/**
	 * @param loteenvioid
	 *            the loteenvioid to set
	 */
	public void setLoteenvioid(Long loteenvioid) {
		this.loteenvioid = loteenvioid;
	}

	/**
	 * @return the loteenvio
	 */
	public String getLoteenvio() {
		return loteenvio;
	}

	/**
	 * @param loteenvio
	 *            the loteenvio to set
	 */
	public void setLoteenvio(String loteenvio) {
		this.loteenvio = loteenvio;
	}

	/**
	 * @return the mensajeid
	 */
	public Long getMensajeid() {
		return mensajeid;
	}

	/**
	 * @param mensajeid
	 *            the mensajeid to set
	 */
	public void setMensajeid(Long mensajeid) {
		this.mensajeid = mensajeid;
	}

	/**
	 * @return the ultimoenvio
	 */
	public Date getUltimoenvio() {
		return ultimoenvio;
	}

	/**
	 * @param ultimoenvio
	 *            the ultimoenvio to set
	 */
	public void setUltimoenvio(Date ultimoenvio) {
		this.ultimoenvio = ultimoenvio;
	}

	/**
	 * @return the estadoid
	 */
	public Long getEstadoid() {
		return estadoid;
	}

	/**
	 * @param estadoid
	 *            the estadoid to set
	 */
	public void setEstadoid(Long estadoid) {
		this.estadoid = estadoid;
	}

	/**
	 * @return the servidorid
	 */
	public Long getServidorid() {
		return servidorid;
	}

	/**
	 * @param servidorid
	 *            the servidorid to set
	 */
	public void setServidorid(Long servidorid) {
		this.servidorid = servidorid;
	}

	/**
	 * @return the codigoexterno
	 */
	public String getCodigoexterno() {
		return codigoexterno;
	}

	/**
	 * @param codigoexterno
	 *            the codigoexterno to set
	 */
	public void setCodigoexterno(String codigoexterno) {
		this.codigoexterno = codigoexterno;
	}

	/**
	 * @return the envioid
	 */
	public String getEnvioid() {
		return envioid;
	}

	/**
	 * @param envioid
	 *            the envioid to set
	 */
	public void setEnvioid(String envioid) {
		this.envioid = envioid;
	}

	/**
	 * @return the uim
	 */
	public String getUim() {
		return uim;
	}

	/**
	 * @param uim
	 *            the uim to set
	 */
	public void setUim(String uim) {
		this.uim = uim;
	}

	/**
	 * @return the docusuario
	 */
	public String getDocusuario() {
		return docusuario;
	}

	/**
	 * @param docusuario
	 *            the docusuario to set
	 */
	public void setDocusuario(String docusuario) {
		this.docusuario = docusuario;
	}

	/**
	 * @return the codsia
	 */
	public String getCodsia() {
		return codsia;
	}

	/**
	 * @param codsia
	 *            the codsia to set
	 */
	public void setCodsia(String codsia) {
		this.codsia = codsia;
	}

	/**
	 * @return the codorganismo
	 */
	public String getCodorganismo() {
		return codorganismo;
	}

	/**
	 * @param codorganismo
	 *            the codorganismo to set
	 */
	public void setCodorganismo(String codorganismo) {
		this.codorganismo = codorganismo;
	}

	/**
	 * @return the codorganismopagador
	 */
	public String getCodorganismopagador() {
		return codorganismopagador;
	}

	/**
	 * @param codorganismopagador
	 *            the codorganismopagador to set
	 */
	public void setCodorganismopagador(String codorganismopagador) {
		this.codorganismopagador = codorganismopagador;
	}

	/**
	 * @return the icono
	 */
	public String getIcono() {
		return icono;
	}

	/**
	 * @param icono
	 *            the icono to set
	 */
	public void setIcono(String icono) {
		this.icono = icono;
	}

	/**
	 * @return the sonido
	 */
	public String getSonido() {
		return sonido;
	}

	/**
	 * @param sonido
	 *            the sonido to set
	 */
	public void setSonido(String sonido) {
		this.sonido = sonido;
	}

	/**
	 * @return the destinatariosmensajes
	 */
	public Long getDestinatariosmensajes() {
		return destinatariosmensajes;
	}

	/**
	 * @param destinatariosmensajes
	 *            the destinatariosmensajes to set
	 */
	public void setDestinatariosmensajes(Long destinatariosmensajes) {
		this.destinatariosmensajes = destinatariosmensajes;
	}

}
