package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewSMS generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SMS")
public class ViewSMS implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4299313443363809360L;
	private ViewSMSId id;

	public ViewSMS() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idenviossms", column = @Column(name = "IDENVIOSSMS", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "idservicio", column = @Column(name = "IDSERVICIO", precision = 6, scale = 0)),
			@AttributeOverride(name = "telefono", column = @Column(name = "TELEFONO", length = 50)),
			@AttributeOverride(name = "textosms", column = @Column(name = "TEXTOSMS", length = 2500)),
			@AttributeOverride(name = "adtusuario", column = @Column(name = "ADTUSUARIO")),
			@AttributeOverride(name = "adtfecha", column = @Column(name = "ADTFECHA", length = 7)),
			@AttributeOverride(name = "eliminado", column = @Column(name = "ELIMINADO", length = 1)),
			@AttributeOverride(name = "enviado", column = @Column(name = "ENVIADO", length = 1)),
			@AttributeOverride(name = "idconvocatoria", column = @Column(name = "IDCONVOCATORIA", precision = 6, scale = 0)),
			@AttributeOverride(name = "idusuario", column = @Column(name = "IDUSUARIO", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "nenvios", column = @Column(name = "NENVIOS", precision = 4, scale = 0)),
			@AttributeOverride(name = "uim", column = @Column(name = "UIM", length = 30)),
			@AttributeOverride(name = "idestado", column = @Column(name = "IDESTADO", precision = 6, scale = 0)),
			@AttributeOverride(name = "anio", column = @Column(name = "ANIO", precision = 4, scale = 0)),
			@AttributeOverride(name = "cuerpo", column = @Column(name = "CUERPO")),
			@AttributeOverride(name = "tipoincidencia", column = @Column(name = "TIPOINCIDENCIA")),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)) })
	public ViewSMSId getId() {
		return this.id;
	}

	public void setId(ViewSMSId id) {
		this.id = id;
	}

}
