package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewAplicaciones generated by hbm2java
 */
@Entity
@Table(name = "VIEW_APLICACIONES")
public class ViewAplicaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2084032647242968872L;
	private ViewAplicacionesId id;

	public ViewAplicaciones() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 500)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 50)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)),
			@AttributeOverride(name = "eliminado", column = @Column(name = "ELIMINADO", length = 1)) })
	public ViewAplicacionesId getId() {
		return this.id;
	}

	public void setId(ViewAplicacionesId id) {
		this.id = id;
	}

}
