package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewProvPrioridadMultiorg generated by hbm2java
 */
@Entity
@Table(name = "VIEW_PROV_PRIORIDAD_MULTIORG")
public class ViewProvPrioridadMultiorg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6062713471431190201L;
	private ViewProvPrioridadMultiorgId id;

	public ViewProvPrioridadMultiorg() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "proveedorid", column = @Column(name = "PROVEEDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "url", column = @Column(name = "URL", length = 500)),
			@AttributeOverride(name = "organismoid", column = @Column(name = "ORGANISMOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "prioridad", column = @Column(name = "PRIORIDAD", precision = 22, scale = 0)) })
	public ViewProvPrioridadMultiorgId getId() {
		return this.id;
	}

	public void setId(ViewProvPrioridadMultiorgId id) {
		this.id = id;
	}

}
