package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewUsuarios generated by hbm2java
 */
@Entity
@Table(name = "VIEW_USUARIOS")
public class ViewUsuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5406414134220600032L;
	
	@Id
	@Column(name = "IDCOMPUESTO", length = 81)
	private String idcompuesto;

	@Column(name = "USUARIOID", nullable = false, precision = 22, scale = 0)
	private Long usuarioid;

	@Column(name = "NOMBRE", nullable = false, length = 100)
	private String nombre;

	@Column(name = "LOGIN", length = 100)
	private String login;

	@Column(name = "EMAIL", length = 100)
	private String email;

	@Column(name = "FECHACREACION", nullable = false, length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", nullable = false, length = 150)
	private String creadopor;

	@Column(name = "ACTIVO", length = 1)
	private Boolean activo;

	@Column(name = "ROLID", precision = 22, scale = 0)
	private Long rolid;

	@Column(name = "MODIFICADOPOR", length = 150)
	private String modificadopor;

	@Column(name = "APLICACIONID", precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "NOMBREAPLICACION", length = 100)
	private String nombreaplicacion;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	public ViewUsuarios() {
	}

	/**
	 * @return the idcompuesto
	 */
	public String getIdcompuesto() {
		return idcompuesto;
	}

	/**
	 * @param idcompuesto the idcompuesto to set
	 */
	public void setIdcompuesto(String idcompuesto) {
		this.idcompuesto = idcompuesto;
	}

	/**
	 * @return the usuarioid
	 */
	public Long getUsuarioid() {
		return usuarioid;
	}

	/**
	 * @param usuarioid the usuarioid to set
	 */
	public void setUsuarioid(Long usuarioid) {
		this.usuarioid = usuarioid;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the login
	 */
	public String getLogin() {
		return login;
	}

	/**
	 * @param login the login to set
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	/**
	 * @return the activo
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * @param activo the activo to set
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	/**
	 * @return the rolid
	 */
	public Long getRolid() {
		return rolid;
	}

	/**
	 * @param rolid the rolid to set
	 */
	public void setRolid(Long rolid) {
		this.rolid = rolid;
	}

	/**
	 * @return the modificadopor
	 */
	public String getModificadopor() {
		return modificadopor;
	}

	/**
	 * @param modificadopor the modificadopor to set
	 */
	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	/**
	 * @return the aplicacionid
	 */
	public Long getAplicacionid() {
		return aplicacionid;
	}

	/**
	 * @param aplicacionid the aplicacionid to set
	 */
	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	/**
	 * @return the nombreaplicacion
	 */
	public String getNombreaplicacion() {
		return nombreaplicacion;
	}

	/**
	 * @param nombreaplicacion the nombreaplicacion to set
	 */
	public void setNombreaplicacion(String nombreaplicacion) {
		this.nombreaplicacion = nombreaplicacion;
	}

	/**
	 * @return the fechamodificacion
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * @param fechamodificacion the fechamodificacion to set
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	

}
