package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewPlanificaciones generated by hbm2java
 */
@Entity
@Table(name = "VIEW_PLANIFICACIONES")
public class ViewPlanificaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5374697024784325584L;
	private ViewPlanificacionesId id;

	public ViewPlanificaciones() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "planificacionid", column = @Column(name = "PLANIFICACIONID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "organismoid", column = @Column(name = "ORGANISMOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "dir3organismo", column = @Column(name = "DIR3ORGANISMO", length = 100)),
			@AttributeOverride(name = "tipoplanificacionid", column = @Column(name = "TIPOPLANIFICACIONID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "l", column = @Column(name = "L", length = 1)),
			@AttributeOverride(name = "m", column = @Column(name = "M", length = 1)),
			@AttributeOverride(name = "x", column = @Column(name = "X", length = 1)),
			@AttributeOverride(name = "j", column = @Column(name = "J", length = 1)),
			@AttributeOverride(name = "v", column = @Column(name = "V", length = 1)),
			@AttributeOverride(name = "s", column = @Column(name = "S", length = 1)),
			@AttributeOverride(name = "d", column = @Column(name = "D", length = 1)),
			@AttributeOverride(name = "horadesde", column = @Column(name = "HORADESDE", length = 5)),
			@AttributeOverride(name = "horahasta", column = @Column(name = "HORAHASTA", length = 5)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "nombreaplicacion", column = @Column(name = "NOMBREAPLICACION", length = 100)),
			@AttributeOverride(name = "nombreservidor", column = @Column(name = "NOMBRESERVIDOR", length = 100)),
			@AttributeOverride(name = "nombreservicio", column = @Column(name = "NOMBRESERVICIO", length = 100)),
			@AttributeOverride(name = "nombretipoplanificacion", column = @Column(name = "NOMBRETIPOPLANIFICACION", length = 100)),
			@AttributeOverride(name = "eliminado", column = @Column(name = "ELIMINADO", length = 1)),
			@AttributeOverride(name = "externalid", column = @Column(name = "EXTERNALID", length = 0)) })
	public ViewPlanificacionesId getId() {
		return this.id;
	}

	public void setId(ViewPlanificacionesId id) {
		this.id = id;
	}

}
