package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewEstadoPorEnvioId generated by hbm2java
 */
@Embeddable
public class ViewEstadoPorEnvioId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2922142136966756291L;

	@Column(name = "LOTEENVIOID", nullable = false, precision = 22, scale = 0)
	private Long loteenvioid;

	@Column(name = "ENVIOID", nullable = false, precision = 22, scale = 0)
	private Long envioid;

	@Column(name = "ESTADOID", precision = 22, scale = 0)
	private Long estadoid;

	public ViewEstadoPorEnvioId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewEstadoPorEnvioId))
			return false;
		ViewEstadoPorEnvioId castOther = (ViewEstadoPorEnvioId) other;

		return ((this.getLoteenvioid() == castOther.getLoteenvioid()) || (this
				.getLoteenvioid() != null && castOther.getLoteenvioid() != null && this
				.getLoteenvioid().equals(castOther.getLoteenvioid())))
				&& ((this.getEnvioid() == castOther.getEnvioid()) || (this
						.getEnvioid() != null && castOther.getEnvioid() != null && this
						.getEnvioid().equals(castOther.getEnvioid())))
				&& ((this.getEstadoid() == castOther.getEstadoid()) || (this
						.getEstadoid() != null
						&& castOther.getEstadoid() != null && this
						.getEstadoid().equals(castOther.getEstadoid())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getLoteenvioid() == null ? 0 : this.getLoteenvioid()
						.hashCode());
		result = 37 * result
				+ (getEnvioid() == null ? 0 : this.getEnvioid().hashCode());
		result = 37 * result
				+ (getEstadoid() == null ? 0 : this.getEstadoid().hashCode());
		return result;
	}

	/**
	 * @return the loteenvioid
	 */
	public Long getLoteenvioid() {
		return loteenvioid;
	}

	/**
	 * @param loteenvioid
	 *            the loteenvioid to set
	 */
	public void setLoteenvioid(Long loteenvioid) {
		this.loteenvioid = loteenvioid;
	}

	/**
	 * @return the envioid
	 */
	public Long getEnvioid() {
		return envioid;
	}

	/**
	 * @param envioid
	 *            the envioid to set
	 */
	public void setEnvioid(Long envioid) {
		this.envioid = envioid;
	}

	/**
	 * @return the estadoid
	 */
	public Long getEstadoid() {
		return estadoid;
	}

	/**
	 * @param estadoid
	 *            the estadoid to set
	 */
	public void setEstadoid(Long estadoid) {
		this.estadoid = estadoid;
	}

}
