package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewEstadoPorEnvioHist generated by hbm2java
 */
@Entity
@Table(name = "VIEW_ESTADOPORENVIO_HIST")
public class ViewEstadoPorEnvioHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6875978199665350765L;
	private ViewEstadoPorEnvioHistId id;

	public ViewEstadoPorEnvioHist() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "envioid", column = @Column(name = "ENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoid", column = @Column(name = "ESTADOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "fechahistorificacion", column = @Column(name = "FECHAHISTORIFICACION", length = 7)) })
	public ViewEstadoPorEnvioHistId getId() {
		return this.id;
	}

	public void setId(ViewEstadoPorEnvioHistId id) {
		this.id = id;
	}

}
