package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewEstadistica generated by hbm2java
 */
@Entity
@Table(name = "VIEW_ESTADISTICA")
public class ViewEstadistica implements java.io.Serializable {

	private ViewEstadisticaId id;

	public ViewEstadistica() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servidornombre", column = @Column(name = "SERVIDORNOMBRE", length = 100)),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "planificacionid", column = @Column(name = "PLANIFICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "aplicacionnombre", column = @Column(name = "APLICACIONNOMBRE", length = 100)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servicionombre", column = @Column(name = "SERVICIONOMBRE", length = 100)),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)),
			@AttributeOverride(name = "canalnombre", column = @Column(name = "CANALNOMBRE", length = 100)),
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "ultimoenvio", column = @Column(name = "ULTIMOENVIO", length = 7)),
			@AttributeOverride(name = "estadoid", column = @Column(name = "ESTADOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "estadonombre", column = @Column(name = "ESTADONOMBRE", length = 50)),
			@AttributeOverride(name = "anno", column = @Column(name = "ANNO", precision = 4, scale = 0)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", length = 81)),
			@AttributeOverride(name = "dia", column = @Column(name = "DIA", length = 122)),
			@AttributeOverride(name = "mensajeid", column = @Column(name = "MENSAJEID", precision = 22, scale = 0)),
			@AttributeOverride(name = "envioid", column = @Column(name = "ENVIOID", length = 42)),
			@AttributeOverride(name = "docusuario", column = @Column(name = "DOCUSUARIO", length = 20)),
			@AttributeOverride(name = "codsia", column = @Column(name = "CODSIA", length = 20)),
			@AttributeOverride(name = "codorganismo", column = @Column(name = "CODORGANISMO", length = 20)),
			@AttributeOverride(name = "codorganismopagador", column = @Column(name = "CODORGANISMOPAGADOR", length = 20)) })
	public ViewEstadisticaId getId() {
		return this.id;
	}

	public void setId(ViewEstadisticaId id) {
		this.id = id;
	}

}
