package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewEstadoEnvios generated by hbm2java
 */
@Entity
@Table(name = "VIEW_ESTADOENVIOS")
public class ViewEstadoEnvios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -707796750021250444L;
	private ViewEstadoEnviosId id;

	public ViewEstadoEnvios() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "estadoenvioid", column = @Column(name = "ESTADOENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 500)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)) })
	public ViewEstadoEnviosId getId() {
		return this.id;
	}

	public void setId(ViewEstadoEnviosId id) {
		this.id = id;
	}

}
