package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewServicioOrganismosId generated by hbm2java
 */
@Embeddable
public class ViewServicioOrganismosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1394364916546309177L;

	@Column(name = "SERVICIOID", nullable = false, precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "ORGANISMOID", nullable = false, precision = 22, scale = 0)
	private Long organismoid;

	@Column(name = "SERVICIOORGANISMOID", nullable = false, precision = 22, scale = 0)
	private Long servicioorganismoid;

	@Column(name = "NOMBRESERVICIO", length = 100)
	private String nombreservicio;

	@Column(name = "NOMBREORGANISMO", nullable = false, length = 100)
	private String nombreorganismo;

	@Column(name = "DIR3ORGANISMO", nullable = false, length = 100)
	private String dir3organismo;

	@Column(name = "DESCRIPCIONORGANISMO", length = 500)
	private String descripcionorganismo;

	@Column(name = "DESCRIPCIONSERVICIO", length = 500)
	private String descripcionservicio;

	@Column(name = "CREADOPOR", length = 100)
	private String creadopor;

	@Column(name = "FECHACREACION", length = 7)
	private Date fechacreacion;

	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadopor;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	public ViewServicioOrganismosId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewServicioOrganismosId))
			return false;
		ViewServicioOrganismosId castOther = (ViewServicioOrganismosId) other;

		return ((this.getServicioid() == castOther.getServicioid()) || (this
				.getServicioid() != null && castOther.getServicioid() != null && this
				.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getOrganismoid() == castOther.getOrganismoid()) || (this
						.getOrganismoid() != null
						&& castOther.getOrganismoid() != null && this
						.getOrganismoid().equals(castOther.getOrganismoid())))
				&& ((this.getServicioorganismoid() == castOther
						.getServicioorganismoid()) || (this
						.getServicioorganismoid() != null
						&& castOther.getServicioorganismoid() != null && this
						.getServicioorganismoid().equals(
								castOther.getServicioorganismoid())))
				&& ((this.getNombreservicio() == castOther.getNombreservicio()) || (this
						.getNombreservicio() != null
						&& castOther.getNombreservicio() != null && this
						.getNombreservicio().equals(
								castOther.getNombreservicio())))
				&& ((this.getNombreorganismo() == castOther
						.getNombreorganismo()) || (this.getNombreorganismo() != null
						&& castOther.getNombreorganismo() != null && this
						.getNombreorganismo().equals(
								castOther.getNombreorganismo())))
				&& ((this.getDir3organismo() == castOther.getDir3organismo()) || (this
						.getDir3organismo() != null
						&& castOther.getDir3organismo() != null && this
						.getDir3organismo()
						.equals(castOther.getDir3organismo())))
				&& ((this.getDescripcionorganismo() == castOther
						.getDescripcionorganismo()) || (this
						.getDescripcionorganismo() != null
						&& castOther.getDescripcionorganismo() != null && this
						.getDescripcionorganismo().equals(
								castOther.getDescripcionorganismo())))
				&& ((this.getDescripcionservicio() == castOther
						.getDescripcionservicio()) || (this
						.getDescripcionservicio() != null
						&& castOther.getDescripcionservicio() != null && this
						.getDescripcionservicio().equals(
								castOther.getDescripcionservicio())))
				&& ((this.getCreadopor() == castOther.getCreadopor()) || (this
						.getCreadopor() != null
						&& castOther.getCreadopor() != null && this
						.getCreadopor().equals(castOther.getCreadopor())))
				&& ((this.getFechacreacion() == castOther.getFechacreacion()) || (this
						.getFechacreacion() != null
						&& castOther.getFechacreacion() != null && this
						.getFechacreacion()
						.equals(castOther.getFechacreacion())))
				&& ((this.getModificadopor() == castOther.getModificadopor()) || (this
						.getModificadopor() != null
						&& castOther.getModificadopor() != null && this
						.getModificadopor()
						.equals(castOther.getModificadopor())))
				&& ((this.getFechamodificacion() == castOther
						.getFechamodificacion()) || (this
						.getFechamodificacion() != null
						&& castOther.getFechamodificacion() != null && this
						.getFechamodificacion().equals(
								castOther.getFechamodificacion())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37
				* result
				+ (getOrganismoid() == null ? 0 : this.getOrganismoid()
						.hashCode());
		result = 37
				* result
				+ (getServicioorganismoid() == null ? 0 : this
						.getServicioorganismoid().hashCode());
		result = 37
				* result
				+ (getNombreservicio() == null ? 0 : this.getNombreservicio()
						.hashCode());
		result = 37
				* result
				+ (getNombreorganismo() == null ? 0 : this.getNombreorganismo()
						.hashCode());
		result = 37
				* result
				+ (getDir3organismo() == null ? 0 : this.getDir3organismo()
						.hashCode());
		result = 37
				* result
				+ (getDescripcionorganismo() == null ? 0 : this
						.getDescripcionorganismo().hashCode());
		result = 37
				* result
				+ (getDescripcionservicio() == null ? 0 : this
						.getDescripcionservicio().hashCode());
		result = 37 * result
				+ (getCreadopor() == null ? 0 : this.getCreadopor().hashCode());
		result = 37
				* result
				+ (getFechacreacion() == null ? 0 : this.getFechacreacion()
						.hashCode());
		result = 37
				* result
				+ (getModificadopor() == null ? 0 : this.getModificadopor()
						.hashCode());
		result = 37
				* result
				+ (getFechamodificacion() == null ? 0 : this
						.getFechamodificacion().hashCode());
		return result;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the organismoid
	 */
	public Long getOrganismoid() {
		return organismoid;
	}

	/**
	 * @param organismoid
	 *            the organismoid to set
	 */
	public void setOrganismoid(Long organismoid) {
		this.organismoid = organismoid;
	}

	/**
	 * @return the servicioorganismoid
	 */
	public Long getServicioorganismoid() {
		return servicioorganismoid;
	}

	/**
	 * @param servicioorganismoid
	 *            the servicioorganismoid to set
	 */
	public void setServicioorganismoid(Long servicioorganismoid) {
		this.servicioorganismoid = servicioorganismoid;
	}

	/**
	 * @return the nombreservicio
	 */
	public String getNombreservicio() {
		return nombreservicio;
	}

	/**
	 * @param nombreservicio
	 *            the nombreservicio to set
	 */
	public void setNombreservicio(String nombreservicio) {
		this.nombreservicio = nombreservicio;
	}

	/**
	 * @return the nombreorganismo
	 */
	public String getNombreorganismo() {
		return nombreorganismo;
	}

	/**
	 * @param nombreorganismo
	 *            the nombreorganismo to set
	 */
	public void setNombreorganismo(String nombreorganismo) {
		this.nombreorganismo = nombreorganismo;
	}

	/**
	 * @return the dir3organismo
	 */
	public String getDir3organismo() {
		return dir3organismo;
	}

	/**
	 * @param dir3organismo
	 *            the dir3organismo to set
	 */
	public void setDir3organismo(String dir3organismo) {
		this.dir3organismo = dir3organismo;
	}

	/**
	 * @return the descripcionorganismo
	 */
	public String getDescripcionorganismo() {
		return descripcionorganismo;
	}

	/**
	 * @param descripcionorganismo
	 *            the descripcionorganismo to set
	 */
	public void setDescripcionorganismo(String descripcionorganismo) {
		this.descripcionorganismo = descripcionorganismo;
	}

	/**
	 * @return the descripcionservicio
	 */
	public String getDescripcionservicio() {
		return descripcionservicio;
	}

	/**
	 * @param descripcionservicio
	 *            the descripcionservicio to set
	 */
	public void setDescripcionservicio(String descripcionservicio) {
		this.descripcionservicio = descripcionservicio;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor
	 *            the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the modificadopor
	 */
	public String getModificadopor() {
		return modificadopor;
	}

	/**
	 * @param modificadopor
	 *            the modificadopor to set
	 */
	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	/**
	 * @return the fechamodificacion
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * @param fechamodificacion
	 *            the fechamodificacion to set
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

}
