package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewRefresgStatusDestId generated by hbm2java
 */
@Embeddable
public class ViewRefresgStatusDestId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3363466422942778245L;

	@Column(name = "MENSAJEID", nullable = false, precision = 22, scale = 0)
	private Long mensajeid;

	@Column(name = "UIM", length = 50)
	private String uim;

	@Column(name = "ULTIMOENVIO", length = 7)
	private Date ultimoenvio;

	@Column(name = "NODO", precision = 22, scale = 0)
	private Integer nodo;

	public ViewRefresgStatusDestId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRefresgStatusDestId))
			return false;
		ViewRefresgStatusDestId castOther = (ViewRefresgStatusDestId) other;

		return ((this.getMensajeid() == castOther.getMensajeid()) || (this
				.getMensajeid() != null && castOther.getMensajeid() != null && this
				.getMensajeid().equals(castOther.getMensajeid())))
				&& ((this.getUim() == castOther.getUim()) || (this.getUim() != null
						&& castOther.getUim() != null && this.getUim().equals(
						castOther.getUim())))
				&& ((this.getUltimoenvio() == castOther.getUltimoenvio()) || (this
						.getUltimoenvio() != null
						&& castOther.getUltimoenvio() != null && this
						.getUltimoenvio().equals(castOther.getUltimoenvio())))
				&& ((this.getNodo() == castOther.getNodo()) || (this.getNodo() != null
						&& castOther.getNodo() != null && this.getNodo()
						.equals(castOther.getNodo())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMensajeid() == null ? 0 : this.getMensajeid().hashCode());
		result = 37 * result
				+ (getUim() == null ? 0 : this.getUim().hashCode());
		result = 37
				* result
				+ (getUltimoenvio() == null ? 0 : this.getUltimoenvio()
						.hashCode());
		result = 37 * result
				+ (getNodo() == null ? 0 : this.getNodo().hashCode());
		return result;
	}

	/**
	 * @return the mensajeid
	 */
	public Long getMensajeid() {
		return mensajeid;
	}

	/**
	 * @param mensajeid
	 *            the mensajeid to set
	 */
	public void setMensajeid(Long mensajeid) {
		this.mensajeid = mensajeid;
	}

	/**
	 * @return the uim
	 */
	public String getUim() {
		return uim;
	}

	/**
	 * @param uim
	 *            the uim to set
	 */
	public void setUim(String uim) {
		this.uim = uim;
	}

	/**
	 * @return the ultimoenvio
	 */
	public Date getUltimoenvio() {
		return ultimoenvio;
	}

	/**
	 * @param ultimoenvio
	 *            the ultimoenvio to set
	 */
	public void setUltimoenvio(Date ultimoenvio) {
		this.ultimoenvio = ultimoenvio;
	}

	/**
	 * @return the nodo
	 */
	public Integer getNodo() {
		return nodo;
	}

	/**
	 * @param nodo
	 *            the nodo to set
	 */
	public void setNodo(Integer nodo) {
		this.nodo = nodo;
	}

}
