package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewMensajeAdjuntosDetHist generated by hbm2java
 */
@Entity
@Table(name = "VIEW_MENSAJEADJUNTOS_DET_HIST")
public class ViewMensajeAdjuntosDetHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6581579750009878829L;
	private ViewMensajeAdjuntosDetHistId id;

	public ViewMensajeAdjuntosDetHist() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mensajeadjuntoid", column = @Column(name = "MENSAJEADJUNTOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "mensajeid", column = @Column(name = "MENSAJEID", precision = 22, scale = 0)),
			@AttributeOverride(name = "adjuntoid", column = @Column(name = "ADJUNTOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 50)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)),
			@AttributeOverride(name = "fechahistorificacion", column = @Column(name = "FECHAHISTORIFICACION", length = 7)) })
	public ViewMensajeAdjuntosDetHistId getId() {
		return this.id;
	}

	public void setId(ViewMensajeAdjuntosDetHistId id) {
		this.id = id;
	}

}
