package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewEnviosPorCanalId generated by hbm2java
 */
@Embeddable
public class ViewEnviosPorCanalId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6900190912292883729L;

	@Column(name = "ENVIOID", nullable = false, precision = 22, scale = 0)
	private Long envioid;

	@Column(name = "CANALID", precision = 22, scale = 0)
	private Long canalid;

	public ViewEnviosPorCanalId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewEnviosPorCanalId))
			return false;
		ViewEnviosPorCanalId castOther = (ViewEnviosPorCanalId) other;

		return ((this.getEnvioid() == castOther.getEnvioid()) || (this
				.getEnvioid() != null && castOther.getEnvioid() != null && this
				.getEnvioid().equals(castOther.getEnvioid())))
				&& ((this.getCanalid() == castOther.getCanalid()) || (this
						.getCanalid() != null && castOther.getCanalid() != null && this
						.getCanalid().equals(castOther.getCanalid())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getEnvioid() == null ? 0 : this.getEnvioid().hashCode());
		result = 37 * result
				+ (getCanalid() == null ? 0 : this.getCanalid().hashCode());
		return result;
	}

	/**
	 * @return the envioid
	 */
	public Long getEnvioid() {
		return envioid;
	}

	/**
	 * @param envioid
	 *            the envioid to set
	 */
	public void setEnvioid(Long envioid) {
		this.envioid = envioid;
	}

	/**
	 * @return the canalid
	 */
	public Long getCanalid() {
		return canalid;
	}

	/**
	 * @param canalid
	 *            the canalid to set
	 */
	public void setCanalid(Long canalid) {
		this.canalid = canalid;
	}

}
