package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewHistoricoSMS generated by hbm2java
 */
@Entity
@Table(name = "VIEW_HISTORICOSMS")
public class ViewHistoricoSMS implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8128787489437467721L;
	private ViewHistoricoSMSId id;

	public ViewHistoricoSMS() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idenviossms", column = @Column(name = "IDENVIOSSMS", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "uim", column = @Column(name = "UIM", length = 50)),
			@AttributeOverride(name = "idestado", column = @Column(name = "IDESTADO", precision = 22, scale = 0)),
			@AttributeOverride(name = "fecha", column = @Column(name = "FECHA", length = 7)),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO", nullable = false, length = 100)),
			@AttributeOverride(name = "idgrupo", column = @Column(name = "IDGRUPO", precision = 22, scale = 0)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 5)),
			@AttributeOverride(name = "servidor", column = @Column(name = "SERVIDOR", length = 100)),
			@AttributeOverride(name = "idventana", column = @Column(name = "IDVENTANA", precision = 22, scale = 0)),
			@AttributeOverride(name = "planificacionid", column = @Column(name = "PLANIFICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 50)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)) })
	public ViewHistoricoSMSId getId() {
		return this.id;
	}

	public void setId(ViewHistoricoSMSId id) {
		this.id = id;
	}

}
