package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewAdjuntos generated by hbm2java
 */
@Entity
@Table(name = "VIEW_ADJUNTOS")
public class ViewAdjuntos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7560111447823503083L;
	private ViewAdjuntosId id;

	public ViewAdjuntos() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "adjuntoid", column = @Column(name = "ADJUNTOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "contenido", column = @Column(name = "CONTENIDO")),
			@AttributeOverride(name = "emailid", column = @Column(name = "EMAILID", precision = 22, scale = 0)),
			@AttributeOverride(name = "imagen", column = @Column(name = "IMAGEN", precision = 22, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)) })
	public ViewAdjuntosId getId() {
		return this.id;
	}

	public void setId(ViewAdjuntosId id) {
		this.id = id;
	}

}
