package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewEnviosPorCanal generated by hbm2java
 */
@Entity
@Table(name = "VIEW_ENVIOSPORCANAL")
public class ViewEnviosPorCanal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3309811291254622504L;
	private ViewEnviosPorCanalId id;

	public ViewEnviosPorCanal() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "envioid", column = @Column(name = "ENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)) })
	public ViewEnviosPorCanalId getId() {
		return this.id;
	}

	public void setId(ViewEnviosPorCanalId id) {
		this.id = id;
	}

}
