package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewServidores generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SERVIDORES")
public class ViewServidores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8125178185840541304L;
	private ViewServidoresId id;

	public ViewServidores() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 500)),
			@AttributeOverride(name = "pordefecto", column = @Column(name = "PORDEFECTO", precision = 1, scale = 0)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "urldestino", column = @Column(name = "URLDESTINO", length = 500)),
			@AttributeOverride(name = "tipo", column = @Column(name = "TIPO", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "plataforma", column = @Column(name = "PLATAFORMA", precision = 1, scale = 0)),
			@AttributeOverride(name = "eliminado", column = @Column(name = "ELIMINADO", length = 1)),
			@AttributeOverride(name = "urlfeedback", column = @Column(name = "URLFEEDBACK", length = 500)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 50)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)) })
	public ViewServidoresId getId() {
		return this.id;
	}

	public void setId(ViewServidoresId id) {
		this.id = id;
	}

}
