package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewInformesServiciosEstado generated by hbm2java
 */
@Entity
@Table(name = "VIEW_INFORMES_SERVICIOS_ESTADO")
public class ViewInformesServiciosEstado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1686796869750399160L;
	private ViewInformesServiciosEstadoId id;

	public ViewInformesServiciosEstado() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "anno", column = @Column(name = "ANNO", precision = 4, scale = 0)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", precision = 2, scale = 0)),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO", length = 50)),
			@AttributeOverride(name = "numtotal", column = @Column(name = "NUMTOTAL", precision = 22, scale = 0)) })
	public ViewInformesServiciosEstadoId getId() {
		return this.id;
	}

	public void setId(ViewInformesServiciosEstadoId id) {
		this.id = id;
	}

}
