package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewProvPrioridadMultiorgId generated by hbm2java
 */
@Embeddable
public class ViewProvPrioridadMultiorgId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7715959069594658250L;

	@Column(name = "PROVEEDORID", precision = 22, scale = 0)
	private BigDecimal proveedorid;

	@Column(name = "URL", length = 500)
	private String url;

	@Column(name = "ORGANISMOID", precision = 22, scale = 0)
	private BigDecimal organismoid;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private BigDecimal servicioid;

	@Column(name = "PRIORIDAD", precision = 22, scale = 0)
	private Integer prioridad;

	public ViewProvPrioridadMultiorgId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewProvPrioridadMultiorgId))
			return false;
		ViewProvPrioridadMultiorgId castOther = (ViewProvPrioridadMultiorgId) other;

		return ((this.getProveedorid() == castOther.getProveedorid()) || (this
				.getProveedorid() != null && castOther.getProveedorid() != null && this
				.getProveedorid().equals(castOther.getProveedorid())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getOrganismoid() == castOther.getOrganismoid()) || (this
						.getOrganismoid() != null
						&& castOther.getOrganismoid() != null && this
						.getOrganismoid().equals(castOther.getOrganismoid())))
				&& ((this.getServicioid() == castOther.getServicioid()) || (this
						.getServicioid() != null
						&& castOther.getServicioid() != null && this
						.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getPrioridad() == castOther.getPrioridad()) || (this
						.getPrioridad() != null
						&& castOther.getPrioridad() != null && this
						.getPrioridad().equals(castOther.getPrioridad())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getProveedorid() == null ? 0 : this.getProveedorid()
						.hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37
				* result
				+ (getOrganismoid() == null ? 0 : this.getOrganismoid()
						.hashCode());
		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37 * result
				+ (getPrioridad() == null ? 0 : this.getPrioridad().hashCode());
		return result;
	}

	/**
	 * @return the proveedorid
	 */
	public BigDecimal getProveedorid() {
		return proveedorid;
	}

	/**
	 * @param proveedorid
	 *            the proveedorid to set
	 */
	public void setProveedorid(BigDecimal proveedorid) {
		this.proveedorid = proveedorid;
	}

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url
	 *            the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the organismoid
	 */
	public BigDecimal getOrganismoid() {
		return organismoid;
	}

	/**
	 * @param organismoid
	 *            the organismoid to set
	 */
	public void setOrganismoid(BigDecimal organismoid) {
		this.organismoid = organismoid;
	}

	/**
	 * @return the servicioid
	 */
	public BigDecimal getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(BigDecimal servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the prioridad
	 */
	public Integer getPrioridad() {
		return prioridad;
	}

	/**
	 * @param prioridad
	 *            the prioridad to set
	 */
	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
