package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewServidoresServiciosId generated by hbm2java
 */
@Embeddable
public class ViewServidoresServiciosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4682420747462303868L;

	@Column(name = "SERVIDORID", nullable = false, precision = 22, scale = 0)
	private Long servidorid;

	@Column(name = "SERVICIOID", nullable = false, precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "SERVIDORSERVICIOID", nullable = false, precision = 22, scale = 0)
	private Long servidorservicioid;

	@Column(name = "NOMBRESERVIDOR", length = 100)
	private String nombreservidor;

	@Column(name = "NOMBRESERVICIO", length = 100)
	private String nombreservicio;

	@Column(name = "NUMINTENTOS", precision = 10, scale = 0)
	private Integer numintentos;

	@Column(name = "HEADERSMS", length = 50)
	private String headersms;

	@Column(name = "PROVEEDORUSUARIOSMS", length = 20)
	private String proveedorusuariosms;

	@Column(name = "PROVEEDORPASSWORDSMS", length = 20)
	private String proveedorpasswordsms;

	public ViewServidoresServiciosId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewServidoresServiciosId))
			return false;
		ViewServidoresServiciosId castOther = (ViewServidoresServiciosId) other;

		return ((this.getServidorid() == castOther.getServidorid()) || (this
				.getServidorid() != null && castOther.getServidorid() != null && this
				.getServidorid().equals(castOther.getServidorid())))
				&& ((this.getServicioid() == castOther.getServicioid()) || (this
						.getServicioid() != null
						&& castOther.getServicioid() != null && this
						.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getServidorservicioid() == castOther
						.getServidorservicioid()) || (this
						.getServidorservicioid() != null
						&& castOther.getServidorservicioid() != null && this
						.getServidorservicioid().equals(
								castOther.getServidorservicioid())))
				&& ((this.getNombreservidor() == castOther.getNombreservidor()) || (this
						.getNombreservidor() != null
						&& castOther.getNombreservidor() != null && this
						.getNombreservidor().equals(
								castOther.getNombreservidor())))
				&& ((this.getNombreservicio() == castOther.getNombreservicio()) || (this
						.getNombreservicio() != null
						&& castOther.getNombreservicio() != null && this
						.getNombreservicio().equals(
								castOther.getNombreservicio())))
				&& ((this.getNumintentos() == castOther.getNumintentos()) || (this
						.getNumintentos() != null
						&& castOther.getNumintentos() != null && this
						.getNumintentos().equals(castOther.getNumintentos())))
				&& ((this.getHeadersms() == castOther.getHeadersms()) || (this
						.getHeadersms() != null
						&& castOther.getHeadersms() != null && this
						.getHeadersms().equals(castOther.getHeadersms())))
				&& ((this.getProveedorusuariosms() == castOther
						.getProveedorusuariosms()) || (this
						.getProveedorusuariosms() != null
						&& castOther.getProveedorusuariosms() != null && this
						.getProveedorusuariosms().equals(
								castOther.getProveedorusuariosms())))
				&& ((this.getProveedorpasswordsms() == castOther
						.getProveedorpasswordsms()) || (this
						.getProveedorpasswordsms() != null
						&& castOther.getProveedorpasswordsms() != null && this
						.getProveedorpasswordsms().equals(
								castOther.getProveedorpasswordsms())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServidorid() == null ? 0 : this.getServidorid()
						.hashCode());
		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37
				* result
				+ (getServidorservicioid() == null ? 0 : this
						.getServidorservicioid().hashCode());
		result = 37
				* result
				+ (getNombreservidor() == null ? 0 : this.getNombreservidor()
						.hashCode());
		result = 37
				* result
				+ (getNombreservicio() == null ? 0 : this.getNombreservicio()
						.hashCode());
		result = 37
				* result
				+ (getNumintentos() == null ? 0 : this.getNumintentos()
						.hashCode());
		result = 37 * result
				+ (getHeadersms() == null ? 0 : this.getHeadersms().hashCode());
		result = 37
				* result
				+ (getProveedorusuariosms() == null ? 0 : this
						.getProveedorusuariosms().hashCode());
		result = 37
				* result
				+ (getProveedorpasswordsms() == null ? 0 : this
						.getProveedorpasswordsms().hashCode());
		return result;
	}

	/**
	 * @return the servidorid
	 */
	public Long getServidorid() {
		return servidorid;
	}

	/**
	 * @param servidorid
	 *            the servidorid to set
	 */
	public void setServidorid(Long servidorid) {
		this.servidorid = servidorid;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the servidorservicioid
	 */
	public Long getServidorservicioid() {
		return servidorservicioid;
	}

	/**
	 * @param servidorservicioid
	 *            the servidorservicioid to set
	 */
	public void setServidorservicioid(Long servidorservicioid) {
		this.servidorservicioid = servidorservicioid;
	}

	/**
	 * @return the nombreservidor
	 */
	public String getNombreservidor() {
		return nombreservidor;
	}

	/**
	 * @param nombreservidor
	 *            the nombreservidor to set
	 */
	public void setNombreservidor(String nombreservidor) {
		this.nombreservidor = nombreservidor;
	}

	/**
	 * @return the nombreservicio
	 */
	public String getNombreservicio() {
		return nombreservicio;
	}

	/**
	 * @param nombreservicio
	 *            the nombreservicio to set
	 */
	public void setNombreservicio(String nombreservicio) {
		this.nombreservicio = nombreservicio;
	}

	/**
	 * @return the numintentos
	 */
	public Integer getNumintentos() {
		return numintentos;
	}

	/**
	 * @param numintentos
	 *            the numintentos to set
	 */
	public void setNumintentos(Integer numintentos) {
		this.numintentos = numintentos;
	}

	/**
	 * @return the headersms
	 */
	public String getHeadersms() {
		return headersms;
	}

	/**
	 * @param headersms
	 *            the headersms to set
	 */
	public void setHeadersms(String headersms) {
		this.headersms = headersms;
	}

	/**
	 * @return the proveedorusuariosms
	 */
	public String getProveedorusuariosms() {
		return proveedorusuariosms;
	}

	/**
	 * @param proveedorusuariosms
	 *            the proveedorusuariosms to set
	 */
	public void setProveedorusuariosms(String proveedorusuariosms) {
		this.proveedorusuariosms = proveedorusuariosms;
	}

	/**
	 * @return the proveedorpasswordsms
	 */
	public String getProveedorpasswordsms() {
		return proveedorpasswordsms;
	}

	/**
	 * @param proveedorpasswordsms
	 *            the proveedorpasswordsms to set
	 */
	public void setProveedorpasswordsms(String proveedorpasswordsms) {
		this.proveedorpasswordsms = proveedorpasswordsms;
	}

}
