package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewGestionSMSHist generated by hbm2java
 */
@Entity
@Table(name = "VIEW_GESTIONSMS_HIST")
public class ViewGestionSMSHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1982958567360139081L;
	private ViewGestionSMSHistId id;

	public ViewGestionSMSHist() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "aplicacion", column = @Column(name = "APLICACION", length = 100)),
			@AttributeOverride(name = "servicio", column = @Column(name = "SERVICIO", length = 100)),
			@AttributeOverride(name = "destinatario", column = @Column(name = "DESTINATARIO", length = 4000)),
			@AttributeOverride(name = "textosms", column = @Column(name = "TEXTOSMS")),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "idenviossms", column = @Column(name = "IDENVIOSSMS", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "loteenvio", column = @Column(name = "LOTEENVIO", length = 100)),
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoid", column = @Column(name = "ESTADOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO", length = 50)),
			@AttributeOverride(name = "ultimoenvio", column = @Column(name = "ULTIMOENVIO", length = 7)),
			@AttributeOverride(name = "uim", column = @Column(name = "UIM", length = 50)),
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "fechahistorificacion", column = @Column(name = "FECHAHISTORIFICACION", length = 7)) })
	public ViewGestionSMSHistId getId() {
		return this.id;
	}

	public void setId(ViewGestionSMSHistId id) {
		this.id = id;
	}

}
