package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewGestionEnviosDetHist generated by hbm2java
 */
@Entity
@Table(name = "VIEW_GESTIONENVIOS_DET_HIST")
public class ViewGestionEnviosDetHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5163434695140779608L;
	private ViewGestionEnviosDetHistId id;

	public ViewGestionEnviosDetHist() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "aplicacion", column = @Column(name = "APLICACION", length = 100)),
			@AttributeOverride(name = "canal", column = @Column(name = "CANAL", length = 100)),
			@AttributeOverride(name = "servicio", column = @Column(name = "SERVICIO", length = 100)),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO", length = 50)),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)),
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "loteenvio", column = @Column(name = "LOTEENVIO", length = 100)),
			@AttributeOverride(name = "mensajeid", column = @Column(name = "MENSAJEID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "ultimoenvio", column = @Column(name = "ULTIMOENVIO", length = 7)),
			@AttributeOverride(name = "estadoid", column = @Column(name = "ESTADOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "idexterno", column = @Column(name = "IDEXTERNO", length = 100)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 50)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)),
			@AttributeOverride(name = "fechahistorificacion", column = @Column(name = "FECHAHISTORIFICACION", length = 7)) })
	public ViewGestionEnviosDetHistId getId() {
		return this.id;
	}

	public void setId(ViewGestionEnviosDetHistId id) {
		this.id = id;
	}

}
