package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewInformesServiciosCodSIA generated by hbm2java
 */
@Entity
@Table(name = "VIEW_INFORMES_SERVICIOS_CODSIA")
public class ViewInformesServiciosCodSIA implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4158791861714474080L;
	private ViewInformesServiciosCodSIAId id;

	public ViewInformesServiciosCodSIA() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "anno", column = @Column(name = "ANNO", length = 500)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", precision = 2, scale = 0)),
			@AttributeOverride(name = "codsia", column = @Column(name = "CODSIA", precision = 22, scale = 0)),
			@AttributeOverride(name = "numtotal", column = @Column(name = "NUMTOTAL", precision = 22, scale = 0)) })
	public ViewInformesServiciosCodSIAId getId() {
		return this.id;
	}

	public void setId(ViewInformesServiciosCodSIAId id) {
		this.id = id;
	}

}
