package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewAyudas generated by hbm2java
 */
@Entity
@Table(name = "VIEW_AYUDAS")
public class ViewAyudas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3954613607589560563L;
	private ViewAyudasId id;

	public ViewAyudas() {
	}

	public ViewAyudas(ViewAyudasId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ayudaid", column = @Column(name = "AYUDAID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "textoayuda", column = @Column(name = "TEXTOAYUDA", length = 2000)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)) })
	public ViewAyudasId getId() {
		return this.id;
	}
	
	public void setId (ViewAyudasId id) {
		this.id = id;
	}

}
