package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewEnviosPendientesPorCanalId generated by hbm2java
 */
@Embeddable
public class ViewEnviosPendientesPorCanalId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5363027558329461666L;

	@Column(name = "APLICACIONID", nullable = false, precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "NOMBRE", length = 100)
	private String nombre;

	@Column(name = "EMAILS", precision = 22, scale = 0)
	private Integer emails;

	@Column(name = "SMS", precision = 22, scale = 0)
	private Integer sms;

	@Column(name = "RECEPCIONSMS", precision = 22, scale = 0)
	private Integer recepcionsms;

	@Column(name = "PUSH", precision = 22, scale = 0)
	private Integer push;

	public ViewEnviosPendientesPorCanalId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewEnviosPendientesPorCanalId))
			return false;
		ViewEnviosPendientesPorCanalId castOther = (ViewEnviosPendientesPorCanalId) other;

		return ((this.getAplicacionid() == castOther.getAplicacionid()) || (this
				.getAplicacionid() != null
				&& castOther.getAplicacionid() != null && this
				.getAplicacionid().equals(castOther.getAplicacionid())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getEmails() == castOther.getEmails()) || (this
						.getEmails() != null && castOther.getEmails() != null && this
						.getEmails().equals(castOther.getEmails())))
				&& ((this.getSms() == castOther.getSms()) || (this.getSms() != null
						&& castOther.getSms() != null && this.getSms().equals(
						castOther.getSms())))
				&& ((this.getRecepcionsms() == castOther.getRecepcionsms()) || (this
						.getRecepcionsms() != null
						&& castOther.getRecepcionsms() != null && this
						.getRecepcionsms().equals(castOther.getRecepcionsms())))
				&& ((this.getPush() == castOther.getPush()) || (this.getPush() != null
						&& castOther.getPush() != null && this.getPush()
						.equals(castOther.getPush())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAplicacionid() == null ? 0 : this.getAplicacionid()
						.hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getEmails() == null ? 0 : this.getEmails().hashCode());
		result = 37 * result
				+ (getSms() == null ? 0 : this.getSms().hashCode());
		result = 37
				* result
				+ (getRecepcionsms() == null ? 0 : this.getRecepcionsms()
						.hashCode());
		result = 37 * result
				+ (getPush() == null ? 0 : this.getPush().hashCode());
		return result;
	}

	/**
	 * @return the aplicacionid
	 */
	public Long getAplicacionid() {
		return aplicacionid;
	}

	/**
	 * @param aplicacionid
	 *            the aplicacionid to set
	 */
	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre
	 *            the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the emails
	 */
	public Integer getEmails() {
		return emails;
	}

	/**
	 * @param emails
	 *            the emails to set
	 */
	public void setEmails(Integer emails) {
		this.emails = emails;
	}

	/**
	 * @return the sms
	 */
	public Integer getSms() {
		return sms;
	}

	/**
	 * @param sms
	 *            the sms to set
	 */
	public void setSms(Integer sms) {
		this.sms = sms;
	}

	/**
	 * @return the recepcionsms
	 */
	public Integer getRecepcionsms() {
		return recepcionsms;
	}

	/**
	 * @param recepcionsms
	 *            the recepcionsms to set
	 */
	public void setRecepcionsms(Integer recepcionsms) {
		this.recepcionsms = recepcionsms;
	}

	/**
	 * @return the push
	 */
	public Integer getPush() {
		return push;
	}

	/**
	 * @param push
	 *            the push to set
	 */
	public void setPush(Integer push) {
		this.push = push;
	}

}
