package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewLotesEnviosDetHist generated by hbm2java
 */
@Entity
@Table(name = "VIEW_LOTESENVIOS_DET_HIST")
public class ViewLotesEnviosDetHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8560549030346885234L;
	private ViewLotesEnviosDetHistId id;

	public ViewLotesEnviosDetHist() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 500)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoenvioid", column = @Column(name = "ESTADOENVIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "servicio", column = @Column(name = "SERVICIO", length = 100)),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "aplicacion", column = @Column(name = "APLICACION", length = 100)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 50)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)),
			@AttributeOverride(name = "canalid", column = @Column(name = "CANALID", precision = 22, scale = 0)),
			@AttributeOverride(name = "fechahistorificacion", column = @Column(name = "FECHAHISTORIFICACION", length = 7)) })
	public ViewLotesEnviosDetHistId getId() {
		return this.id;
	}

	public void setId(ViewLotesEnviosDetHistId id) {
		this.id = id;
	}

}
