package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewSeridorOrganismoId generated by hbm2java
 */
@Embeddable
public class ViewSeridorOrganismoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5234476971719499495L;

	@Column(name = "SERVIDORID", nullable = false, precision = 22, scale = 0)
	private Long servidorid;

	@Column(name = "ORGANISMOID", nullable = false, precision = 22, scale = 0)
	private Long organismoid;

	@Column(name = "SERVIDORORGANISMOID", nullable = false, precision = 22, scale = 0)
	private Long servidororganismoid;

	@Column(name = "NOMBRESERVIDOR", length = 100)
	private String nombreservidor;

	@Column(name = "NOMBREORGANISMO", nullable = false, length = 100)
	private String nombreorganismo;

	@Column(name = "DIR3ORGANISMO", nullable = false, length = 100)
	private String dir3organismo;

	@Column(name = "NUMINTENTOS", precision = 10, scale = 0)
	private Integer numintentos;

	@Column(name = "HEADERSMS", length = 50)
	private String headersms;

	@Column(name = "PROVEEDORUSUARIOSMS", length = 20)
	private String proveedorusuariosms;

	@Column(name = "PROVEEDORPASSWORDSMS", length = 20)
	private String proveedorpasswordsms;

	public ViewSeridorOrganismoId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewSeridorOrganismoId))
			return false;
		ViewSeridorOrganismoId castOther = (ViewSeridorOrganismoId) other;

		return ((this.getServidorid() == castOther.getServidorid()) || (this
				.getServidorid() != null && castOther.getServidorid() != null && this
				.getServidorid().equals(castOther.getServidorid())))
				&& ((this.getOrganismoid() == castOther.getOrganismoid()) || (this
						.getOrganismoid() != null
						&& castOther.getOrganismoid() != null && this
						.getOrganismoid().equals(castOther.getOrganismoid())))
				&& ((this.getServidororganismoid() == castOther
						.getServidororganismoid()) || (this
						.getServidororganismoid() != null
						&& castOther.getServidororganismoid() != null && this
						.getServidororganismoid().equals(
								castOther.getServidororganismoid())))
				&& ((this.getNombreservidor() == castOther.getNombreservidor()) || (this
						.getNombreservidor() != null
						&& castOther.getNombreservidor() != null && this
						.getNombreservidor().equals(
								castOther.getNombreservidor())))
				&& ((this.getNombreorganismo() == castOther
						.getNombreorganismo()) || (this.getNombreorganismo() != null
						&& castOther.getNombreorganismo() != null && this
						.getNombreorganismo().equals(
								castOther.getNombreorganismo())))
				&& ((this.getDir3organismo() == castOther.getDir3organismo()) || (this
						.getDir3organismo() != null
						&& castOther.getDir3organismo() != null && this
						.getDir3organismo()
						.equals(castOther.getDir3organismo())))
				&& ((this.getNumintentos() == castOther.getNumintentos()) || (this
						.getNumintentos() != null
						&& castOther.getNumintentos() != null && this
						.getNumintentos().equals(castOther.getNumintentos())))
				&& ((this.getHeadersms() == castOther.getHeadersms()) || (this
						.getHeadersms() != null
						&& castOther.getHeadersms() != null && this
						.getHeadersms().equals(castOther.getHeadersms())))
				&& ((this.getProveedorusuariosms() == castOther
						.getProveedorusuariosms()) || (this
						.getProveedorusuariosms() != null
						&& castOther.getProveedorusuariosms() != null && this
						.getProveedorusuariosms().equals(
								castOther.getProveedorusuariosms())))
				&& ((this.getProveedorpasswordsms() == castOther
						.getProveedorpasswordsms()) || (this
						.getProveedorpasswordsms() != null
						&& castOther.getProveedorpasswordsms() != null && this
						.getProveedorpasswordsms().equals(
								castOther.getProveedorpasswordsms())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServidorid() == null ? 0 : this.getServidorid()
						.hashCode());
		result = 37
				* result
				+ (getOrganismoid() == null ? 0 : this.getOrganismoid()
						.hashCode());
		result = 37
				* result
				+ (getServidororganismoid() == null ? 0 : this
						.getServidororganismoid().hashCode());
		result = 37
				* result
				+ (getNombreservidor() == null ? 0 : this.getNombreservidor()
						.hashCode());
		result = 37
				* result
				+ (getNombreorganismo() == null ? 0 : this.getNombreorganismo()
						.hashCode());
		result = 37
				* result
				+ (getDir3organismo() == null ? 0 : this.getDir3organismo()
						.hashCode());
		result = 37
				* result
				+ (getNumintentos() == null ? 0 : this.getNumintentos()
						.hashCode());
		result = 37 * result
				+ (getHeadersms() == null ? 0 : this.getHeadersms().hashCode());
		result = 37
				* result
				+ (getProveedorusuariosms() == null ? 0 : this
						.getProveedorusuariosms().hashCode());
		result = 37
				* result
				+ (getProveedorpasswordsms() == null ? 0 : this
						.getProveedorpasswordsms().hashCode());
		return result;
	}

	/**
	 * @return the servidorid
	 */
	public Long getServidorid() {
		return servidorid;
	}

	/**
	 * @param servidorid
	 *            the servidorid to set
	 */
	public void setServidorid(Long servidorid) {
		this.servidorid = servidorid;
	}

	/**
	 * @return the organismoid
	 */
	public Long getOrganismoid() {
		return organismoid;
	}

	/**
	 * @param organismoid
	 *            the organismoid to set
	 */
	public void setOrganismoid(Long organismoid) {
		this.organismoid = organismoid;
	}

	/**
	 * @return the servidororganismoid
	 */
	public Long getServidororganismoid() {
		return servidororganismoid;
	}

	/**
	 * @param servidororganismoid
	 *            the servidororganismoid to set
	 */
	public void setServidororganismoid(Long servidororganismoid) {
		this.servidororganismoid = servidororganismoid;
	}

	/**
	 * @return the nombreservidor
	 */
	public String getNombreservidor() {
		return nombreservidor;
	}

	/**
	 * @param nombreservidor
	 *            the nombreservidor to set
	 */
	public void setNombreservidor(String nombreservidor) {
		this.nombreservidor = nombreservidor;
	}

	/**
	 * @return the nombreorganismo
	 */
	public String getNombreorganismo() {
		return nombreorganismo;
	}

	/**
	 * @param nombreorganismo
	 *            the nombreorganismo to set
	 */
	public void setNombreorganismo(String nombreorganismo) {
		this.nombreorganismo = nombreorganismo;
	}

	/**
	 * @return the dir3organismo
	 */
	public String getDir3organismo() {
		return dir3organismo;
	}

	/**
	 * @param dir3organismo
	 *            the dir3organismo to set
	 */
	public void setDir3organismo(String dir3organismo) {
		this.dir3organismo = dir3organismo;
	}

	/**
	 * @return the numintentos
	 */
	public Integer getNumintentos() {
		return numintentos;
	}

	/**
	 * @param numintentos
	 *            the numintentos to set
	 */
	public void setNumintentos(Integer numintentos) {
		this.numintentos = numintentos;
	}

	/**
	 * @return the headersms
	 */
	public String getHeadersms() {
		return headersms;
	}

	/**
	 * @param headersms
	 *            the headersms to set
	 */
	public void setHeadersms(String headersms) {
		this.headersms = headersms;
	}

	/**
	 * @return the proveedorusuariosms
	 */
	public String getProveedorusuariosms() {
		return proveedorusuariosms;
	}

	/**
	 * @param proveedorusuariosms
	 *            the proveedorusuariosms to set
	 */
	public void setProveedorusuariosms(String proveedorusuariosms) {
		this.proveedorusuariosms = proveedorusuariosms;
	}

	/**
	 * @return the proveedorpasswordsms
	 */
	public String getProveedorpasswordsms() {
		return proveedorpasswordsms;
	}

	/**
	 * @param proveedorpasswordsms
	 *            the proveedorpasswordsms to set
	 */
	public void setProveedorpasswordsms(String proveedorpasswordsms) {
		this.proveedorpasswordsms = proveedorpasswordsms;
	}

}
