package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewUsuariosPush generated by hbm2java
 */
@Entity
@Table(name = "VIEW_USUARIOS_PUSH")
public class ViewUsuariosPush implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1978879403580876869L;

	@Id
	@Column(name = "USUARIOID", nullable = false, precision = 22, scale = 0)
	private Long usuarioid;

	@Column(name = "NOMBREUSUARIO", length = 100)
	private String nombreusuario;

	@Column(name = "PLATAFORMA", length = 7)
	private String plataforma;

	@Column(name = "TOKENUSUARIO", length = 200)
	private String tokenusuario;

	@Column(name = "APLICACIONID", precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "APLICACION", length = 100)
	private String aplicacion;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "SERVICIO", length = 100)
	private String servicio;

	@Column(name = "DISPOSITIVOID", length = 200)
	private String dispositivoid;

	@Column(name = "FECHA", length = 7)
	private Date fecha;

	public ViewUsuariosPush() {
	}

	public Long getUsuarioid() {
		return usuarioid;
	}

	public void setUsuarioid(Long usuarioid) {
		this.usuarioid = usuarioid;
	}

	public String getNombreusuario() {
		return nombreusuario;
	}

	public void setNombreusuario(String nombreusuario) {
		this.nombreusuario = nombreusuario;
	}

	public String getPlataforma() {
		return plataforma;
	}

	public void setPlataforma(String plataforma) {
		this.plataforma = plataforma;
	}

	public String getTokenusuario() {
		return tokenusuario;
	}

	public void setTokenusuario(String tokenusuario) {
		this.tokenusuario = tokenusuario;
	}

	public Long getAplicacionid() {
		return aplicacionid;
	}

	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	public String getAplicacion() {
		return aplicacion;
	}

	public void setAplicacion(String aplicacion) {
		this.aplicacion = aplicacion;
	}

	public Long getServicioid() {
		return servicioid;
	}

	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	public String getServicio() {
		return servicio;
	}

	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	public String getDispositivoid() {
		return dispositivoid;
	}

	public void setDispositivoid(String dispositivoid) {
		this.dispositivoid = dispositivoid;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
