package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewTiposParametros generated by hbm2java
 */
@Entity
@Table(name = "VIEW_TIPOSPARAMETROS")
public class ViewTiposParametros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8795624834729718757L;
	private ViewTiposParametrosId id;

	public ViewTiposParametros() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tipoparametroid", column = @Column(name = "TIPOPARAMETROID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", nullable = false, length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 500)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", nullable = false, length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", nullable = false, length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "tags", column = @Column(name = "TAGS", length = 100)),
			@AttributeOverride(name = "tipo", column = @Column(name = "TIPO", precision = 22, scale = 0)),
			@AttributeOverride(name = "tipocampo", column = @Column(name = "TIPOCAMPO", length = 50)) })
	public ViewTiposParametrosId getId() {
		return this.id;
	}

	public void setId(ViewTiposParametrosId id) {
		this.id = id;
	}

}
