package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewEstadoPorEnvio generated by hbm2java
 */
@Entity
@Table(name = "VIEW_ESTADOPORENVIO")
public class ViewEstadoPorEnvio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4855158177214220876L;
	private ViewEstadoPorEnvioId id;

	public ViewEstadoPorEnvio() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "envioid", column = @Column(name = "ENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoid", column = @Column(name = "ESTADOID", precision = 22, scale = 0)) })
	public ViewEstadoPorEnvioId getId() {
		return this.id;
	}

	public void setId(ViewEstadoPorEnvioId id) {
		this.id = id;
	}

}
