package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewProveedoresPrioridad generated by hbm2java
 */
@Entity
@Table(name = "VIEW_PROVEEDORES_PRIORIDAD")
public class ViewProveedoresPrioridad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1697908833046336244L;
	private ViewProveedoresPrioridadId id;

	public ViewProveedoresPrioridad() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "proveedorid", column = @Column(name = "PROVEEDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "url", column = @Column(name = "URL", length = 500)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 200)),
			@AttributeOverride(name = "telefono", column = @Column(name = "TELEFONO", length = 200)),
			@AttributeOverride(name = "texto", column = @Column(name = "TEXTO", length = 200)),
			@AttributeOverride(name = "uim", column = @Column(name = "UIM", length = 200)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "prioridad", column = @Column(name = "PRIORIDAD", precision = 22, scale = 0)) })
	public ViewProveedoresPrioridadId getId() {
		return this.id;
	}

	public void setId(ViewProveedoresPrioridadId id) {
		this.id = id;
	}

}
