package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewInformesServiciosCodSIAId generated by hbm2java
 */
@Embeddable
public class ViewInformesServiciosCodSIAId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6883255706514582047L;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "ANNO", length = 500)
	private String anno;

	@Column(name = "MES", precision = 2, scale = 0)
	private Integer mes;

	@Column(name = "CODSIA", precision = 22, scale = 0)
	private Long codsia;

	@Column(name = "NUMTOTAL", precision = 22, scale = 0)
	private Integer numtotal;

	public ViewInformesServiciosCodSIAId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewInformesServiciosCodSIAId))
			return false;
		ViewInformesServiciosCodSIAId castOther = (ViewInformesServiciosCodSIAId) other;

		return ((this.getServicioid() == castOther.getServicioid()) || (this
				.getServicioid() != null && castOther.getServicioid() != null && this
				.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getAnno() == castOther.getAnno()) || (this.getAnno() != null
						&& castOther.getAnno() != null && this.getAnno()
						.equals(castOther.getAnno())))
				&& ((this.getMes() == castOther.getMes()) || (this.getMes() != null
						&& castOther.getMes() != null && this.getMes().equals(
						castOther.getMes())))
				&& ((this.getCodsia() == castOther.getCodsia()) || (this
						.getCodsia() != null && castOther.getCodsia() != null && this
						.getCodsia().equals(castOther.getCodsia())))
				&& ((this.getNumtotal() == castOther.getNumtotal()) || (this
						.getNumtotal() != null
						&& castOther.getNumtotal() != null && this
						.getNumtotal().equals(castOther.getNumtotal())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37 * result
				+ (getAnno() == null ? 0 : this.getAnno().hashCode());
		result = 37 * result
				+ (getMes() == null ? 0 : this.getMes().hashCode());
		result = 37 * result
				+ (getCodsia() == null ? 0 : this.getCodsia().hashCode());
		result = 37 * result
				+ (getNumtotal() == null ? 0 : this.getNumtotal().hashCode());
		return result;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the anno
	 */
	public String getAnno() {
		return anno;
	}

	/**
	 * @param anno
	 *            the anno to set
	 */
	public void setAnno(String anno) {
		this.anno = anno;
	}

	/**
	 * @return the mes
	 */
	public Integer getMes() {
		return mes;
	}

	/**
	 * @param mes
	 *            the mes to set
	 */
	public void setMes(Integer mes) {
		this.mes = mes;
	}

	/**
	 * @return the codsia
	 */
	public Long getCodsia() {
		return codsia;
	}

	/**
	 * @param codsia
	 *            the codsia to set
	 */
	public void setCodsia(Long codsia) {
		this.codsia = codsia;
	}

	/**
	 * @return the numtotal
	 */
	public Integer getNumtotal() {
		return numtotal;
	}

	/**
	 * @param numtotal
	 *            the numtotal to set
	 */
	public void setNumtotal(Integer numtotal) {
		this.numtotal = numtotal;
	}

}
