package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewServServidorPush generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SERV_SERVIDOR_PUSH")
public class ViewServServidorPush implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8400816740641967627L;
	private ViewServServidorPushId id;

	public ViewServServidorPush() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servidorpushid", column = @Column(name = "SERVIDORPUSHID", precision = 22, scale = 0)),
			@AttributeOverride(name = "plataformaid", column = @Column(name = "PLATAFORMAID", precision = 22, scale = 0)),
			@AttributeOverride(name = "url", column = @Column(name = "URL", length = 500)),
			@AttributeOverride(name = "urlfeedback", column = @Column(name = "URLFEEDBACK", length = 500)),
			@AttributeOverride(name = "puertourl", column = @Column(name = "PUERTOURL", length = 200)),
			@AttributeOverride(name = "puertourlfeedback", column = @Column(name = "PUERTOURLFEEDBACK", length = 200)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "prioridad", column = @Column(name = "PRIORIDAD", precision = 22, scale = 0)) })
	public ViewServServidorPushId getId() {
		return this.id;
	}

	public void setId(ViewServServidorPushId id) {
		this.id = id;
	}

}
