package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewEstadoLotesEnviosId generated by hbm2java
 */
@Embeddable
public class ViewEstadoLotesEnviosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5044018963193429939L;

	@Column(name = "LOTEENVIOID", precision = 22, scale = 0)
	private Long loteenvioid;

	

	public ViewEstadoLotesEnviosId() {
	}



	/**
	 * @return the loteenvioid
	 */
	public Long getLoteenvioid() {
		return loteenvioid;
	}

	/**
	 * @param loteenvioid
	 *            the loteenvioid to set
	 */
	public void setLoteenvioid(Long loteenvioid) {
		this.loteenvioid = loteenvioid;
	}

	
}
