package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewLogs generated by hbm2java
 */
@Entity
@Table(name = "VIEW_LOGS")
public class ViewLogs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3056057654880347653L;
	private ViewLogsId id;

	public ViewLogs() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "logid", column = @Column(name = "LOGID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "logdescripcion", column = @Column(name = "LOGDESCRIPCION", length = 1000)),
			@AttributeOverride(name = "sourcename", column = @Column(name = "SOURCENAME", nullable = false, length = 100)),
			@AttributeOverride(name = "sourceid", column = @Column(name = "SOURCEID", precision = 22, scale = 0)),
			@AttributeOverride(name = "sourcedescription", column = @Column(name = "SOURCEDESCRIPTION", length = 100)),
			@AttributeOverride(name = "adtusuario", column = @Column(name = "ADTUSUARIO", length = 100)),
			@AttributeOverride(name = "adtfecha", column = @Column(name = "ADTFECHA", length = 7)),
			@AttributeOverride(name = "logaccion", column = @Column(name = "LOGACCION", precision = 22, scale = 0)) })
	public ViewLogsId getId() {
		return this.id;
	}

	public void setId(ViewLogsId id) {
		this.id = id;
	}

}
