package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewTiposParametrosId generated by hbm2java
 */
@Embeddable
public class ViewTiposParametrosId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3955006497204959481L;

	@Column(name = "TIPOPARAMETROID", nullable = false, precision = 22, scale = 0)
	private Long tipoparametroid;

	@Column(name = "NOMBRE", nullable = false, length = 100)
	private String nombre;

	@Column(name = "DESCRIPCION", length = 500)
	private String descripcion;

	@Column(name = "ACTIVO", precision = 1, scale = 0)
	private Boolean activo;

	@Column(name = "FECHACREACION", nullable = false, length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", nullable = false, length = 100)
	private String creadopor;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadopor;

	@Column(name = "TAGS", length = 100)
	private String tags;

	@Column(name = "TIPO", precision = 22, scale = 0)
	private Integer tipo;

	@Column(name = "TIPOCAMPO", length = 50)
	private String tipocampo;

	public ViewTiposParametrosId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewTiposParametrosId))
			return false;
		ViewTiposParametrosId castOther = (ViewTiposParametrosId) other;

		return ((this.getTipoparametroid() == castOther.getTipoparametroid()) || (this
				.getTipoparametroid() != null
				&& castOther.getTipoparametroid() != null && this
				.getTipoparametroid().equals(castOther.getTipoparametroid())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getDescripcion() == castOther.getDescripcion()) || (this
						.getDescripcion() != null
						&& castOther.getDescripcion() != null && this
						.getDescripcion().equals(castOther.getDescripcion())))
				&& ((this.getActivo() == castOther.getActivo()) || (this
						.getActivo() != null && castOther.getActivo() != null && this
						.getActivo().equals(castOther.getActivo())))
				&& ((this.getFechacreacion() == castOther.getFechacreacion()) || (this
						.getFechacreacion() != null
						&& castOther.getFechacreacion() != null && this
						.getFechacreacion()
						.equals(castOther.getFechacreacion())))
				&& ((this.getCreadopor() == castOther.getCreadopor()) || (this
						.getCreadopor() != null
						&& castOther.getCreadopor() != null && this
						.getCreadopor().equals(castOther.getCreadopor())))
				&& ((this.getFechamodificacion() == castOther
						.getFechamodificacion()) || (this
						.getFechamodificacion() != null
						&& castOther.getFechamodificacion() != null && this
						.getFechamodificacion().equals(
								castOther.getFechamodificacion())))
				&& ((this.getModificadopor() == castOther.getModificadopor()) || (this
						.getModificadopor() != null
						&& castOther.getModificadopor() != null && this
						.getModificadopor()
						.equals(castOther.getModificadopor())))
				&& ((this.getTags() == castOther.getTags()) || (this.getTags() != null
						&& castOther.getTags() != null && this.getTags()
						.equals(castOther.getTags())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())))
				&& ((this.getTipocampo() == castOther.getTipocampo()) || (this
						.getTipocampo() != null
						&& castOther.getTipocampo() != null && this
						.getTipocampo().equals(castOther.getTipocampo())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTipoparametroid() == null ? 0 : this.getTipoparametroid()
						.hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37
				* result
				+ (getDescripcion() == null ? 0 : this.getDescripcion()
						.hashCode());
		result = 37 * result
				+ (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37
				* result
				+ (getFechacreacion() == null ? 0 : this.getFechacreacion()
						.hashCode());
		result = 37 * result
				+ (getCreadopor() == null ? 0 : this.getCreadopor().hashCode());
		result = 37
				* result
				+ (getFechamodificacion() == null ? 0 : this
						.getFechamodificacion().hashCode());
		result = 37
				* result
				+ (getModificadopor() == null ? 0 : this.getModificadopor()
						.hashCode());
		result = 37 * result
				+ (getTags() == null ? 0 : this.getTags().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37 * result
				+ (getTipocampo() == null ? 0 : this.getTipocampo().hashCode());
		return result;
	}

	/**
	 * @return the tipoparametroid
	 */
	public Long getTipoparametroid() {
		return tipoparametroid;
	}

	/**
	 * @param tipoparametroid
	 *            the tipoparametroid to set
	 */
	public void setTipoparametroid(Long tipoparametroid) {
		this.tipoparametroid = tipoparametroid;
	}

	/**
	 * @return the nombre
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * @param nombre
	 *            the nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * @return the descripcion
	 */
	public String getDescripcion() {
		return descripcion;
	}

	/**
	 * @param descripcion
	 *            the descripcion to set
	 */
	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	/**
	 * @return the activo
	 */
	public Boolean getActivo() {
		return activo;
	}

	/**
	 * @param activo
	 *            the activo to set
	 */
	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	/**
	 * @return the fechacreacion
	 */
	public Date getFechacreacion() {
		return fechacreacion;
	}

	/**
	 * @param fechacreacion
	 *            the fechacreacion to set
	 */
	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	/**
	 * @return the creadopor
	 */
	public String getCreadopor() {
		return creadopor;
	}

	/**
	 * @param creadopor
	 *            the creadopor to set
	 */
	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	/**
	 * @return the fechamodificacion
	 */
	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	/**
	 * @param fechamodificacion
	 *            the fechamodificacion to set
	 */
	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	/**
	 * @return the modificadopor
	 */
	public String getModificadopor() {
		return modificadopor;
	}

	/**
	 * @param modificadopor
	 *            the modificadopor to set
	 */
	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	/**
	 * @return the tags
	 */
	public String getTags() {
		return tags;
	}

	/**
	 * @param tags
	 *            the tags to set
	 */
	public void setTags(String tags) {
		this.tags = tags;
	}

	/**
	 * @return the tipo
	 */
	public Integer getTipo() {
		return tipo;
	}

	/**
	 * @param tipo
	 *            the tipo to set
	 */
	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	/**
	 * @return the tipocampo
	 */
	public String getTipocampo() {
		return tipocampo;
	}

	/**
	 * @param tipocampo
	 *            the tipocampo to set
	 */
	public void setTipocampo(String tipocampo) {
		this.tipocampo = tipocampo;
	}

}
