package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewHistoricoEmailHist generated by hbm2java
 */
@Entity
@Table(name = "VIEW_HISTORICOEMAIL_HIST")
public class ViewHistoricoEmailHist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 275072809542659976L;
	private ViewHistoricoEmailHistId id;

	public ViewHistoricoEmailHist() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "historicoid", column = @Column(name = "HISTORICOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "emailid", column = @Column(name = "EMAILID", precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoid", column = @Column(name = "ESTADOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "planificacionid", column = @Column(name = "PLANIFICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "estado", column = @Column(name = "ESTADO", nullable = false, length = 100)),
			@AttributeOverride(name = "fecha", column = @Column(name = "FECHA", length = 7)),
			@AttributeOverride(name = "servidor", column = @Column(name = "SERVIDOR", length = 100)),
			@AttributeOverride(name = "codigoexterno", column = @Column(name = "CODIGOEXTERNO", length = 100)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 50)),
			@AttributeOverride(name = "password", column = @Column(name = "PASSWORD", length = 50)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 1000)),
			@AttributeOverride(name = "fechahistorificacion", column = @Column(name = "FECHAHISTORIFICACION", length = 7)) })
	public ViewHistoricoEmailHistId getId() {
		return this.id;
	}

	public void setId(ViewHistoricoEmailHistId id) {
		this.id = id;
	}

}
