package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewServEmail generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SERV_EMAIL")
public class ViewServEmail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4824830597809978556L;
	private ViewServEmailId id;

	public ViewServEmail() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", precision = 22, scale = 0)),
			@AttributeOverride(name = "ip", column = @Column(name = "IP", length = 200)),
			@AttributeOverride(name = "usuario", column = @Column(name = "USUARIO", length = 200)),
			@AttributeOverride(name = "contraseña", column = @Column(name = "CONTRASEÑA", length = 200)),
			@AttributeOverride(name = "conexion", column = @Column(name = "CONEXION", length = 200)),
			@AttributeOverride(name = "puerto", column = @Column(name = "PUERTO", length = 200)),
			@AttributeOverride(name = "autentificacion", column = @Column(name = "AUTENTIFICACION", length = 200)),
			@AttributeOverride(name = "tiempoespera", column = @Column(name = "TIEMPOESPERA", length = 200)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "prioridad", column = @Column(name = "PRIORIDAD", precision = 22, scale = 0)) })
	public ViewServEmailId getId() {
		return this.id;
	}

	public void setId(ViewServEmailId id) {
		this.id = id;
	}

}
