package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewMensajesDetallada generated by hbm2java
 */
@Entity
@Table(name = "VIEW_MENSAJES_DETALLADA")
public class ViewMensajesDetallada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3979848376634193328L;
	
	@Id
	@Column(name = "MENSAJEID", nullable = false, precision = 22, scale = 0)
	private Long mensajeid;

	@Column(name = "LOTEENVIOID", nullable = false, precision = 22, scale = 0)
	private Long loteenvioid;

	@Column(name = "CODIGOEXTERNO", length = 100)
	private String codigoexterno;

	@Column(name = "CUERPO")
	private String cuerpo;

	@Column(name = "CABECERA", length = 2000)
	private String cabecera;

	@Column(name = "ESTADOACTUAL", nullable = false, length = 50)
	private String estadoactual;

	@Column(name = "NUMEROENVIOS", precision = 10, scale = 0)
	private Integer numeroenvios;

	@Column(name = "ULTIMOENVIO", length = 7)
	private Date ultimoenvio;

	@Column(name = "FECHACREACION", nullable = false, length = 7)
	private Date fechacreacion;

	@Column(name = "CREADOPOR", nullable = false, length = 100)
	private String creadopor;

	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechamodificacion;

	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadopor;

	@Column(name = "ULTIMOIDHISTORICO", precision = 22, scale = 0)
	private Long ultimoidhistorico;

	@Column(name = "TIPOCUERPO", length = 10)
	private String tipocuerpo;

	@Column(name = "TIPOCODIFICACION", length = 50)
	private String tipocodificacion;

	@Column(name = "PRIORIDAD", precision = 22, scale = 0)
	private Integer prioridad;

	@Column(name = "TIPOMENSAJE", nullable = false, length = 20)
	private String tipomensaje;

	@Column(name = "TELEFONO", length = 15)
	private String telefono;

	@Column(name = "CANALID", precision = 22, scale = 0)
	private Long canalid;

	@Column(name = "USUARIO", length = 50)
	private String usuario;

	@Column(name = "PASSWORD", length = 50)
	private String password;

	public ViewMensajesDetallada() {
	}

	public Long getMensajeid() {
		return mensajeid;
	}

	public void setMensajeid(Long mensajeid) {
		this.mensajeid = mensajeid;
	}

	public Long getLoteenvioid() {
		return loteenvioid;
	}

	public void setLoteenvioid(Long loteenvioid) {
		this.loteenvioid = loteenvioid;
	}

	public String getCodigoexterno() {
		return codigoexterno;
	}

	public void setCodigoexterno(String codigoexterno) {
		this.codigoexterno = codigoexterno;
	}

	public String getCuerpo() {
		return cuerpo;
	}

	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

	public String getCabecera() {
		return cabecera;
	}

	public void setCabecera(String cabecera) {
		this.cabecera = cabecera;
	}

	public String getEstadoactual() {
		return estadoactual;
	}

	public void setEstadoactual(String estadoactual) {
		this.estadoactual = estadoactual;
	}

	public Integer getNumeroenvios() {
		return numeroenvios;
	}

	public void setNumeroenvios(Integer numeroenvios) {
		this.numeroenvios = numeroenvios;
	}

	public Date getUltimoenvio() {
		return ultimoenvio;
	}

	public void setUltimoenvio(Date ultimoenvio) {
		this.ultimoenvio = ultimoenvio;
	}

	public Date getFechacreacion() {
		return fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	public String getCreadopor() {
		return creadopor;
	}

	public void setCreadopor(String creadopor) {
		this.creadopor = creadopor;
	}

	public Date getFechamodificacion() {
		return fechamodificacion;
	}

	public void setFechamodificacion(Date fechamodificacion) {
		this.fechamodificacion = fechamodificacion;
	}

	public String getModificadopor() {
		return modificadopor;
	}

	public void setModificadopor(String modificadopor) {
		this.modificadopor = modificadopor;
	}

	public Long getUltimoidhistorico() {
		return ultimoidhistorico;
	}

	public void setUltimoidhistorico(Long ultimoidhistorico) {
		this.ultimoidhistorico = ultimoidhistorico;
	}

	public String getTipocuerpo() {
		return tipocuerpo;
	}

	public void setTipocuerpo(String tipocuerpo) {
		this.tipocuerpo = tipocuerpo;
	}

	public String getTipocodificacion() {
		return tipocodificacion;
	}

	public void setTipocodificacion(String tipocodificacion) {
		this.tipocodificacion = tipocodificacion;
	}

	public Integer getPrioridad() {
		return prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	public String getTipomensaje() {
		return tipomensaje;
	}

	public void setTipomensaje(String tipomensaje) {
		this.tipomensaje = tipomensaje;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Long getCanalid() {
		return canalid;
	}

	public void setCanalid(Long canalid) {
		this.canalid = canalid;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
