package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TblCanales generated by hbm2java
 */
@Entity
@Table(name = "VIEW_PROCESOSMANUALES")
public class ViewProcesosManuales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3001600976168842226L;
	
	@Id
	@Column(name = "PROCESOSMANUALESID", unique = true, nullable = false, precision = 22, scale = 0)
	private Long procesosManualesId;
	
	@Column(name = "PROCESOID", precision = 22, scale = 0)
	private Long procesoId;
	
	@Column(name = "NOMBRE", length = 7)
	private String nombre;
	
	@Column(name = "JOB", length = 7)
	private String job;
	
	@Column(name = "PARAMETRO1", length = 300)
	private String parametro1;
	
	@Column(name = "PARAMETRO2", length = 300)
	private String parametro2;
	
	@Column(name = "PARAMETRO3", length = 300)
	private String parametro3;
	
	@Column(name = "ELIMINADO", length = 1)
	private String eliminado;
	
	@Column(name = "FECHACREACION", length = 7)
	private Date fechaCreacion;
	
	@Column(name = "CREADOPOR", length = 100)
	private String creadoPor;
	
	@Column(name = "FECHAMODIFICACION", length = 7)
	private Date fechaModificacion;
	
	@Column(name = "MODIFICADOPOR", length = 100)
	private String modificadoPor;
	
	
	
	public ViewProcesosManuales() {
	}

	public Long getProcesosManualesId() {
		return procesosManualesId;
	}

	public void setProcesosManualesId(Long procesosManualesId) {
		this.procesosManualesId = procesosManualesId;
	}

	public Long getProcesoId() {
		return procesoId;
	}

	public void setProcesoId(Long procesoId) {
		this.procesoId = procesoId;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getParametro1() {
		return parametro1;
	}

	public void setParametro1(String parametro1) {
		this.parametro1 = parametro1;
	}

	public String getParametro2() {
		return parametro2;
	}

	public void setParametro2(String parametro2) {
		this.parametro2 = parametro2;
	}

	public String getParametro3() {
		return parametro3;
	}

	public void setParametro3(String parametro3) {
		this.parametro3 = parametro3;
	}

	public String getEliminado() {
		return eliminado;
	}

	public void setEliminado(String eliminado) {
		this.eliminado = eliminado;
	}

	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getCreadoPor() {
		return creadoPor;
	}

	public void setCreadoPor(String creadoPor) {
		this.creadoPor = creadoPor;
	}

	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getModificadoPor() {
		return modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	public String getJob() {
		return job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	
}
