package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewRefreshStatus generated by hbm2java
 */
@Entity
@Table(name = "VIEW_REFRESH_STATUS")
public class ViewRefreshStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9011618728296769130L;
	private ViewRefreshStatusId id;

	public ViewRefreshStatus() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mensajeid", column = @Column(name = "MENSAJEID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "uim", column = @Column(name = "UIM", length = 50)),
			@AttributeOverride(name = "ultimoenvio", column = @Column(name = "ULTIMOENVIO", length = 7)),
			@AttributeOverride(name = "nodo", column = @Column(name = "NODO", precision = 22, scale = 0)) })
	public ViewRefreshStatusId getId() {
		return this.id;
	}

	public void setId(ViewRefreshStatusId id) {
		this.id = id;
	}

}
