package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewSMSId generated by hbm2java
 */
@Embeddable
public class ViewSMSId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7992843470985895176L;

	@Column(name = "IDENVIOSSMS", nullable = false, precision = 15, scale = 0)
	private long idenviossms;

	@Column(name = "IDSERVICIO", precision = 6, scale = 0)
	private Integer idservicio;

	@Column(name = "TELEFONO", length = 50)
	private String telefono;

	@Column(name = "TEXTOSMS", length = 2500)
	private String textosms;

	@Column(name = "ADTUSUARIO")
	private String adtusuario;

	@Column(name = "ADTFECHA", length = 7)
	private Date adtfecha;

	@Column(name = "ELIMINADO", length = 1)
	private Character eliminado;

	@Column(name = "ENVIADO", length = 1)
	private Character enviado;

	@Column(name = "IDCONVOCATORIA", precision = 6, scale = 0)
	private Integer idconvocatoria;

	@Column(name = "IDUSUARIO", nullable = false, precision = 6, scale = 0)
	private int idusuario;

	@Column(name = "NENVIOS", precision = 4, scale = 0)
	private Short nenvios;

	@Column(name = "UIM", length = 30)
	private String uim;

	@Column(name = "IDESTADO", precision = 6, scale = 0)
	private Integer idestado;

	@Column(name = "ANIO", precision = 4, scale = 0)
	private Short anio;

	@Column(name = "CUERPO")
	private String cuerpo;

	@Column(name = "TIPOINCIDENCIA")
	private String tipoincidencia;

	@Column(name = "CANALID", precision = 22, scale = 0)
	private Long canalid;

	public ViewSMSId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewSMSId))
			return false;
		ViewSMSId castOther = (ViewSMSId) other;

		return (this.getIdenviossms() == castOther.getIdenviossms())
				&& ((this.getIdservicio() == castOther.getIdservicio()) || (this
						.getIdservicio() != null
						&& castOther.getIdservicio() != null && this
						.getIdservicio().equals(castOther.getIdservicio())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this
						.getTelefono() != null
						&& castOther.getTelefono() != null && this
						.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getTextosms() == castOther.getTextosms()) || (this
						.getTextosms() != null
						&& castOther.getTextosms() != null && this
						.getTextosms().equals(castOther.getTextosms())))
				&& ((this.getAdtusuario() == castOther.getAdtusuario()) || (this
						.getAdtusuario() != null
						&& castOther.getAdtusuario() != null && this
						.getAdtusuario().equals(castOther.getAdtusuario())))
				&& ((this.getAdtfecha() == castOther.getAdtfecha()) || (this
						.getAdtfecha() != null
						&& castOther.getAdtfecha() != null && this
						.getAdtfecha().equals(castOther.getAdtfecha())))
				&& ((this.getEliminado() == castOther.getEliminado()) || (this
						.getEliminado() != null
						&& castOther.getEliminado() != null && this
						.getEliminado().equals(castOther.getEliminado())))
				&& ((this.getEnviado() == castOther.getEnviado()) || (this
						.getEnviado() != null && castOther.getEnviado() != null && this
						.getEnviado().equals(castOther.getEnviado())))
				&& ((this.getIdconvocatoria() == castOther.getIdconvocatoria()) || (this
						.getIdconvocatoria() != null
						&& castOther.getIdconvocatoria() != null && this
						.getIdconvocatoria().equals(
								castOther.getIdconvocatoria())))
				&& (this.getIdusuario() == castOther.getIdusuario())
				&& ((this.getNenvios() == castOther.getNenvios()) || (this
						.getNenvios() != null && castOther.getNenvios() != null && this
						.getNenvios().equals(castOther.getNenvios())))
				&& ((this.getUim() == castOther.getUim()) || (this.getUim() != null
						&& castOther.getUim() != null && this.getUim().equals(
						castOther.getUim())))
				&& ((this.getIdestado() == castOther.getIdestado()) || (this
						.getIdestado() != null
						&& castOther.getIdestado() != null && this
						.getIdestado().equals(castOther.getIdestado())))
				&& ((this.getAnio() == castOther.getAnio()) || (this.getAnio() != null
						&& castOther.getAnio() != null && this.getAnio()
						.equals(castOther.getAnio())))
				&& ((this.getCuerpo() == castOther.getCuerpo()) || (this
						.getCuerpo() != null && castOther.getCuerpo() != null && this
						.getCuerpo().equals(castOther.getCuerpo())))
				&& ((this.getTipoincidencia() == castOther.getTipoincidencia()) || (this
						.getTipoincidencia() != null
						&& castOther.getTipoincidencia() != null && this
						.getTipoincidencia().equals(
								castOther.getTipoincidencia())))
				&& ((this.getCanalid() == castOther.getCanalid()) || (this
						.getCanalid() != null && castOther.getCanalid() != null && this
						.getCanalid().equals(castOther.getCanalid())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdenviossms();
		result = 37
				* result
				+ (getIdservicio() == null ? 0 : this.getIdservicio()
						.hashCode());
		result = 37 * result
				+ (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result
				+ (getTextosms() == null ? 0 : this.getTextosms().hashCode());
		result = 37
				* result
				+ (getAdtusuario() == null ? 0 : this.getAdtusuario()
						.hashCode());
		result = 37 * result
				+ (getAdtfecha() == null ? 0 : this.getAdtfecha().hashCode());
		result = 37 * result
				+ (getEliminado() == null ? 0 : this.getEliminado().hashCode());
		result = 37 * result
				+ (getEnviado() == null ? 0 : this.getEnviado().hashCode());
		result = 37
				* result
				+ (getIdconvocatoria() == null ? 0 : this.getIdconvocatoria()
						.hashCode());
		result = 37 * result + this.getIdusuario();
		result = 37 * result
				+ (getNenvios() == null ? 0 : this.getNenvios().hashCode());
		result = 37 * result
				+ (getUim() == null ? 0 : this.getUim().hashCode());
		result = 37 * result
				+ (getIdestado() == null ? 0 : this.getIdestado().hashCode());
		result = 37 * result
				+ (getAnio() == null ? 0 : this.getAnio().hashCode());
		result = 37 * result
				+ (getCuerpo() == null ? 0 : this.getCuerpo().hashCode());
		result = 37
				* result
				+ (getTipoincidencia() == null ? 0 : this.getTipoincidencia()
						.hashCode());
		result = 37 * result
				+ (getCanalid() == null ? 0 : this.getCanalid().hashCode());
		return result;
	}

	/**
	 * @return the idenviossms
	 */
	public long getIdenviossms() {
		return idenviossms;
	}

	/**
	 * @param idenviossms
	 *            the idenviossms to set
	 */
	public void setIdenviossms(long idenviossms) {
		this.idenviossms = idenviossms;
	}

	/**
	 * @return the idservicio
	 */
	public Integer getIdservicio() {
		return idservicio;
	}

	/**
	 * @param idservicio
	 *            the idservicio to set
	 */
	public void setIdservicio(Integer idservicio) {
		this.idservicio = idservicio;
	}

	/**
	 * @return the telefono
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * @param telefono
	 *            the telefono to set
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * @return the textosms
	 */
	public String getTextosms() {
		return textosms;
	}

	/**
	 * @param textosms
	 *            the textosms to set
	 */
	public void setTextosms(String textosms) {
		this.textosms = textosms;
	}

	/**
	 * @return the adtusuario
	 */
	public String getAdtusuario() {
		return adtusuario;
	}

	/**
	 * @param adtusuario
	 *            the adtusuario to set
	 */
	public void setAdtusuario(String adtusuario) {
		this.adtusuario = adtusuario;
	}

	/**
	 * @return the adtfecha
	 */
	public Date getAdtfecha() {
		return adtfecha;
	}

	/**
	 * @param adtfecha
	 *            the adtfecha to set
	 */
	public void setAdtfecha(Date adtfecha) {
		this.adtfecha = adtfecha;
	}

	/**
	 * @return the eliminado
	 */
	public Character getEliminado() {
		return eliminado;
	}

	/**
	 * @param eliminado
	 *            the eliminado to set
	 */
	public void setEliminado(Character eliminado) {
		this.eliminado = eliminado;
	}

	/**
	 * @return the enviado
	 */
	public Character getEnviado() {
		return enviado;
	}

	/**
	 * @param enviado
	 *            the enviado to set
	 */
	public void setEnviado(Character enviado) {
		this.enviado = enviado;
	}

	/**
	 * @return the idconvocatoria
	 */
	public Integer getIdconvocatoria() {
		return idconvocatoria;
	}

	/**
	 * @param idconvocatoria
	 *            the idconvocatoria to set
	 */
	public void setIdconvocatoria(Integer idconvocatoria) {
		this.idconvocatoria = idconvocatoria;
	}

	/**
	 * @return the idusuario
	 */
	public int getIdusuario() {
		return idusuario;
	}

	/**
	 * @param idusuario
	 *            the idusuario to set
	 */
	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	/**
	 * @return the nenvios
	 */
	public Short getNenvios() {
		return nenvios;
	}

	/**
	 * @param nenvios
	 *            the nenvios to set
	 */
	public void setNenvios(Short nenvios) {
		this.nenvios = nenvios;
	}

	/**
	 * @return the uim
	 */
	public String getUim() {
		return uim;
	}

	/**
	 * @param uim
	 *            the uim to set
	 */
	public void setUim(String uim) {
		this.uim = uim;
	}

	/**
	 * @return the idestado
	 */
	public Integer getIdestado() {
		return idestado;
	}

	/**
	 * @param idestado
	 *            the idestado to set
	 */
	public void setIdestado(Integer idestado) {
		this.idestado = idestado;
	}

	/**
	 * @return the anio
	 */
	public Short getAnio() {
		return anio;
	}

	/**
	 * @param anio
	 *            the anio to set
	 */
	public void setAnio(Short anio) {
		this.anio = anio;
	}

	/**
	 * @return the cuerpo
	 */
	public String getCuerpo() {
		return cuerpo;
	}

	/**
	 * @param cuerpo
	 *            the cuerpo to set
	 */
	public void setCuerpo(String cuerpo) {
		this.cuerpo = cuerpo;
	}

	/**
	 * @return the tipoincidencia
	 */
	public String getTipoincidencia() {
		return tipoincidencia;
	}

	/**
	 * @param tipoincidencia
	 *            the tipoincidencia to set
	 */
	public void setTipoincidencia(String tipoincidencia) {
		this.tipoincidencia = tipoincidencia;
	}

	/**
	 * @return the canalid
	 */
	public Long getCanalid() {
		return canalid;
	}

	/**
	 * @param canalid
	 *            the canalid to set
	 */
	public void setCanalid(Long canalid) {
		this.canalid = canalid;
	}

}
