package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewSeridorOrganismo generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SERVIDOR_ORGANISMO")
public class ViewSeridorOrganismo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2261968224593201469L;
	private ViewSeridorOrganismoId id;

	public ViewSeridorOrganismo() {
	}

	public ViewSeridorOrganismo(ViewSeridorOrganismoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "organismoid", column = @Column(name = "ORGANISMOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "servidororganismoid", column = @Column(name = "SERVIDORORGANISMOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombreservidor", column = @Column(name = "NOMBRESERVIDOR", length = 100)),
			@AttributeOverride(name = "nombreorganismo", column = @Column(name = "NOMBREORGANISMO", nullable = false, length = 100)),
			@AttributeOverride(name = "dir3organismo", column = @Column(name = "DIR3ORGANISMO", nullable = false, length = 100)),
			@AttributeOverride(name = "numintentos", column = @Column(name = "NUMINTENTOS", precision = 10, scale = 0)),
			@AttributeOverride(name = "headersms", column = @Column(name = "HEADERSMS", length = 50)),
			@AttributeOverride(name = "proveedorusuariosms", column = @Column(name = "PROVEEDORUSUARIOSMS", length = 20)),
			@AttributeOverride(name = "proveedorpasswordsms", column = @Column(name = "PROVEEDORPASSWORDSMS", length = 20)) })
	public ViewSeridorOrganismoId getId() {
		return this.id;
	}

	public void setId(ViewSeridorOrganismoId id) {
		this.id = id;
	}

}
