package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewParametrosServidor generated by hbm2java
 */
@Entity
@Table(name = "VIEW_PARAMETROSSERVIDOR")
public class ViewParametrosServidor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7095301255709305522L;
	private ViewParametrosServidorId id;

	public ViewParametrosServidor() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "parametroservidorid", column = @Column(name = "PARAMETROSERVIDORID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tipoparametroid", column = @Column(name = "TIPOPARAMETROID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tiponombre", column = @Column(name = "TIPONOMBRE", nullable = false, length = 100)),
			@AttributeOverride(name = "valor", column = @Column(name = "VALOR", nullable = false, length = 200)),
			@AttributeOverride(name = "tipodescripcion", column = @Column(name = "TIPODESCRIPCION", length = 500)),
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "tipotag", column = @Column(name = "TIPOTAG", length = 100)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", nullable = false, length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", nullable = false, length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)) })
	public ViewParametrosServidorId getId() {
		return this.id;
	}

	public void setId(ViewParametrosServidorId id) {
		this.id = id;
	}

}
