package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewInformesServiciosCop generated by hbm2java
 */
@Entity
@Table(name = "VIEW_INFORMES_SERVICIOS_COP")
public class ViewInformesServiciosCop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8462011589115647007L;
	private ViewInformesServiciosCopId id;

	public ViewInformesServiciosCop() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "anno", column = @Column(name = "ANNO", precision = 4, scale = 0)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", precision = 2, scale = 0)),
			@AttributeOverride(name = "codorganismopagador", column = @Column(name = "CODORGANISMOPAGADOR", length = 20)),
			@AttributeOverride(name = "numtotal", column = @Column(name = "NUMTOTAL", precision = 22, scale = 0)) })
	public ViewInformesServiciosCopId getId() {
		return this.id;
	}

	public void setId(ViewInformesServiciosCopId id) {
		this.id = id;
	}

}
