package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewServidoresServicios generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SERVIDORES_SERVICIOS")
public class ViewServidoresServicios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2499544226758376446L;
	private ViewServidoresServiciosId id;

	public ViewServidoresServicios() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servidorid", column = @Column(name = "SERVIDORID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "servidorservicioid", column = @Column(name = "SERVIDORSERVICIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombreservidor", column = @Column(name = "NOMBRESERVIDOR", length = 100)),
			@AttributeOverride(name = "nombreservicio", column = @Column(name = "NOMBRESERVICIO", length = 100)),
			@AttributeOverride(name = "numintentos", column = @Column(name = "NUMINTENTOS", precision = 10, scale = 0)),
			@AttributeOverride(name = "headersms", column = @Column(name = "HEADERSMS", length = 50)),
			@AttributeOverride(name = "proveedorusuariosms", column = @Column(name = "PROVEEDORUSUARIOSMS", length = 20)),
			@AttributeOverride(name = "proveedorpasswordsms", column = @Column(name = "PROVEEDORPASSWORDSMS", length = 20)) })
	public ViewServidoresServiciosId getId() {
		return this.id;
	}

	public void setId(ViewServidoresServiciosId id) {
		this.id = id;
	}

}
