package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ViewHistoricoMultidest generated by hbm2java
 */
@Entity
@Table(name = "VIEW_HISTORICO_MULTIDEST")
public class ViewHistoricoMultidest implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3638893093253484083L;
	
	@Id
	@Column(name = "HISTORICOID", nullable = false, precision = 22, scale = 0)
	private Long historicoid;

	@Column(name = "MENSAJEID", precision = 22, scale = 0)
	private Long mensajeid;

	@Column(name = "DESTINATARIOSMENSAJES", precision = 22, scale = 0)
	private Long destinatariosmensajes;

	@Column(name = "ESTADOID", precision = 22, scale = 0)
	private Long estadoid;

	@Column(name = "SERVIDORID", precision = 22, scale = 0)
	private Long servidorid;

	@Column(name = "PLANIFICACIONID", precision = 22, scale = 0)
	private Long planificacionid;

	@Column(name = "ESTADO", nullable = false, length = 100)
	private String estado;

	@Column(name = "FECHA", length = 7)
	private Date fecha;

	@Column(name = "SERVIDOR", length = 100)
	private String servidor;

	@Column(name = "CODIGOEXTERNO", length = 100)
	private String codigoexterno;

	@Column(name = "USUARIO", length = 50)
	private String usuario;

	@Column(name = "PASSWORD", length = 50)
	private String password;

	@Column(name = "DESCRIPCION", length = 1000)
	private String descripcion;


	public ViewHistoricoMultidest() {
	}


	public Long getHistoricoid() {
		return historicoid;
	}


	public void setHistoricoid(Long historicoid) {
		this.historicoid = historicoid;
	}


	public Long getMensajeid() {
		return mensajeid;
	}


	public void setMensajeid(Long mensajeid) {
		this.mensajeid = mensajeid;
	}


	public Long getDestinatariosmensajes() {
		return destinatariosmensajes;
	}


	public void setDestinatariosmensajes(Long destinatariosmensajes) {
		this.destinatariosmensajes = destinatariosmensajes;
	}


	public Long getEstadoid() {
		return estadoid;
	}


	public void setEstadoid(Long estadoid) {
		this.estadoid = estadoid;
	}


	public Long getServidorid() {
		return servidorid;
	}


	public void setServidorid(Long servidorid) {
		this.servidorid = servidorid;
	}


	public Long getPlanificacionid() {
		return planificacionid;
	}


	public void setPlanificacionid(Long planificacionid) {
		this.planificacionid = planificacionid;
	}


	public String getEstado() {
		return estado;
	}


	public void setEstado(String estado) {
		this.estado = estado;
	}


	public Date getFecha() {
		return fecha;
	}


	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}


	public String getServidor() {
		return servidor;
	}


	public void setServidor(String servidor) {
		this.servidor = servidor;
	}


	public String getCodigoexterno() {
		return codigoexterno;
	}


	public void setCodigoexterno(String codigoexterno) {
		this.codigoexterno = codigoexterno;
	}


	public String getUsuario() {
		return usuario;
	}


	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	public String getDescripcion() {
		return descripcion;
	}


	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	

}
