package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewLogsId generated by hbm2java
 */
@Embeddable
public class ViewLogsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1533458954082880690L;

	@Column(name = "LOGID", nullable = false, precision = 22, scale = 0)
	private Long logid;

	@Column(name = "LOGDESCRIPCION", length = 1000)
	private String logdescripcion;

	@Column(name = "SOURCENAME", nullable = false, length = 100)
	private String sourcename;

	@Column(name = "SOURCEID", precision = 22, scale = 0)
	private Long sourceid;

	@Column(name = "SOURCEDESCRIPTION", length = 100)
	private String sourcedescription;

	@Column(name = "ADTUSUARIO", length = 100)
	private String adtusuario;

	@Column(name = "ADTFECHA", length = 7)
	private Date adtfecha;

	@Column(name = "LOGACCION", precision = 22, scale = 0)
	private Long logaccion;

	public ViewLogsId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewLogsId))
			return false;
		ViewLogsId castOther = (ViewLogsId) other;

		return ((this.getLogid() == castOther.getLogid()) || (this.getLogid() != null
				&& castOther.getLogid() != null && this.getLogid().equals(
				castOther.getLogid())))
				&& ((this.getLogdescripcion() == castOther.getLogdescripcion()) || (this
						.getLogdescripcion() != null
						&& castOther.getLogdescripcion() != null && this
						.getLogdescripcion().equals(
								castOther.getLogdescripcion())))
				&& ((this.getSourcename() == castOther.getSourcename()) || (this
						.getSourcename() != null
						&& castOther.getSourcename() != null && this
						.getSourcename().equals(castOther.getSourcename())))
				&& ((this.getSourceid() == castOther.getSourceid()) || (this
						.getSourceid() != null
						&& castOther.getSourceid() != null && this
						.getSourceid().equals(castOther.getSourceid())))
				&& ((this.getSourcedescription() == castOther
						.getSourcedescription()) || (this
						.getSourcedescription() != null
						&& castOther.getSourcedescription() != null && this
						.getSourcedescription().equals(
								castOther.getSourcedescription())))
				&& ((this.getAdtusuario() == castOther.getAdtusuario()) || (this
						.getAdtusuario() != null
						&& castOther.getAdtusuario() != null && this
						.getAdtusuario().equals(castOther.getAdtusuario())))
				&& ((this.getAdtfecha() == castOther.getAdtfecha()) || (this
						.getAdtfecha() != null
						&& castOther.getAdtfecha() != null && this
						.getAdtfecha().equals(castOther.getAdtfecha())))
				&& ((this.getLogaccion() == castOther.getLogaccion()) || (this
						.getLogaccion() != null
						&& castOther.getLogaccion() != null && this
						.getLogaccion().equals(castOther.getLogaccion())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getLogid() == null ? 0 : this.getLogid().hashCode());
		result = 37
				* result
				+ (getLogdescripcion() == null ? 0 : this.getLogdescripcion()
						.hashCode());
		result = 37
				* result
				+ (getSourcename() == null ? 0 : this.getSourcename()
						.hashCode());
		result = 37 * result
				+ (getSourceid() == null ? 0 : this.getSourceid().hashCode());
		result = 37
				* result
				+ (getSourcedescription() == null ? 0 : this
						.getSourcedescription().hashCode());
		result = 37
				* result
				+ (getAdtusuario() == null ? 0 : this.getAdtusuario()
						.hashCode());
		result = 37 * result
				+ (getAdtfecha() == null ? 0 : this.getAdtfecha().hashCode());
		result = 37 * result
				+ (getLogaccion() == null ? 0 : this.getLogaccion().hashCode());
		return result;
	}

	/**
	 * @return the logid
	 */
	public Long getLogid() {
		return logid;
	}

	/**
	 * @param logid
	 *            the logid to set
	 */
	public void setLogid(Long logid) {
		this.logid = logid;
	}

	/**
	 * @return the logdescripcion
	 */
	public String getLogdescripcion() {
		return logdescripcion;
	}

	/**
	 * @param logdescripcion
	 *            the logdescripcion to set
	 */
	public void setLogdescripcion(String logdescripcion) {
		this.logdescripcion = logdescripcion;
	}

	/**
	 * @return the sourcename
	 */
	public String getSourcename() {
		return sourcename;
	}

	/**
	 * @param sourcename
	 *            the sourcename to set
	 */
	public void setSourcename(String sourcename) {
		this.sourcename = sourcename;
	}

	/**
	 * @return the sourceid
	 */
	public Long getSourceid() {
		return sourceid;
	}

	/**
	 * @param sourceid
	 *            the sourceid to set
	 */
	public void setSourceid(Long sourceid) {
		this.sourceid = sourceid;
	}

	/**
	 * @return the sourcedescription
	 */
	public String getSourcedescription() {
		return sourcedescription;
	}

	/**
	 * @param sourcedescription
	 *            the sourcedescription to set
	 */
	public void setSourcedescription(String sourcedescription) {
		this.sourcedescription = sourcedescription;
	}

	/**
	 * @return the adtusuario
	 */
	public String getAdtusuario() {
		return adtusuario;
	}

	/**
	 * @param adtusuario
	 *            the adtusuario to set
	 */
	public void setAdtusuario(String adtusuario) {
		this.adtusuario = adtusuario;
	}

	/**
	 * @return the adtfecha
	 */
	public Date getAdtfecha() {
		return adtfecha;
	}

	/**
	 * @param adtfecha
	 *            the adtfecha to set
	 */
	public void setAdtfecha(Date adtfecha) {
		this.adtfecha = adtfecha;
	}

	/**
	 * @return the logaccion
	 */
	public Long getLogaccion() {
		return logaccion;
	}

	/**
	 * @param logaccion
	 *            the logaccion to set
	 */
	public void setLogaccion(Long logaccion) {
		this.logaccion = logaccion;
	}

}
