package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewInformesServiciosCodOrg generated by hbm2java
 */
@Entity
@Table(name = "VIEW_INFORMES_SERVICIOS_CODORG")
public class ViewInformesServiciosCodOrg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7025961445487337824L;
	private ViewInformesServiciosCodOrgId id;

	public ViewInformesServiciosCodOrg() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "anno", column = @Column(name = "ANNO", precision = 4, scale = 0)),
			@AttributeOverride(name = "mes", column = @Column(name = "MES", precision = 2, scale = 0)),
			@AttributeOverride(name = "codorganismo", column = @Column(name = "CODORGANISMO", length = 20)),
			@AttributeOverride(name = "numtotal", column = @Column(name = "NUMTOTAL", precision = 22, scale = 0)) })
	public ViewInformesServiciosCodOrgId getId() {
		return this.id;
	}

	public void setId(ViewInformesServiciosCodOrgId id) {
		this.id = id;
	}

}
