package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewUsuarios generated by hbm2java
 */
@Entity
@Table(name = "VIEW_USUARIOS")
public class ViewUsuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5406414134220600032L;
	private ViewUsuariosId id;

	public ViewUsuarios() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idcompuesto", column = @Column(name = "IDCOMPUESTO", length = 81)),
			@AttributeOverride(name = "usuarioid", column = @Column(name = "USUARIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", nullable = false, length = 100)),
			@AttributeOverride(name = "login", column = @Column(name = "LOGIN", length = 100)),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL", length = 100)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", nullable = false, length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", nullable = false, length = 150)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", length = 1)),
			@AttributeOverride(name = "rolid", column = @Column(name = "ROLID", precision = 22, scale = 0)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 150)),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "nombreaplicacion", column = @Column(name = "NOMBREAPLICACION", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)) })
	public ViewUsuariosId getId() {
		return this.id;
	}

	public void setId(ViewUsuariosId id) {
		this.id = id;
	}

}
