package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewGestionEnviosDetMultideId generated by hbm2java
 */
@Embeddable
public class ViewGestionEnviosDetMultideId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 90887247405064435L;

	@Column(name = "APLICACION", length = 100)
	private String aplicacion;

	@Column(name = "CANAL", length = 100)
	private String canal;

	@Column(name = "SERVICIO", length = 100)
	private String servicio;

	@Column(name = "ESTADO", nullable = false, length = 100)
	private String estado;

	@Column(name = "APLICACIONID", precision = 22, scale = 0)
	private Long aplicacionid;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "CANALID", precision = 22, scale = 0)
	private Long canalid;

	@Column(name = "LOTEENVIOID", precision = 22, scale = 0)
	private Long loteenvioid;

	@Column(name = "LOTEENVIO", length = 100)
	private String loteenvio;

	@Column(name = "MENSAJEID", nullable = false, precision = 22, scale = 0)
	private Long mensajeid;

	@Column(name = "ULTIMOENVIO", length = 7)
	private Date ultimoenvio;

	@Column(name = "ESTADOID", precision = 22, scale = 0)
	private Long estadoid;

	@Column(name = "IDEXTERNO", length = 100)
	private String idexterno;

	@Column(name = "USUARIO", length = 50)
	private String usuario;

	@Column(name = "PASSWORD", length = 50)
	private String password;

	@Column(name = "NUMEROENVIOS", precision = 10, scale = 0)
	private Integer numeroenvios;

	public ViewGestionEnviosDetMultideId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewGestionEnviosDetMultideId))
			return false;
		ViewGestionEnviosDetMultideId castOther = (ViewGestionEnviosDetMultideId) other;

		return ((this.getAplicacion() == castOther.getAplicacion()) || (this
				.getAplicacion() != null && castOther.getAplicacion() != null && this
				.getAplicacion().equals(castOther.getAplicacion())))
				&& ((this.getCanal() == castOther.getCanal()) || (this
						.getCanal() != null && castOther.getCanal() != null && this
						.getCanal().equals(castOther.getCanal())))
				&& ((this.getServicio() == castOther.getServicio()) || (this
						.getServicio() != null
						&& castOther.getServicio() != null && this
						.getServicio().equals(castOther.getServicio())))
				&& ((this.getEstado() == castOther.getEstado()) || (this
						.getEstado() != null && castOther.getEstado() != null && this
						.getEstado().equals(castOther.getEstado())))
				&& ((this.getAplicacionid() == castOther.getAplicacionid()) || (this
						.getAplicacionid() != null
						&& castOther.getAplicacionid() != null && this
						.getAplicacionid().equals(castOther.getAplicacionid())))
				&& ((this.getServicioid() == castOther.getServicioid()) || (this
						.getServicioid() != null
						&& castOther.getServicioid() != null && this
						.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getCanalid() == castOther.getCanalid()) || (this
						.getCanalid() != null && castOther.getCanalid() != null && this
						.getCanalid().equals(castOther.getCanalid())))
				&& ((this.getLoteenvioid() == castOther.getLoteenvioid()) || (this
						.getLoteenvioid() != null
						&& castOther.getLoteenvioid() != null && this
						.getLoteenvioid().equals(castOther.getLoteenvioid())))
				&& ((this.getLoteenvio() == castOther.getLoteenvio()) || (this
						.getLoteenvio() != null
						&& castOther.getLoteenvio() != null && this
						.getLoteenvio().equals(castOther.getLoteenvio())))
				&& ((this.getMensajeid() == castOther.getMensajeid()) || (this
						.getMensajeid() != null
						&& castOther.getMensajeid() != null && this
						.getMensajeid().equals(castOther.getMensajeid())))
				&& ((this.getUltimoenvio() == castOther.getUltimoenvio()) || (this
						.getUltimoenvio() != null
						&& castOther.getUltimoenvio() != null && this
						.getUltimoenvio().equals(castOther.getUltimoenvio())))
				&& ((this.getEstadoid() == castOther.getEstadoid()) || (this
						.getEstadoid() != null
						&& castOther.getEstadoid() != null && this
						.getEstadoid().equals(castOther.getEstadoid())))
				&& ((this.getIdexterno() == castOther.getIdexterno()) || (this
						.getIdexterno() != null
						&& castOther.getIdexterno() != null && this
						.getIdexterno().equals(castOther.getIdexterno())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null && castOther.getUsuario() != null && this
						.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getPassword() == castOther.getPassword()) || (this
						.getPassword() != null
						&& castOther.getPassword() != null && this
						.getPassword().equals(castOther.getPassword())))
				&& ((this.getNumeroenvios() == castOther.getNumeroenvios()) || (this
						.getNumeroenvios() != null
						&& castOther.getNumeroenvios() != null && this
						.getNumeroenvios().equals(castOther.getNumeroenvios())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAplicacion() == null ? 0 : this.getAplicacion()
						.hashCode());
		result = 37 * result
				+ (getCanal() == null ? 0 : this.getCanal().hashCode());
		result = 37 * result
				+ (getServicio() == null ? 0 : this.getServicio().hashCode());
		result = 37 * result
				+ (getEstado() == null ? 0 : this.getEstado().hashCode());
		result = 37
				* result
				+ (getAplicacionid() == null ? 0 : this.getAplicacionid()
						.hashCode());
		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37 * result
				+ (getCanalid() == null ? 0 : this.getCanalid().hashCode());
		result = 37
				* result
				+ (getLoteenvioid() == null ? 0 : this.getLoteenvioid()
						.hashCode());
		result = 37 * result
				+ (getLoteenvio() == null ? 0 : this.getLoteenvio().hashCode());
		result = 37 * result
				+ (getMensajeid() == null ? 0 : this.getMensajeid().hashCode());
		result = 37
				* result
				+ (getUltimoenvio() == null ? 0 : this.getUltimoenvio()
						.hashCode());
		result = 37 * result
				+ (getEstadoid() == null ? 0 : this.getEstadoid().hashCode());
		result = 37 * result
				+ (getIdexterno() == null ? 0 : this.getIdexterno().hashCode());
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result
				+ (getPassword() == null ? 0 : this.getPassword().hashCode());
		result = 37
				* result
				+ (getNumeroenvios() == null ? 0 : this.getNumeroenvios()
						.hashCode());
		return result;
	}

	/**
	 * @return the aplicacion
	 */
	public String getAplicacion() {
		return aplicacion;
	}

	/**
	 * @param aplicacion
	 *            the aplicacion to set
	 */
	public void setAplicacion(String aplicacion) {
		this.aplicacion = aplicacion;
	}

	/**
	 * @return the canal
	 */
	public String getCanal() {
		return canal;
	}

	/**
	 * @param canal
	 *            the canal to set
	 */
	public void setCanal(String canal) {
		this.canal = canal;
	}

	/**
	 * @return the servicio
	 */
	public String getServicio() {
		return servicio;
	}

	/**
	 * @param servicio
	 *            the servicio to set
	 */
	public void setServicio(String servicio) {
		this.servicio = servicio;
	}

	/**
	 * @return the estado
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * @param estado
	 *            the estado to set
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * @return the aplicacionid
	 */
	public Long getAplicacionid() {
		return aplicacionid;
	}

	/**
	 * @param aplicacionid
	 *            the aplicacionid to set
	 */
	public void setAplicacionid(Long aplicacionid) {
		this.aplicacionid = aplicacionid;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the canalid
	 */
	public Long getCanalid() {
		return canalid;
	}

	/**
	 * @param canalid
	 *            the canalid to set
	 */
	public void setCanalid(Long canalid) {
		this.canalid = canalid;
	}

	/**
	 * @return the loteenvioid
	 */
	public Long getLoteenvioid() {
		return loteenvioid;
	}

	/**
	 * @param loteenvioid
	 *            the loteenvioid to set
	 */
	public void setLoteenvioid(Long loteenvioid) {
		this.loteenvioid = loteenvioid;
	}

	/**
	 * @return the loteenvio
	 */
	public String getLoteenvio() {
		return loteenvio;
	}

	/**
	 * @param loteenvio
	 *            the loteenvio to set
	 */
	public void setLoteenvio(String loteenvio) {
		this.loteenvio = loteenvio;
	}

	/**
	 * @return the mensajeid
	 */
	public Long getMensajeid() {
		return mensajeid;
	}

	/**
	 * @param mensajeid
	 *            the mensajeid to set
	 */
	public void setMensajeid(Long mensajeid) {
		this.mensajeid = mensajeid;
	}

	/**
	 * @return the ultimoenvio
	 */
	public Date getUltimoenvio() {
		return ultimoenvio;
	}

	/**
	 * @param ultimoenvio
	 *            the ultimoenvio to set
	 */
	public void setUltimoenvio(Date ultimoenvio) {
		this.ultimoenvio = ultimoenvio;
	}

	/**
	 * @return the estadoid
	 */
	public Long getEstadoid() {
		return estadoid;
	}

	/**
	 * @param estadoid
	 *            the estadoid to set
	 */
	public void setEstadoid(Long estadoid) {
		this.estadoid = estadoid;
	}

	/**
	 * @return the idexterno
	 */
	public String getIdexterno() {
		return idexterno;
	}

	/**
	 * @param idexterno
	 *            the idexterno to set
	 */
	public void setIdexterno(String idexterno) {
		this.idexterno = idexterno;
	}

	/**
	 * @return the usuario
	 */
	public String getUsuario() {
		return usuario;
	}

	/**
	 * @param usuario
	 *            the usuario to set
	 */
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password
	 *            the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the numeroenvios
	 */
	public Integer getNumeroenvios() {
		return numeroenvios;
	}

	/**
	 * @param numeroenvios
	 *            the numeroenvios to set
	 */
	public void setNumeroenvios(Integer numeroenvios) {
		this.numeroenvios = numeroenvios;
	}

}
