package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewUsuariosAplicaciones generated by hbm2java
 */
@Entity
@Table(name = "VIEW_USUARIOS_APLICACIONES")
public class ViewUsuariosAplicaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4808829895827432046L;
	private ViewUsuariosAplicacionesId id;

	public ViewUsuariosAplicaciones() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "usuarioaplicacionid", column = @Column(name = "USUARIOAPLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "usuarioid", column = @Column(name = "USUARIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "aplicacionid", column = @Column(name = "APLICACIONID", precision = 22, scale = 0)),
			@AttributeOverride(name = "modo", column = @Column(name = "MODO", precision = 1, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "nombreaplicacion", column = @Column(name = "NOMBREAPLICACION", length = 100)),
			@AttributeOverride(name = "nombreusuario", column = @Column(name = "NOMBREUSUARIO", nullable = false, length = 100)),
			@AttributeOverride(name = "rolid", column = @Column(name = "ROLID", precision = 22, scale = 0)),
			@AttributeOverride(name = "activo", column = @Column(name = "ACTIVO", precision = 1, scale = 0)),
			@AttributeOverride(name = "eliminado", column = @Column(name = "ELIMINADO", length = 1)),
			@AttributeOverride(name = "rolusuario", column = @Column(name = "ROLUSUARIO", length = 22)) })
	public ViewUsuariosAplicacionesId getId() {
		return this.id;
	}

	public void setId(ViewUsuariosAplicacionesId id) {
		this.id = id;
	}

}
