package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewLotesEnvios generated by hbm2java
 */
@Entity
@Table(name = "VIEW_LOTESENVIOS")
public class ViewLotesEnvios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1261874366065874628L;
	private ViewLotesEnviosId id;

	public ViewLotesEnvios() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "loteenvioid", column = @Column(name = "LOTEENVIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", length = 100)),
			@AttributeOverride(name = "descripcion", column = @Column(name = "DESCRIPCION", length = 500)),
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "estadoenvioid", column = @Column(name = "ESTADOENVIOID", precision = 22, scale = 0)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)) })
	public ViewLotesEnviosId getId() {
		return this.id;
	}

	public void setId(ViewLotesEnviosId id) {
		this.id = id;
	}

}
