package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewServServidorPushId generated by hbm2java
 */
@Embeddable
public class ViewServServidorPushId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4462680859323135771L;

	@Column(name = "SERVIDORPUSHID", precision = 22, scale = 0)
	private Long servidorpushid;

	@Column(name = "PLATAFORMAID", precision = 22, scale = 0)
	private Long plataformaid;

	@Column(name = "URL", length = 500)
	private String url;

	@Column(name = "URLFEEDBACK", length = 500)
	private String urlfeedback;

	@Column(name = "PUERTOURL", length = 200)
	private String puertourl;

	@Column(name = "PUERTOURLFEEDBACK", length = 200)
	private String puertourlfeedback;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "PRIORIDAD", precision = 22, scale = 0)
	private Integer prioridad;

	public ViewServServidorPushId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewServServidorPushId))
			return false;
		ViewServServidorPushId castOther = (ViewServServidorPushId) other;

		return ((this.getServidorpushid() == castOther.getServidorpushid()) || (this
				.getServidorpushid() != null
				&& castOther.getServidorpushid() != null && this
				.getServidorpushid().equals(castOther.getServidorpushid())))
				&& ((this.getPlataformaid() == castOther.getPlataformaid()) || (this
						.getPlataformaid() != null
						&& castOther.getPlataformaid() != null && this
						.getPlataformaid().equals(castOther.getPlataformaid())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getUrlfeedback() == castOther.getUrlfeedback()) || (this
						.getUrlfeedback() != null
						&& castOther.getUrlfeedback() != null && this
						.getUrlfeedback().equals(castOther.getUrlfeedback())))
				&& ((this.getPuertourl() == castOther.getPuertourl()) || (this
						.getPuertourl() != null
						&& castOther.getPuertourl() != null && this
						.getPuertourl().equals(castOther.getPuertourl())))
				&& ((this.getPuertourlfeedback() == castOther
						.getPuertourlfeedback()) || (this
						.getPuertourlfeedback() != null
						&& castOther.getPuertourlfeedback() != null && this
						.getPuertourlfeedback().equals(
								castOther.getPuertourlfeedback())))
				&& ((this.getServicioid() == castOther.getServicioid()) || (this
						.getServicioid() != null
						&& castOther.getServicioid() != null && this
						.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getPrioridad() == castOther.getPrioridad()) || (this
						.getPrioridad() != null
						&& castOther.getPrioridad() != null && this
						.getPrioridad().equals(castOther.getPrioridad())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServidorpushid() == null ? 0 : this.getServidorpushid()
						.hashCode());
		result = 37
				* result
				+ (getPlataformaid() == null ? 0 : this.getPlataformaid()
						.hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37
				* result
				+ (getUrlfeedback() == null ? 0 : this.getUrlfeedback()
						.hashCode());
		result = 37 * result
				+ (getPuertourl() == null ? 0 : this.getPuertourl().hashCode());
		result = 37
				* result
				+ (getPuertourlfeedback() == null ? 0 : this
						.getPuertourlfeedback().hashCode());
		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37 * result
				+ (getPrioridad() == null ? 0 : this.getPrioridad().hashCode());
		return result;
	}

	/**
	 * @return the servidorpushid
	 */
	public Long getServidorpushid() {
		return servidorpushid;
	}

	/**
	 * @param servidorpushid
	 *            the servidorpushid to set
	 */
	public void setServidorpushid(Long servidorpushid) {
		this.servidorpushid = servidorpushid;
	}

	/**
	 * @return the plataformaid
	 */
	public Long getPlataformaid() {
		return plataformaid;
	}

	/**
	 * @param plataformaid
	 *            the plataformaid to set
	 */
	public void setPlataformaid(Long plataformaid) {
		this.plataformaid = plataformaid;
	}

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url
	 *            the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the urlfeedback
	 */
	public String getUrlfeedback() {
		return urlfeedback;
	}

	/**
	 * @param urlfeedback
	 *            the urlfeedback to set
	 */
	public void setUrlfeedback(String urlfeedback) {
		this.urlfeedback = urlfeedback;
	}

	/**
	 * @return the puertourl
	 */
	public String getPuertourl() {
		return puertourl;
	}

	/**
	 * @param puertourl
	 *            the puertourl to set
	 */
	public void setPuertourl(String puertourl) {
		this.puertourl = puertourl;
	}

	/**
	 * @return the puertourlfeedback
	 */
	public String getPuertourlfeedback() {
		return puertourlfeedback;
	}

	/**
	 * @param puertourlfeedback
	 *            the puertourlfeedback to set
	 */
	public void setPuertourlfeedback(String puertourlfeedback) {
		this.puertourlfeedback = puertourlfeedback;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the prioridad
	 */
	public Integer getPrioridad() {
		return prioridad;
	}

	/**
	 * @param prioridad
	 *            the prioridad to set
	 */
	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
