package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewServidoresPrioridadId generated by hbm2java
 */
@Embeddable
public class ViewServidoresPrioridadId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9104690048213723252L;

	@Column(name = "SERVIDORID", precision = 22, scale = 0)
	private Long servidorid;

	@Column(name = "IP", length = 200)
	private String ip;

	@Column(name = "USUARIO", length = 200)
	private String usuario;

	@Column(name = "CONTRASEÑA", length = 200)
	private String contrasena;

	@Column(name = "CONEXION", length = 200)
	private String conexion;

	@Column(name = "PUERTO", length = 200)
	private String puerto;

	@Column(name = "AUTENTIFICACION", length = 200)
	private String autentificacion;

	@Column(name = "TIEMPOESPERA", length = 200)
	private String tiempoespera;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "PRIORIDAD", precision = 22, scale = 0)
	private Integer prioridad;

	public ViewServidoresPrioridadId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewServidoresPrioridadId))
			return false;
		ViewServidoresPrioridadId castOther = (ViewServidoresPrioridadId) other;

		return ((this.getServidorid() == castOther.getServidorid()) || (this
				.getServidorid() != null && castOther.getServidorid() != null && this
				.getServidorid().equals(castOther.getServidorid())))
				&& ((this.getIp() == castOther.getIp()) || (this.getIp() != null
						&& castOther.getIp() != null && this.getIp().equals(
						castOther.getIp())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null && castOther.getUsuario() != null && this
						.getUsuario().equals(castOther.getUsuario())))
				&& ((this.getContrasena() == castOther.getContrasena()) || (this
						.getContrasena() != null
						&& castOther.getContrasena() != null && this
						.getContrasena().equals(castOther.getContrasena())))
				&& ((this.getConexion() == castOther.getConexion()) || (this
						.getConexion() != null
						&& castOther.getConexion() != null && this
						.getConexion().equals(castOther.getConexion())))
				&& ((this.getPuerto() == castOther.getPuerto()) || (this
						.getPuerto() != null && castOther.getPuerto() != null && this
						.getPuerto().equals(castOther.getPuerto())))
				&& ((this.getAutentificacion() == castOther
						.getAutentificacion()) || (this.getAutentificacion() != null
						&& castOther.getAutentificacion() != null && this
						.getAutentificacion().equals(
								castOther.getAutentificacion())))
				&& ((this.getTiempoespera() == castOther.getTiempoespera()) || (this
						.getTiempoespera() != null
						&& castOther.getTiempoespera() != null && this
						.getTiempoespera().equals(castOther.getTiempoespera())))
				&& ((this.getServicioid() == castOther.getServicioid()) || (this
						.getServicioid() != null
						&& castOther.getServicioid() != null && this
						.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getPrioridad() == castOther.getPrioridad()) || (this
						.getPrioridad() != null
						&& castOther.getPrioridad() != null && this
						.getPrioridad().equals(castOther.getPrioridad())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServidorid() == null ? 0 : this.getServidorid()
						.hashCode());
		result = 37 * result + (getIp() == null ? 0 : this.getIp().hashCode());
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37
				* result
				+ (getContrasena() == null ? 0 : this.getContrasena()
						.hashCode());
		result = 37 * result
				+ (getConexion() == null ? 0 : this.getConexion().hashCode());
		result = 37 * result
				+ (getPuerto() == null ? 0 : this.getPuerto().hashCode());
		result = 37
				* result
				+ (getAutentificacion() == null ? 0 : this.getAutentificacion()
						.hashCode());
		result = 37
				* result
				+ (getTiempoespera() == null ? 0 : this.getTiempoespera()
						.hashCode());
		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37 * result
				+ (getPrioridad() == null ? 0 : this.getPrioridad().hashCode());
		return result;
	}

	/**
	 * @return the servidorid
	 */
	public Long getServidorid() {
		return servidorid;
	}

	/**
	 * @param servidorid
	 *            the servidorid to set
	 */
	public void setServidorid(Long servidorid) {
		this.servidorid = servidorid;
	}

	/**
	 * @return the ip
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * @param ip
	 *            the ip to set
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * @return the usuario
	 */
	public String getUsuario() {
		return usuario;
	}

	/**
	 * @param usuario
	 *            the usuario to set
	 */
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	/**
	 * @return the contrasena
	 */
	public String getContrasena() {
		return contrasena;
	}

	/**
	 * @param contrasena
	 *            the contrasena to set
	 */
	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	/**
	 * @return the conexion
	 */
	public String getConexion() {
		return conexion;
	}

	/**
	 * @param conexion
	 *            the conexion to set
	 */
	public void setConexion(String conexion) {
		this.conexion = conexion;
	}

	/**
	 * @return the puerto
	 */
	public String getPuerto() {
		return puerto;
	}

	/**
	 * @param puerto
	 *            the puerto to set
	 */
	public void setPuerto(String puerto) {
		this.puerto = puerto;
	}

	/**
	 * @return the autentificacion
	 */
	public String getAutentificacion() {
		return autentificacion;
	}

	/**
	 * @param autentificacion
	 *            the autentificacion to set
	 */
	public void setAutentificacion(String autentificacion) {
		this.autentificacion = autentificacion;
	}

	/**
	 * @return the tiempoespera
	 */
	public String getTiempoespera() {
		return tiempoespera;
	}

	/**
	 * @param tiempoespera
	 *            the tiempoespera to set
	 */
	public void setTiempoespera(String tiempoespera) {
		this.tiempoespera = tiempoespera;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the prioridad
	 */
	public Integer getPrioridad() {
		return prioridad;
	}

	/**
	 * @param prioridad
	 *            the prioridad to set
	 */
	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
