package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ViewServicioOrganismos generated by hbm2java
 */
@Entity
@Table(name = "VIEW_SERVICIO_ORGANISMOS")
public class ViewServicioOrganismos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1296003348850725923L;
	private ViewServicioOrganismosId id;

	public ViewServicioOrganismos() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "servicioid", column = @Column(name = "SERVICIOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "organismoid", column = @Column(name = "ORGANISMOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "servicioorganismoid", column = @Column(name = "SERVICIOORGANISMOID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "nombreservicio", column = @Column(name = "NOMBRESERVICIO", length = 100)),
			@AttributeOverride(name = "nombreorganismo", column = @Column(name = "NOMBREORGANISMO", nullable = false, length = 100)),
			@AttributeOverride(name = "dir3organismo", column = @Column(name = "DIR3ORGANISMO", nullable = false, length = 100)),
			@AttributeOverride(name = "descripcionorganismo", column = @Column(name = "DESCRIPCIONORGANISMO", length = 500)),
			@AttributeOverride(name = "descripcionservicio", column = @Column(name = "DESCRIPCIONSERVICIO", length = 500)),
			@AttributeOverride(name = "creadopor", column = @Column(name = "CREADOPOR", length = 100)),
			@AttributeOverride(name = "fechacreacion", column = @Column(name = "FECHACREACION", length = 7)),
			@AttributeOverride(name = "modificadopor", column = @Column(name = "MODIFICADOPOR", length = 100)),
			@AttributeOverride(name = "fechamodificacion", column = @Column(name = "FECHAMODIFICACION", length = 7)) })
	public ViewServicioOrganismosId getId() {
		return this.id;
	}

	public void setId(ViewServicioOrganismosId id) {
		this.id = id;
	}

}
