package es.minhap.sim.model;

// Generated 18-jul-2016 10:57:14 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ViewServReceptorSMSId generated by hbm2java
 */
@Embeddable
public class ViewServReceptorSMSId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6354545614830718651L;

	@Column(name = "RECEPTORID", precision = 22, scale = 0)
	private Long receptorid;

	@Column(name = "URL", length = 500)
	private String url;

	@Column(name = "ID", length = 200)
	private String id;

	@Column(name = "TELEFONO", length = 200)
	private String telefono;

	@Column(name = "TEXTO", length = 200)
	private String texto;

	@Column(name = "UIM", length = 200)
	private String uim;

	@Column(name = "SERVICIOID", precision = 22, scale = 0)
	private Long servicioid;

	@Column(name = "PRIORIDAD", precision = 22, scale = 0)
	private Integer prioridad;

	public ViewServReceptorSMSId() {
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewServReceptorSMSId))
			return false;
		ViewServReceptorSMSId castOther = (ViewServReceptorSMSId) other;

		return ((this.getReceptorid() == castOther.getReceptorid()) || (this
				.getReceptorid() != null && castOther.getReceptorid() != null && this
				.getReceptorid().equals(castOther.getReceptorid())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getTelefono() == castOther.getTelefono()) || (this
						.getTelefono() != null
						&& castOther.getTelefono() != null && this
						.getTelefono().equals(castOther.getTelefono())))
				&& ((this.getTexto() == castOther.getTexto()) || (this
						.getTexto() != null && castOther.getTexto() != null && this
						.getTexto().equals(castOther.getTexto())))
				&& ((this.getUim() == castOther.getUim()) || (this.getUim() != null
						&& castOther.getUim() != null && this.getUim().equals(
						castOther.getUim())))
				&& ((this.getServicioid() == castOther.getServicioid()) || (this
						.getServicioid() != null
						&& castOther.getServicioid() != null && this
						.getServicioid().equals(castOther.getServicioid())))
				&& ((this.getPrioridad() == castOther.getPrioridad()) || (this
						.getPrioridad() != null
						&& castOther.getPrioridad() != null && this
						.getPrioridad().equals(castOther.getPrioridad())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getReceptorid() == null ? 0 : this.getReceptorid()
						.hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getTelefono() == null ? 0 : this.getTelefono().hashCode());
		result = 37 * result
				+ (getTexto() == null ? 0 : this.getTexto().hashCode());
		result = 37 * result
				+ (getUim() == null ? 0 : this.getUim().hashCode());
		result = 37
				* result
				+ (getServicioid() == null ? 0 : this.getServicioid()
						.hashCode());
		result = 37 * result
				+ (getPrioridad() == null ? 0 : this.getPrioridad().hashCode());
		return result;
	}

	/**
	 * @return the receptorid
	 */
	public Long getReceptorid() {
		return receptorid;
	}

	/**
	 * @param receptorid
	 *            the receptorid to set
	 */
	public void setReceptorid(Long receptorid) {
		this.receptorid = receptorid;
	}

	/**
	 * @return the url
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * @param url
	 *            the url to set
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the telefono
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * @param telefono
	 *            the telefono to set
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * @return the texto
	 */
	public String getTexto() {
		return texto;
	}

	/**
	 * @param texto
	 *            the texto to set
	 */
	public void setTexto(String texto) {
		this.texto = texto;
	}

	/**
	 * @return the uim
	 */
	public String getUim() {
		return uim;
	}

	/**
	 * @param uim
	 *            the uim to set
	 */
	public void setUim(String uim) {
		this.uim = uim;
	}

	/**
	 * @return the servicioid
	 */
	public Long getServicioid() {
		return servicioid;
	}

	/**
	 * @param servicioid
	 *            the servicioid to set
	 */
	public void setServicioid(Long servicioid) {
		this.servicioid = servicioid;
	}

	/**
	 * @return the prioridad
	 */
	public Integer getPrioridad() {
		return prioridad;
	}

	/**
	 * @param prioridad
	 *            the prioridad to set
	 */
	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
