package es.mpr.plataformamensajeria.ws.aplicacion.envio;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.3
 * Generated source version: 2.6.3
 * 
 */
@WebServiceClient(name = "EnvioAplicacionImplService", 
                  wsdlLocation = "/wsdl/enviarAplicacion.wsdl",
                  targetNamespace = "http://envio.aplicacion.ws.plataformamensajeria.minhap.es/") 
public class EnvioAplicacionImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://envio.aplicacion.ws.plataformamensajeria.minhap.es/", "EnvioAplicacionImplService");
    public final static QName EnvioAplicacionImplPort = new QName("http://envio.aplicacion.ws.plataformamensajeria.minhap.es/", "EnvioAplicacionImplPort");
    static {
        URL url = EnvioAplicacionImplService.class.getResource("/wsdl/enviarAplicacion.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(EnvioAplicacionImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/wsdl/enviarAplicacion.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public EnvioAplicacionImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnvioAplicacionImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnvioAplicacionImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IEnvioAplicacionService
     */
    @WebEndpoint(name = "EnvioAplicacionImplPort")
    public IEnvioAplicacionService getEnvioAplicacionImplPort() {
        return super.getPort(EnvioAplicacionImplPort, IEnvioAplicacionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEnvioAplicacionService
     */
    @WebEndpoint(name = "EnvioAplicacionImplPort")
    public IEnvioAplicacionService getEnvioAplicacionImplPort(WebServiceFeature... features) {
        return super.getPort(EnvioAplicacionImplPort, IEnvioAplicacionService.class, features);
    }

}
