package es.mpr.plataformamensajeria.ws.aplicacion.envio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.3
 * Generated source version: 2.6.3
 * 
 */
@WebService(targetNamespace = "http://envio.aplicacion.ws.plataformamensajeria.minhap.es/", name = "IEnvioAplicacionService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IEnvioAplicacionService {

    @WebResult(name = "envioAplicacioResponse", targetNamespace = "http://envio.aplicacion.ws.plataformamensajeria.minhap.es/", partName = "parameters")
    @WebMethod
    public EnvioAplicacioResponse recibirSmsAplicacion(
        @WebParam(partName = "parameters", name = "envioAplicacionRequest", targetNamespace = "http://envio.aplicacion.ws.plataformamensajeria.minhap.es/")
        EnvioAplicacionRequest parameters
    );
}
